Integrate Manifester with API activation key test
SatelliteQE/robottelo pull request #10019
Opened 2022-09-06 18:25 UTC by synkd

The API activation key test module currently contains a single test that
uses a cloned manifest. This PR switches that test to use Manifester to
obtain a manifest (via the session_entitlement_manifest fixture) as a
proof of concept for Robottelo/Manifester integration.

2022-09-06 18:47 UTC, JacobCallahan approved these changes

2022-09-06 19:28 UTC, synkd commented
The above test run failed because the GitLab MR to add conf/manifest.yaml has not been merged yet. So there's no conf/manifest.yaml available in CI yet. I will rerun once that MR is merged.

2022-09-06 20:05 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-06 22:24 UTC, latran reviewed
PRT still failing.  Please recheck.

2022-09-07 06:14 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-07 17:25 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-07 17:27 UTC, synkd commented
Trying again with https://github.com/SatelliteQE/robottelo/pull/10027 merged. This should get logging working, so I'll have a better idea of where the failure occurs. My current suspicion is that generating the access token is failing and thus the subsequent requests to the RHSM API are unable to authenticate.

2022-09-07 18:52 UTC, synkd commented
Here's the relevant log snippet:
```
[D 220907 18:02:13 manifester:43] Generating access token
[D 220907 18:02:13 helpers:13] Sending request to endpoint ['https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token']
[D 220907 18:02:13 helpers:15] Response status code is 200
[D 220907 18:02:13 helpers:13] Sending request to endpoint ['https://api.access.redhat.com/management/v1/allocations']
[D 220907 18:02:14 helpers:15] Response status code is 400
[D 220907 18:02:14 manifester:43] Generating access token
[D 220907 18:02:14 helpers:13] Sending request to endpoint ['https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token']
[D 220907 18:02:14 helpers:15] Response status code is 200
```
Manifester is getting a 200 response when generating the access token, then a 400 when trying to access the RHSM API, then it tries to generate a new access token, which it should only do if there is no access token. This suggests that an access token is not being returned initially, and subsequently, the RHSM API is giving a bad request response because an access token is not included in the request. I'm going to trigger another run and try to do some interactive troubleshooting while it's running.

2022-09-07 18:52 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-08 13:32 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-08 16:01 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-08 18:29 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-08 20:08 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-08 21:10 UTC, synkd commented
I have identified the source of the error by debugging on a running Robottelo pod:
```
(Epdb) manifest.allocation
{'error': {'code': 400, 'message': 'invalid version'}}
(Epdb) manifest.sat_version
'sat-6.12.0'
```
The issue is that the value of the `sat_version` parameter passed with the API call to create a subscription allocation must be in the form of `sat-x.y` and that versions are not valid until they have been released. So `sat-6.12` will not be a valid value until the Satellite 6.12 GA release. I'll need to determine how best to clean up this parameter. Once I implement that change, this test should pass.

2022-09-13 20:31 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-13 20:55 UTC, JacobCallahan requested changes
reorder imports checks failing. try running pre-commit against all files locally

2022-09-13 20:55 UTC, JacobCallahan commented on robottelo/config/__init__.py
> +configure_airgun()
check missing empty line after this

2022-09-13 23:39 UTC, mshriver commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-14 04:54 UTC, devendra104 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_activationkey.py::test_positive_fetch_product_content

2022-09-15 01:03 UTC, JacobCallahan approved these changes

2022-09-16 12:52 UTC, ogajduse approved these changes
ACK based on robottelo-pr-testing/1200 job.

2022-09-19 07:55 UTC, Gauravtalreja1 approved these changes

2022-09-19 07:55 UTC, merged