Move rh_cloud_utils to robottelo/utils/local_io
SatelliteQE/robottelo pull request #10018
Opened 2022-09-06 16:04 UTC by sambible

Simple work here, moving rh_cloud_utils under robottelo/utils and creating a new module there, local_io for any future similar operations. 

I'm not sure if this is the best way to do this, but these util methods have a real case to be external to tests ( several unique dependencies only used for the IO, shared amongst the tests in the class ).

2022-09-06 22:35 UTC, latran requested changes
Can you provide some test results for some sample runs in api, cli, and ui to ensure they pass with the corresponding changes?

2022-09-12 07:24 UTC, shweta83 commented
@sambible @JacobCallahan @jyejare how many io helper methods can we expect in future? Can there be single module with all helper methods related to io?

2022-09-12 16:45 UTC, sambible commented
trigger: test-robottelo
pytest: -v tests/foreman/ui/test_rhcloud_inventory.py

2022-09-12 16:46 UTC, sambible commented
moved to a module named IO and put the methods in the __init__.py of that module, so no seperate submodules
gonna get testrunner to do run the files now

2022-09-12 16:56 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_rhcloud_inventory.py

2022-09-12 17:47 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_rhcloud_inventory.py

2022-09-12 18:49 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/api/test_rhcloud_inventory.py

2022-09-14 14:00 UTC, mshriver approved these changes
As Shweta mentioned, we're unlikely to need `utils.io` to be a whole package, but it doesn't hurt.

2022-09-14 14:01 UTC, merged