[6.11.z] Port/refactor of f-m health tests from testfm
SatelliteQE/robottelo pull request #10350
Opened 2022-11-25 13:29 UTC by Satellite-QE

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10288

Description:

1. Port/refactor f-m health subcommand tests from TestFM to robottelo
https://github.com/SatelliteQE/testfm/blob/master/tests/test_health.py

It includes changes from https://github.com/SatelliteQE/robottelo/pull/10227, and it will be rebased when either PR is merged

2022-11-25 15:33 UTC, Gauravtalreja1 requested changes

2022-11-25 15:33 UTC, Gauravtalreja1 commented on tests/foreman/maintain/test_health.py
> +    :customercenario: true
typo `s/customercenario/customerscenario`

2022-11-25 15:33 UTC, Gauravtalreja1 commented on tests/foreman/maintain/test_health.py
> +    gems_path = '/usr/share/gems/gems/'
This path will change for el7 and el8
```suggestion
    gems_path = f"""{f"{'/opt/theforeman/tfm/root' if sat_maintain.os_version.major < 8 else ''}" + '/usr/share/gems/gems/'}"""
```

2022-11-30 15:41 UTC, Gauravtalreja1 commented
@shubhamsg199 Could you please update this PR, and run PRT?

2022-12-01 08:04 UTC, shubhamsg199 commented on tests/foreman/maintain/test_health.py
> +    gems_path = '/usr/share/gems/gems/'
Updated.

2022-12-01 08:05 UTC, Gauravtalreja1 commented
trigger: test-robottelo
pytest: tests/foreman/maintain/test_health.py

2022-12-01 11:37 UTC, Gauravtalreja1 commented
trigger: test-robottelo
pytest: tests/foreman/maintain/test_health.py
deploy_rhel_version: 7

2022-12-01 19:24 UTC, Gauravtalreja1 commented
trigger: test-robottelo
pytest: tests/foreman/maintain/test_health.py
deploy_rhel_version: 7

2022-12-02 13:12 UTC, shubhamsg199 commented
There were 4 test failures 2 of them related epel install which are fixed with recent commit remaining two are intermittent failures.

2022-12-02 13:33 UTC, shubhamsg199 commented
**Test Result for failed epel test:**
```
pytest -k test_positive_health_check_epel_repository tests/foreman/maintain/test_health.py
============================================= test session starts ==============================================================
platform linux -- Python 3.8.6, pytest-7.1.3, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/sganar/satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, forked-1.3.0, cov-3.0.0, xdist-2.5.0, ibutsu-2.2.4, fixture-tools-1.1.0, reportportal-5.1.2, lazy-fixture-0.6.3, mock-3.10.0
collected 33 items / 32 deselected / 1 selected                                                                                                                                                                                       

tests/foreman/maintain/test_health.py .                                                                                                                                                                                               [100%]

====================================== 1 passed in 68.83s (0:01:08) ============================================
```

2022-12-02 13:48 UTC, Gauravtalreja1 approved these changes
Nice job on handling changes for el7 and el8

2022-12-02 13:48 UTC, merged