change how client repo is sourced in rex tests
SatelliteQE/robottelo pull request #10404
Opened 2022-12-07 16:39 UTC by pondrejk

removes a workaround from pull provider rex tests:
```
pytest  tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_converted_to_pull_provider[rhel8]
=================================================== test session starts ===================================================
platform linux -- Python 3.10.8, pytest-7.2.0, pluggy-1.0.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/pondrejk/Documents/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, ibutsu-2.2.4, forked-1.4.0, cov-3.0.0, mock-3.10.0, xdist-3.0.2, reportportal-5.1.3
collected 47 items / 46 deselected / 1 selected                                                                           

tests/foreman/cli/test_remoteexecution.py .                                                                         [100%]
```

2022-12-07 16:39 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_converted_to_pull_provider[rhel8]

2022-12-08 07:38 UTC, pondrejk commented
PRT failes because it checked out 6.11 in that run, not sure how to force it to use 6.12, anyway passes locally

2022-12-13 10:32 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_converted_to_pull_provider[rhel8]

2022-12-13 15:49 UTC, devendra104 commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_converted_to_pull_provider[rhel8]

2022-12-16 16:53 UTC, Griffin-Sullivan approved these changes

2022-12-16 18:43 UTC, Gauravtalreja1 commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_converted_to_pull_provider

2022-12-19 13:26 UTC, ogajduse approved these changes
:100:

2022-12-19 17:55 UTC, ogajduse commented
I would change my opinion here. If we merge #10287 first, we can just use the value from the settings instead of fetching data from Ohsnap.

2022-12-20 06:48 UTC, jyejare requested changes
Missing Branch labels in this PR to auto-cherrypick!

2023-01-12 09:39 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_converted_to_pull_provider

2023-01-13 12:40 UTC, pondrejk commented
from prt:

```
09:46:44  ============================= test session starts ==============================
09:46:44  platform linux -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0
09:46:44  shared_function enabled - OFF - scope:  - storage: file
09:46:44  rootdir: /opt/app-root/src/robottelo, configfile: pyproject.toml
09:46:44  plugins: ibutsu-2.2.4, mock-3.10.0, reportportal-5.1.3, services-2.2.1, xdist-3.1.0
09:46:44  collected 47 items / 41 deselected / 6 selected
09:46:44  
11:18:00  tests/foreman/cli/test_remoteexecution.py .....E                         [100%]
```

the one error is "No host created" from Broker, not related to this PR's changes

2023-01-16 08:51 UTC, pondrejk commented
@Gauravtalreja1 @ogajduse @jyejare mind revisiting?

2023-01-16 19:11 UTC, ogajduse approved these changes
:+1:

2023-01-16 19:23 UTC, merged