fix how realm tests access proxy locations
SatelliteQE/robottelo pull request #10423
Opened 2022-12-12 14:27 UTC by pondrejk

this was causing `BoxKeyError` at some of realm tests

2022-12-12 15:08 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_realm.py -k test_negative_realm_update_invalid_type

2022-12-13 10:04 UTC, Gauravtalreja1 requested changes

2022-12-13 10:04 UTC, Gauravtalreja1 commented on tests/foreman/destructive/test_realm.py
>      request.addfinalizer(lambda: module_target_sat.cli.Realm(realm['id']).delete())
PRT failures appear to be caused by an incorrect fix in cleanup.py refactor [PR](https://github.com/SatelliteQE/robottelo/pull/9768/files#diff-d3671555df65a9a9c09455290c030fbe7f6a5ac589d62bbf77da561863cf9faaR94)
```suggestion
    request.addfinalizer(lambda: module_target_sat.cli.Realm.delete({'id': realm['id']}))
```

2022-12-13 10:31 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_realm.py -k test_negative_realm_update_invalid_type

2022-12-13 12:27 UTC, pondrejk commented
@Gauravtalreja1 thanks for that advice, passes now

2022-12-13 12:30 UTC, Gauravtalreja1 approved these changes

2022-12-14 16:00 UTC, jameerpathan111 approved these changes

2022-12-14 16:01 UTC, merged