C2 r component change
SatelliteQE/robottelo pull request #10884
Opened 2023-03-06 09:01 UTC by shweta83

2023-03-06 09:32 UTC, Gauravtalreja1 commented on tests/foreman/api/test_convert2rhel.py
> +:CaseComponent: Registration
Registration seems irrelevant here, Can you add some description about this change?

2023-03-09 09:58 UTC, lhellebr requested changes
This file has two tests, both of them test specifically convert2rhel. Since we have a component for that, I don't see any reason not to use it.

Are there plans to drop that component? If yes, may I suggest using a different component, like RemoteExecution or Ansible?

Registration really seems out of place - while registration happens as a part of the test, it's not what is being tested.

2023-03-22 08:46 UTC, Gauravtalreja1 commented
@shweta83 can this be closed in favour of PR #10863 ?

2023-03-22 08:50 UTC, shweta83 commented
> @shweta83 can this be closed in favour of PR #10863 ?

Yes we can close this one.

2023-03-22 08:50 UTC, shweta83 commented
Closing

2023-03-22 08:50 UTC, closed without merging