Hyperv:virt-who config CLI/API cases support for SCA enabled
SatelliteQE/robottelo pull request #10897
Opened 2023-03-07 08:45 UTC by yanpliu

CLI cases PASS
```
(robottelo_vv) [root@dell-per740-68-vm-04 robottelo]# pytest ./tests/foreman/virtwho/cli/test_hyperv_sca.py --disable-pytest-warnings -q
...                                                                                                                                                                                                         [100%]
3 passed, 3 deselected, 7 warnings in 311.43s (0:05:11)

```
API cases PASS
```
(robottelo_vv) [root@dell-per740-68-vm-04 robottelo]# pytest ./tests/foreman/virtwho/api/test_hyperv_sca.py --disable-pytest-warnings -q
...                                                                                                                                                                                                         [100%]
3 passed, 3 deselected, 21 warnings in 277.12s (0:04:37)

```

2023-03-10 21:24 UTC, JacobCallahan requested changes
Small changes

2023-03-10 21:24 UTC, JacobCallahan commented on tests/foreman/virtwho/api/test_hyperv_sca.py
> +        for value in values:
```suggestion
        for value in ['uuid', 'hostname']:
```

2023-03-10 21:24 UTC, JacobCallahan commented on tests/foreman/virtwho/cli/test_hyperv_sca.py
> +        for value in values:
```suggestion
        for value in ['uuid', 'hostname']:
```

2023-03-13 19:06 UTC, JacobCallahan approved these changes

2023-03-17 07:15 UTC, omkarkhatavkar approved these changes

2023-03-17 07:15 UTC, merged