Nutanix:virt-who config API cases support for SCA enabled
SatelliteQE/robottelo pull request #10895
Opened 2023-03-07 06:49 UTC by yanpliu

Cases : PASS
```
(robottelo_vv) [root@dell-per740-68-vm-04 robottelo]# pytest ./tests/foreman/virtwho/api/test_nutanix_sca.py --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 30 warnings in 509.62s (0:08:29)

```

2023-03-07 08:05 UTC, adarshdubey-star commented
trigger: test-robottelo
pytest: tests/foreman/virtwho/api/test_esx.py

2023-03-10 21:22 UTC, JacobCallahan requested changes
Small changes

2023-03-10 21:22 UTC, JacobCallahan commented on tests/foreman/virtwho/api/test_nutanix_sca.py
> +        for value in values:
```suggestion
        for value in ['uuid', 'hostname']:
```

2023-03-10 21:22 UTC, JacobCallahan commented on tests/foreman/virtwho/cli/test_nutanix_sca.py
> +        for value in values:
```suggestion
        for value in ['uuid', 'hostname']:
```

2023-03-13 19:06 UTC, JacobCallahan approved these changes

2023-03-21 09:25 UTC, Gauravtalreja1 requested changes

2023-03-21 09:25 UTC, Gauravtalreja1 commented on tests/foreman/virtwho/api/test_esx.py
> +        :id: 24bf4c5b-cc7a-40ac-9079-e59c73984081
@yanpliu Could you please revert this change for the test case ids? it seems irrelevant and resolve merge conflict

2023-03-28 16:25 UTC, shubhamsg199 approved these changes
ACK

2023-03-30 20:54 UTC, merged