adding skip marker for open BZ
SatelliteQE/robottelo pull request #10919
Opened 2023-03-09 12:00 UTC by vijaysawant

- Current tests are failing due to Open BZ's [#2167937](https://bugzilla.redhat.com/show_bug.cgi?id=2167937) & [#2133151](https://bugzilla.redhat.com/show_bug.cgi?id=2133151) , can not create new SCAP content.
- Adding a marker to avoid running these tests from execution.

2023-03-09 19:50 UTC, shubhamsg199 approved these changes
Ack

2023-03-13 07:50 UTC, jyejare requested changes

2023-03-13 07:50 UTC, jyejare commented on tests/foreman/ui/test_oscapcontent.py
> +@pytest.mark.skip_if_open("BZ:2167937, 2133151")
This wont work! Method `skip_if_open` only accepts a single number, so repeat the marker for every number, as below:
```suggestion
@pytest.mark.skip_if_open("BZ:2167937")
@pytest.mark.skip_if_open("BZ:2133151")
```

2023-03-13 07:50 UTC, jyejare commented on tests/foreman/ui/test_oscapcontent.py
> +@pytest.mark.skip_if_open("BZ:2167937, 2133151")
Repeat this for all below !

2023-03-13 10:20 UTC, jyejare approved these changes

2023-03-13 10:20 UTC, merged