Libvirt:virt-who config CLI/API cases support for SCA enabled
SatelliteQE/robottelo pull request #10911
Opened 2023-03-08 02:16 UTC by yanpliu

API cases PASS:
```
(robottelo_vv) [root@dell-per740-68-vm-04 robottelo]# pytest ./tests/foreman/virtwho/api/test_libvirt_sca.py --disable-pytest-warnings -q
...                                                                                                                                                                                                         [100%]
3 passed, 3 deselected, 21 warnings in 288.15s (0:04:48)

```

CLI cases PASS:
```
(robottelo_vv) [root@dell-per740-68-vm-04 robottelo]# pytest ./tests/foreman/virtwho/cli/test_libvirt_sca.py --disable-pytest-warnings -q
...                                                                                                                                                                                                         [100%]
3 passed, 3 deselected, 7 warnings in 304.75s (0:05:04)

```

2023-03-10 21:25 UTC, JacobCallahan requested changes

2023-03-10 21:25 UTC, JacobCallahan commented on tests/foreman/virtwho/api/test_libvirt_sca.py
> +        for value in values:
```suggestion
        for value in ['uuid', 'hostname']:
```

2023-03-10 21:25 UTC, JacobCallahan commented on tests/foreman/virtwho/cli/test_libvirt_sca.py
> +        for value in values:
```suggestion
        for value in ['uuid', 'hostname']:
```

2023-03-13 19:05 UTC, JacobCallahan approved these changes

2023-03-17 07:17 UTC, omkarkhatavkar approved these changes

2023-03-17 07:17 UTC, merged