Kubevirt:virt-who config CLI/API cases support for SCA enabled
SatelliteQE/robottelo pull request #10918
Opened 2023-03-09 05:50 UTC by yanpliu

CLI cases PASS
```
(robottelo_vv) [root@dell-per740-68-vm-04 robottelo]# pytest ./tests/foreman/virtwho/cli/test_kubevirt_sca.py --disable-pytest-warnings -q
...                                                                                                                                                                                                         [100%]
3 passed, 3 deselected, 7 warnings in 431.61s (0:07:11)

```
API cases PASS
```
(robottelo_vv) [root@dell-per740-68-vm-04 robottelo]# pytest ./tests/foreman/virtwho/api/test_kubevirt_sca.py --disable-pytest-warnings -q
...                                                                                                                                                                                                         [100%]
3 passed, 3 deselected, 21 warnings in 614.58s (0:10:14)

```

2023-03-10 21:26 UTC, JacobCallahan requested changes

2023-03-10 21:26 UTC, JacobCallahan commented on tests/foreman/virtwho/api/test_kubevirt_sca.py
> +        for value in values:
```suggestion
        for value in ['uuid', 'hostname']:
```

2023-03-10 21:26 UTC, JacobCallahan commented on tests/foreman/virtwho/cli/test_kubevirt_sca.py
> +        for value in values:
```suggestion
        for value in ['uuid', 'hostname']:
```

2023-03-13 19:05 UTC, JacobCallahan approved these changes

2023-03-17 07:10 UTC, omkarkhatavkar approved these changes

2023-03-17 07:10 UTC, merged