[Host]-Refactor upgrade tests for Host
SatelliteQE/robottelo pull request #11120
Opened 2023-03-31 14:17 UTC by omkarkhatavkar

2023-04-05 14:42 UTC, jyejare requested changes
ACK pending questions/comments

2023-04-05 14:42 UTC, jyejare commented on tests/upgrades/test_host.py
> +        assert class_host.ip == self.google_host(googleclient, None)
Need not to be explicit  with `None` as its none by default in function defination.

2023-04-05 14:42 UTC, jyejare commented on tests/upgrades/test_host.py
> +                'cr_name': module_gce_compute_puppet.name,
Proabably you should be able to retrive all the other attributes from host object. So just keep host_name and we are good.

2023-04-10 12:27 UTC, adarshdubey-star commented on tests/upgrades/test_host.py
> +            puppet_ca_proxy=session_puppet_enabled_proxy,
I see @omkarkhatavkar testing it out with non-puppet sat and it should work fine

2023-04-10 12:29 UTC, adarshdubey-star commented on pytest_fixtures/component/provision_gce.py
> +    return ptable
You can get rid of this one we have https://github.com/SatelliteQE/robottelo/blob/master/pytest_fixtures/component/partition_table.py#L6
```suggestion
```

2023-04-10 12:58 UTC, omkarkhatavkar commented on tests/upgrades/test_host.py
> +            return googleclient.get_vm(name='{}'.format(self.fullhostname.replace('.', '-')))
`self.fullhostname ` has a static value that needs for assertion.

2023-04-10 17:35 UTC, JacobCallahan approved these changes

2023-04-11 04:25 UTC, adarshdubey-star approved these changes
Nicely done @omkarkhatavkar :)

2023-04-12 14:45 UTC, jyejare approved these changes

2023-04-12 14:45 UTC, merged