Add autoflake in precommit check
SatelliteQE/robottelo pull request #11619
Opened 2023-06-07 10:50 UTC by shweta83

**Why do we need it?** Existing pre-commit checks doesn't remove unused imports and variables from the code. With autoflake, it remove these unused imports and variables in-place and avoids the manual effort.

2023-06-08 08:28 UTC, adarshdubey-star commented
Can you take a look at the checks once

2023-06-21 11:58 UTC, ogajduse commented on .pre-commit-config.yaml
> +      - "--remove-all-unused-imports"
Can you try configuring autoflake in `pyproject.toml` instead?

2023-06-22 11:28 UTC, jyejare requested changes
In CI chcks, One of the autoflake plugin trying to remove `pass` keyword from code which is not necessary to remove as they are placeholders and required to function the functions properly !

Please rectify the issue!

2023-06-22 17:23 UTC, jyejare commented
Agree but using pass is a common behavior in programmers and that also tells it is not implemented.


I really dont see we should have any checks to remove it. Probably we can ignore that check from the hook.

2023-06-23 09:35 UTC, ogajduse commented
> Agree but using pass is a common behavior in programmers and that also tells it is not implemented.
> 
> I really dont see we should have any checks to remove it. Probably we can ignore that check from the hook.

Agreed, using `pass` is a common habit, but that does not mean that we have to necessarily follow it.

[PEP 257](https://www.python.org/dev/peps/pep-0257/#specification) states
> A docstring is a string literal that occurs as the first statement in a module, function, class, or method definition. Such a docstring becomes the __doc__ special attribute of that object.

That means that if the function has `__doc__` defined, you do not have to explicitly state that the function is no-op by adding `pass` statement.

Also, `pass` does not tell you that the function is not implemented. We rather use the `NotImplementedError` exception for such cases. If the function is to be implemented, we should rather use [Ellipsis](https://docs.python.org/3/library/constants.html#Ellipsis).

There is a [nice thread](https://stackoverflow.com/a/49754261) on this topic on Stack Overflow.

Since autoflake is developed by [PyCQA](https://github.com/PyCQA), I would trust them and go with what their tools suggest.

2023-06-23 15:08 UTC, jyejare commented
@ogajduse Sure! And thanks for the nice explanation!  Well still I will keep my NACK to fix the files which has `pass` statement in them and to pass the checks !

2023-07-05 11:59 UTC, jyejare commented
@ogajduse @shweta83 The failing checks are still needed to be fixed in this PR else it will fail for all other PRs post merge!

2023-07-21 08:40 UTC, lhellebr commented
About `pass` vs `...`, this sums it up quite nicely: https://stackoverflow.com/questions/55274977/when-is-the-usage-of-the-python-ellipsis-to-be-preferred-over-pass
@ogajduse , why do you think "If the function is to be implemented, we should rather use Ellipsis."? I don't agree with that one.
OTOH, I do agree that we should use NotImplementedError more.

2023-07-25 11:21 UTC, ogajduse commented
@lhellebr I perhaps did not study it deeper. I do not have a strong opinion on whether to use Ellipsis or `pass`

2023-09-12 14:25 UTC, ogajduse commented
I am in favor of closing this PR as there is a plan to include [ruff](beta.ruff.rs/) into our workflow in robottelo in the same way as in broker, nailgun, and airgun.

2023-09-14 09:57 UTC, ogajduse commented
Ruff added as a part of #12621

2023-10-03 12:11 UTC, jyejare commented
@shweta83 We should now close this as we have ruff in place now! 

Thanks for all your efforts though 👍

2023-10-03 12:11 UTC, closed without merging