Fix 4-digit logic in VersionedContent.download_repofile()
SatelliteQE/robottelo pull request #12057
Opened 2023-07-31 13:21 UTC by lpramuk

`download_repofile()` needlessly shortens 4 digit satellite version to 3 digits

Found when PR testing https://github.com/SatelliteQE/robottelo/pull/12049#issuecomment-1656731416

2023-07-31 14:36 UTC, ogajduse requested changes
Please do the same change in `robottelo/utils/ohsnap.py`.

2023-07-31 15:26 UTC, lpramuk commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_clone.py

2023-07-31 17:15 UTC, lpramuk commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_clone.py
env:
    ROBOTTELO_server__version__release: '6.13.3'
    ROBOTTELO_server__version__snap: '2.0'

2023-07-31 17:18 UTC, lpramuk commented
PRT is failing due to maven:3.8 bug

2023-08-01 08:47 UTC, jameerpathan111 approved these changes

2023-08-01 09:15 UTC, Gauravtalreja1 approved these changes

2023-08-01 09:25 UTC, ogajduse approved these changes

2023-08-01 09:28 UTC, merged