Add health check test for verify_dhcp_config_syntax
SatelliteQE/robottelo pull request #12446
Opened 2023-09-01 18:56 UTC by Griffin-Sullivan

Unstubbing and automating health check test for foreman-proxy-verify-dhcp-config-syntax as part of the foreman-maintain audit.

2023-09-01 18:56 UTC, Griffin-Sullivan commented
trigger: test-robottelo
pytest: tests/foreman/maintain/test_health.py::test_positive_health_check_foreman_proxy_verify_dhcp_config_syntax

2023-09-06 09:38 UTC, jameerpathan111 requested changes

2023-09-06 09:38 UTC, jameerpathan111 commented on tests/foreman/maintain/test_health.py
>      :CaseAutomation: NotAutomated
```suggestion
    :CaseAutomation: Automated
```

2023-09-06 13:47 UTC, jameerpathan111 approved these changes

2023-09-06 13:50 UTC, merged