fixture support for virt-who config cli : data_form deploy_type virtwho_config delete_host& manifest content move
SatelliteQE/robottelo pull request #12619
Opened 2023-09-14 08:22 UTC by yanpliu

Tasks:
1. fixture support for virt-who config cli : data_form deploy_type virtwho_config delete_host
2. module_sca_manifest content move because module_sca_manifest.content can not found

Cases PASS
```
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx.py  --disable-pytest-warnings -q
............                                                                                                                                                                                                [100%]

12 passed, 12 deselected, 7 warnings in 1140.02s (0:19:00)
(robottelo_vv_311_master) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx_sca.py --disable-pytest-warnings -q
................                                                                                                                                                                                            [100%]
16 passed, 16 deselected, 7 warnings in 2903.38s (0:48:23)

(robottelo_vv_311_master) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_hyperv.py --disable-pytest-warnings -q
...                                                                                                                                                                                                         [100%]
3 passed, 3 deselected in 574.06s (0:09:34)

(robottelo_vv_311_master) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_hyperv_sca.py --disable-pytest-warnings -q
...                                                                                                                                                                                                         [100%]
3 passed, 3 deselected in 539.66s (0:08:59)

(robottelo_vv_311_master) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_libvirt**.py --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 5 warnings in 622.06s (0:10:22)

(robottelo_vv_311_master) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_kubevirt**.py --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 5 warnings in 832.63s (0:13:52)
(robottelo_vv_311_master) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_nutanix**.py --disable-pytest-warnings -q
.............                                                                                                                                                                                               [100%]
13 passed, 13 deselected, 5 warnings in 1341.35s (0:22:21)
```

2023-09-29 14:33 UTC, JacobCallahan requested changes
ACK on content, but can you rebase this and run pre-commit on these files?

2023-10-09 08:33 UTC, yanpliu commented
> ACK on content, but can you rebase this and run pre-commit on these files?

@JacobCallahan Hello Jack, have already rebased the fix the conflict.

2023-10-09 20:40 UTC, JacobCallahan approved these changes

2023-10-10 07:27 UTC, shubhamsg199 requested changes

2023-10-10 07:27 UTC, shubhamsg199 commented on pytest_fixtures/component/taxonomy.py
> +    module_target_sat.upload_manifest(module_org.id, module_sca_manifest)
This has already been fixed, can you revert it?

2023-11-17 12:13 UTC, Gauravtalreja1 commented
@yanpliu Try rebase and `pre-commit autoupdate; pre-commit run --all-files` locally to fix pre-commit checks here.

2023-11-20 04:15 UTC, yanpliu commented
> @yanpliu Try rebase and `pre-commit autoupdate; pre-commit run --all-files` locally to fix pre-commit checks here.

Thank you very much Gaurav, have already fixed, could you please review and merge the PR? Thanks

2023-11-23 00:47 UTC, yanpliu commented
Hello, can you help to review and merge this PR? Thank you very much . As satellite6.15 is coming ,this PR influence most of the cases, thank you very much

2023-11-27 01:25 UTC, yanpliu commented
@Gauravtalreja1 Could you please help to review and merge this PR? because this PR has influcence to PRs have been merged already. #12640 #12620 . And can this PR can merge to satellite6.15? Shall I need to submit these changes on satellite6.15?

2023-11-30 14:31 UTC, Gauravtalreja1 approved these changes

2023-11-30 14:31 UTC, merged