fixture support for virt-who config ui : data_form deploy_type virtwho_config
SatelliteQE/robottelo pull request #12640
Opened 2023-09-16 09:09 UTC by yanpliu

fixture support for virt-who config api : data_form deploy_type virtwho_config
depend on https://github.com/SatelliteQE/robottelo/pull/12619 remove content for manifest
Cases PASS:
```
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_hyperv**.py --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 14 warnings in 2253.83s (0:37:33)

(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx**.py --disable-pytest-warnings -q
..................................                                                                                                                                                                          [100%]

34 passed, 34 deselected, 22 warnings in 7530.92s (2:05:30)
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_libvirt**.py --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 14 warnings in 1887.52s (0:31:27)

(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_kubevirt**.py --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 14 warnings in 1976.89s (0:32:56)
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_nutanix**.py --disable-pytest-warnings -q
..............E                                                                                                                                                                                             [100%]
14 passed, 14 deselected, 14 warnings, 1 error in 4094.89s (1:08:14)
```

2023-09-29 14:35 UTC, JacobCallahan requested changes
Much like the other PR, can you rebase this and rerun pre-commit on the contents? To make merge conflicts easier to resolve, try keeping your side of the changes, then let the Ruff tool format the imports.

2023-10-10 00:37 UTC, yanpliu commented
> Much like the other PR, can you rebase this and rerun pre-commit on the contents? To make merge conflicts easier to resolve, try keeping your side of the changes, then let the Ruff tool format the imports.

@JacobCallahan Hello Jake, have already rebase and fixt the conflict

2023-10-10 07:30 UTC, shubhamsg199 approved these changes

2023-10-10 20:39 UTC, JacobCallahan approved these changes

2023-10-10 20:39 UTC, merged