Add coverage for 2055790 to service enable disable
SatelliteQE/robottelo pull request #12756
Opened 2023-09-27 14:42 UTC by Griffin-Sullivan

The first commit here is a cherry-pick of an old PR that I accidentally removed in one of my Foreman Maintain audits. I must not have had the latest changes on that branch. I'm adding that back in and also adding coverage for 2055790.

2023-09-27 14:42 UTC, Griffin-Sullivan commented
trigger: test-robottelo
pytest: tests/foreman/maintain/test_service.py::test_positive_service_enable_disable

2023-09-27 16:20 UTC, Griffin-Sullivan commented
trigger: test-robottelo
pytest: tests/foreman/maintain/test_service.py::test_positive_service_enable_disable

2023-09-29 14:46 UTC, JacobCallahan requested changes
One minor change

2023-09-29 14:46 UTC, JacobCallahan commented on tests/foreman/maintain/test_service.py
> +    if type(sat_maintain) is Satellite:
`isinstance` is prefered over `type` for type checking.
```suggestion
    if isinstance(sat_maintain, Satellite):
```

2023-10-02 13:33 UTC, Griffin-Sullivan commented
trigger: test-robottelo
pytest: tests/foreman/maintain/test_service.py::test_positive_service_enable_disable

2023-10-03 16:31 UTC, sambible approved these changes
PRT passing, looks good

2023-10-03 16:33 UTC, merged