[Repository Rewrite] Adding test for available_repositories endpoint
SatelliteQE/robottelo pull request #12888
Opened 2023-10-11 20:58 UTC by ColeHiggins2

[SAT-13275]

Attempt to hit the /available_repositories endpoint with no failures

:Steps:
    1. Enable a Red Hat Repository
    2. Attempt to hit the enpoint:
        GET /katello/api/repository_sets/:id/available_repositories
    3. Verify Actions::Katello::RepositorySet::ScanCdn task is run
    4. Verify there are no failures when scanning for repository

2023-10-12 17:48 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k test_positive_available_repositories_endpoint

2023-10-12 17:49 UTC, sambible approved these changes
👍 pending PRT

2023-10-12 18:10 UTC, damoore044 approved these changes
looks good prt pending!

2023-10-13 09:03 UTC, vsedmik requested changes

2023-10-13 09:03 UTC, vsedmik commented on tests/foreman/api/test_repositories.py
> +        reposet=constants.REPOSET['rhst8'],
I would prefer single source of truth:
```suggestion
        product=constants.REPOS['rhst8']['product'],
        repo=constants.REPOS['rhst8']['name'],
        reposet=constants.REPOS['rhst8']['reposet'],
```
This way you can have `'rhst8'` as a parameter, not hard-coded, and possibly parametrize the test with different repos.

Last thing, I would rather use more up-to-date repo than `satellite-tools-6.9-for-rhel-8-x86_64-rpms`, or some more frequent one(s). The BZ talks about `rhel-7-server-extras-rpms`, which would be `REPOS['rhel7_extra']`.

2023-10-16 19:15 UTC, vsedmik approved these changes

2023-10-16 19:16 UTC, vsedmik commented
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k test_positive_available_repositories_endpoint

2023-10-16 19:40 UTC, merged