[6.14.z] Cherrypick test sync multiple large repos 6.14.z
SatelliteQE/robottelo pull request #12946
Opened 2023-10-19 17:56 UTC by ColeHiggins2

ParentPR: https://github.com/SatelliteQE/robottelo/pull/12445

2023-10-20 06:22 UTC, Gauravtalreja1 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k test_positive_sync_mulitple_large_repos

2023-10-20 06:28 UTC, Gauravtalreja1 commented
@ColeHiggins2 We already had the cherrypicked PR https://github.com/SatelliteQE/robottelo/pull/12741 for this, this issue must be created due to intermittent memory issue, so  would suggest to check the original PR where cherrypicked PRs and created issues will be linked, so before manually cherrypicking a PR we should be verifying if it is not already cherrypicked in some PR :)
Will close PR https://github.com/SatelliteQE/robottelo/pull/12741 for now

2023-10-20 14:41 UTC, lhellebr requested changes
Logicx of this seems ok.

There are a few comments from me pointing to either a bad naming or bad understanding of what's actually happening - you should think about it and rename accordingly.

Also, think about putting this test to `longrun` because, well, it may run long.

2023-10-26 17:16 UTC, Gauravtalreja1 commented
@ColeHiggins2 Can you rebase and run pre-commit locally? and take a look at the @lhellebr's comments

2023-11-22 12:47 UTC, adarshdubey-star commented
Ping @ColeHiggins2

2023-11-27 20:56 UTC, ColeHiggins2 commented on tests/foreman/api/test_repositories.py
> +        rh_repo_id = module_target_sat.api_factory.enable_rhrepo_and_fetchid(
I can remove this var and see if it passes prt

2023-11-27 20:57 UTC, ColeHiggins2 commented on tests/foreman/api/test_repositories.py
> +    rh_products = module_target_sat.api.Product(id=rh_repos.product.id).read()
updating to singular

2023-11-28 18:58 UTC, Gauravtalreja1 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_repositories.py -k test_positive_sync_mulitple_large_repos

2023-11-29 17:45 UTC, Gauravtalreja1 approved these changes

2023-11-29 17:45 UTC, merged