removing the from nailgun import entities and moving target_sat, module_target_sat
SatelliteQE/robottelo pull request #12989
Opened 2023-10-26 10:59 UTC by omkarkhatavkar

#### WIP

2023-10-29 14:42 UTC, omkarkhatavkar commented
trigger: test-robottelo

2023-10-30 09:01 UTC, omkarkhatavkar commented
trigger: test-robottelo

2023-10-30 10:28 UTC, omkarkhatavkar commented
@shweta83 @vsedmik @pondrejk @Griffin-Sullivan Can you please also take a look from the components side as it is touching multiple component tests.

2023-10-31 10:23 UTC, Gauravtalreja1 commented
@omkarkhatavkar Great job, thanks for this refactor ❤️
Could you add changes for updating fixtures, and setup part done by nailgun entities in CLI/UI/destructive/etc modules too? or are you intending to open a separate PR for each?

2023-10-31 10:34 UTC, shweta83 commented
@omkarkhatavkar Changes impacting Rocket team components are good. Ack for the rocket team tests except for  @Gauravtalreja1 comment.

2023-10-31 11:21 UTC, omkarkhatavkar commented
> @omkarkhatavkar Great job, thanks for this refactor ❤️ Could you add changes for updating fixtures, and setup part done by nailgun entities in CLI/UI/destructive/etc modules too? or are you intending to open a separate PR for each?

@Gauravtalreja1 It will be the seperate PR's as It will be easy to test it out and also review will be smoother

2023-10-31 12:37 UTC, lpramuk approved these changes

2023-10-31 12:40 UTC, Griffin-Sullivan approved these changes
As far as I can tell, none of these components are owned by Platform. Everything looks good to me!

2023-11-02 14:56 UTC, ColeHiggins2 approved these changes
Looks good to me! Nice work

2023-11-02 18:14 UTC, JacobCallahan commented
@omkarkhatavkar please rebase and we'll get this in!

2023-11-02 18:49 UTC, JacobCallahan requested changes
one minor change

2023-11-02 18:49 UTC, JacobCallahan commented on tests/foreman/api/test_organization.py
> +    target_sat.api.)
we can revert this change ;)

2023-11-03 09:09 UTC, omkarkhatavkar commented
trigger: test-robottelo

2023-11-06 06:09 UTC, omkarkhatavkar commented
trigger: test-robottelo

2023-11-06 08:44 UTC, vsedmik approved these changes
Looks good, thank you for the PR!

2023-11-06 09:38 UTC, omkarkhatavkar commented
trigger: test-robottelo
pod_resources_size: large

2023-11-06 10:36 UTC, vijaysawant requested changes

2023-11-06 12:05 UTC, vijaysawant commented on tests/foreman/api/test_discoveryrule.py
> +@pytest.fixture(scope="module")
To maintain consistancy through out the files, same applicable for line 33, 39
```suggestion
@pytest.fixture(scope='module')
```

2023-11-07 18:42 UTC, omkarkhatavkar commented
Hi @JacobCallahan and @vijaysawant, please review. Once confirmed, we can merge without frequent rebases. Thanks!

2023-11-07 19:09 UTC, JacobCallahan approved these changes

2023-11-07 19:09 UTC, merged