[6.15] negative test for webhook task
SatelliteQE/robottelo pull request #13049
Opened 2023-11-07 10:13 UTC by pondrejk

### Problem Statement
The "Deliver webhook..." task for the triggered hook previously succeeded even If the webhook execution failed for some reason. This will change in 6.15

### Solution
I'm adding a negative test to cover this scenario. Note that the upstream PR isn't merged yet, so prt trigger would fail atm

### Related Issues
SAT-21112

2023-11-07 18:31 UTC, jameerpathan111 requested changes

2023-11-07 18:31 UTC, jameerpathan111 commented on tests/foreman/api/test_webhook.py
> +    @pytest.mark.tier1
```suggestion
```
We don't need these markers anymore, right?

2023-11-07 18:31 UTC, jameerpathan111 commented on tests/foreman/api/test_webhook.py
> +        """Create a webhook with unreachable targete and assert the associated task
```suggestion
        """Create a webhook with unreachable target and assert the associated task
```

2023-11-07 18:31 UTC, jameerpathan111 commented on tests/foreman/api/test_webhook.py
> +        hook = entities.Webhooks(
```suggestion
        hook = target_sat.api.Webhooks(
```
Same suggestion for other occurrences of `entities`.

2023-11-08 09:05 UTC, pondrejk commented
@jameerpathan111 changes committed, thanks!

2023-11-08 19:52 UTC, Griffin-Sullivan reviewed
Where are we asserting that the task failed? Also are you able to get local results with a packit installed stream Satellite?

2023-11-09 08:25 UTC, pondrejk commented
```
pytest tests/foreman/api/test_webhook.py -k negative_event_task_failed
========================================== test session starts ===========================================
                                                      

tests/foreman/api/test_webhook.py .                                                                [100%]

2023-11-20 12:53 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/api/test_webhook.py -k  test_negative_event_task_failed

2023-11-20 20:56 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/api/test_webhook.py -k test_negative_event_task_failed

2023-11-22 11:20 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/api/test_webhook.py -k test_negative_event_task_failed

2023-11-22 12:21 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/api/test_webhook.py -k test_negative_event_task_failed

2023-11-22 12:51 UTC, pondrejk commented
@Griffin-Sullivan @jameerpathan111 the thing landed in stream, prt now passes

2023-11-23 13:07 UTC, jameerpathan111 approved these changes

2023-11-23 13:22 UTC, merged