[6.15 RFE] Prepare for SCA only deprecation
SatelliteQE/robottelo pull request #13045
Opened 2023-11-06 13:28 UTC by ColeHiggins2

6.15 Feature automation: SAT-20201

This test is verifying that that Simple Content Access endpoints are deprecated and will be required
        for all organizations in Satellite 6.16

As of now, Stream Satellite is showing Katello 4.12 instead of Satellite 6.16. Keeping in Draft state until changes are made

2023-11-08 17:39 UTC, ColeHiggins2 commented
airgun: https://github.com/SatelliteQE/airgun/pull/1026/files

2023-11-28 14:58 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/test_organization.py::test_positive_prepare_for_sca_only_deprecation
airgun: 1026

2023-11-28 15:13 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_organization.py::test_positive_prepare_for_sca_only_deprecation
airgun: 1026

2024-01-02 08:46 UTC, jyejare requested changes

2024-01-02 08:46 UTC, jyejare commented on tests/foreman/ui/test_organization.py
> +    )
Isnt this warning logged in the notification panel ? And just being silently sent into logs only ?

If yes, please verify the notification mssg as well, If not should we force DEVs to log that in notification as well ?

2024-01-15 13:41 UTC, closed without merging