add automation coverage for BZ 2161993
SatelliteQE/robottelo pull request #13266
Opened 2023-12-05 11:27 UTC by vijaysawant

### Problem Statement
Add automation coverage around the [Bug 2161993](https://bugzilla.redhat.com/show_bug.cgi?id=2161993) - wrong metadata if uploaded rpm have different name than name in rpm

### Solution
1. Create product, custom repo and upload rpm into repo
2. Create CV, add repo into it & publish CV
3. Register host with satellite and install rpm on it

### Related Issues
No

2023-12-05 12:55 UTC, vsedmik reviewed
Does it make sense to have `tests/foreman/data/ant-7.7.7-1.noarch.rpm` already renamed?

2023-12-05 14:49 UTC, vijaysawant commented
> Does it make sense to have `tests/foreman/data/ant-7.7.7-1.noarch.rpm` already renamed?

`ant-7.7.7-1.noarch.rpm` this is the name of rpm file present at http://infra-podman-01.infra.sat.rdu2.redhat.com:50123/fake_yum3/

2023-12-05 15:24 UTC, vijaysawant commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_repository.py -k test_possitive_install_uploaded_rpm_on_host

2023-12-07 11:33 UTC, vsedmik commented
> > Does it make sense to have `tests/foreman/data/ant-7.7.7-1.noarch.rpm` already renamed?
> 
> `ant-7.7.7-1.noarch.rpm` this is the name of rpm file present

I thought have it renamed within this PR to something else already, so that we don't rename it in the code. Instead of `tests/foreman/data/ant-7.7.7-1.noarch.rpm` you would be pushing `tests/foreman/data/noname-animal.noarch.rpm` or whatever you like.

2023-12-07 16:53 UTC, ogajduse requested changes

2023-12-07 17:02 UTC, ogajduse commented
> > > Does it make sense to have `tests/foreman/data/ant-7.7.7-1.noarch.rpm` already renamed?
> > 
> > 
> > `ant-7.7.7-1.noarch.rpm` this is the name of rpm file present
> 
> I thought have it renamed within this PR to something else already, so that we don't rename it in the code. Instead of `tests/foreman/data/ant-7.7.7-1.noarch.rpm` you would be pushing `tests/foreman/data/noname-animal.noarch.rpm` or whatever you like.

I got your point, Vladimir. I like the way it is implemented now, the package (file name) still preserves the contextual info about what package it is. We could rename it to something like `our-renamed-ant-7.7.7-1.noarch.rpm`, however, I find an advantage in using the `genstring` function since it brings randomness to the name = more combinations tested across multiple test runs.

I do not have a strong opinion on this, however.

2023-12-08 10:00 UTC, ogajduse commented on tests/foreman/cli/test_repository.py
> +    target_sat, rhel7_contenthost, function_org, function_lce
Could you look around if we can fit the test logic in an existing test? This is completely non-blocking, especially if we save time using container hosts.

2023-12-08 10:07 UTC, ogajduse commented on tests/foreman/cli/test_repository.py
> +    target_sat, rhel7_contenthost, function_org, function_lce
After a short research of our tests directory, I did not find any suitable test to put the logic in.

2023-12-11 09:53 UTC, vijaysawant commented on tests/foreman/cli/test_repository.py
> +        f'rpm -qa {FAKE_3_YUM_REPO_RPMS[0].split("-")[0]}'
`rpm -qa` gives list of installed packages, but we can use `rpm -q` which will give information, thanks for correction.

2023-12-11 12:06 UTC, vijaysawant commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_repository.py -k test_possitive_install_uploaded_rpm_on_host

2023-12-11 13:34 UTC, vijaysawant commented on tests/foreman/cli/test_repository.py
> +    FAKE_3_YUM_REPO_RPMS[0].split('.')
done, resolving conversation

2023-12-11 13:34 UTC, vijaysawant commented on tests/foreman/cli/test_repository.py
> +        3. Register host with satellite and install rpm on it
done, resolving conversation

2023-12-12 08:29 UTC, vijaysawant commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_repository.py -k test_possitive_install_uploaded_rpm_on_host

2023-12-12 09:34 UTC, vsedmik approved these changes

2023-12-12 10:29 UTC, adarshdubey-star commented on tests/foreman/cli/test_repository.py
> +def test_possitive_install_uploaded_rpm_on_host(
```suggestion
def test_positive_install_uploaded_rpm_on_host(
```

2023-12-12 10:33 UTC, vijaysawant commented on tests/foreman/cli/test_repository.py
> +def test_possitive_install_uploaded_rpm_on_host(
good catch, thanks you.

2023-12-12 10:36 UTC, adarshdubey-star approved these changes

2023-12-12 10:38 UTC, vijaysawant commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_repository.py -k test_positive_install_uploaded_rpm_on_host

2023-12-12 11:20 UTC, merged