Pagination modifications in new host UI>errata tab
SatelliteQE/robottelo pull request #13767
Opened 2024-01-11 23:41 UTC by damoore044

### Update Errata UI Pagination testing
- to standards for 6.15.0 with setup and ui

### Implement
- use of registered host fixture, setup w/ global registrations, subscribed to content.
- method to publish and promote cv, wait for any task(s).
- migrate ui view; from `legacy contenthost UI > errata tab` ,
   to `new host UI > content > errata tab` .

### Affected tests and PRT case:
Two impacted tests, 
- `test_host_content_errata_tab_pagination` renamed to `test_host_content_errata_tab_pagination`
- `test_end_to_end`  by modifying fixture `registered_contenthost`
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination or test_end_to_end'
```

### Airgun Issue
When pagination is accessed from airgun via a method like this, I get a result with no entries, even with errata present in UI and expected table found. Trying access pagination from PF4Pagination here: [views/host_new.py@362](https://github.com/SatelliteQE/airgun/blob/06ea1937089659ad1e27007f73b18cd297c6bf88/airgun/views/host_new.py#L362C7-L362C7)

``` 
def get_errata_pagination(self, entity_name):
    view = self.navigate_to(self, 'NewDetails', entity_name=entity_name)
    view.wait_displayed()
    view.content.errata.wait_displayed()
    return view.read(widget_names="content.errata.pagination")
    
def test_host_content_errata_tab_pagination()
 ...
   with session:
        # Go to new host's page UI, Errata tab,
        # read the page's pagination widgets
        session.organization.select(org_name=org.name)
        session.location.select(loc_name=DEFAULT_LOC)
        page_values = session.host_new.get_errata_pagination(
            registered_contenthost.hostname
        )
        pagination = page_values['content']['errata']['pagination']
        breakpoint()

>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>
(Pdb) : page_values
> {'content': {'errata': {'pagination': {}}}}
(Pdb) : pagination
> {}
```

2024-01-12 17:36 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination or test_end_to_end'
airgun: 1152

2024-01-18 12:11 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination'
airgun: 1152

2024-01-18 18:08 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination'
airgun: 1152

2024-01-18 23:12 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination'
airgun: 1152

2024-01-19 07:43 UTC, vijaysawant commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination'
airgun: 1152

2024-01-19 13:40 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination'
airgun: 1152

2024-01-22 17:25 UTC, vsedmik commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination'
airgun: 1152

2024-01-23 18:20 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination'
airgun: 1152

2024-01-24 16:28 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination'
airgun: 1152

2024-01-24 18:47 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination'
airgun: 1152

2024-01-24 22:01 UTC, JacobCallahan requested changes
one minor request. well done

2024-01-25 06:56 UTC, vijaysawant requested changes
Request to remove assersion condition from test module, because it is already handled inside fixture

2024-01-25 06:56 UTC, vijaysawant commented on tests/foreman/ui/test_errata.py
> +    assert registered_contenthost.subscribed
This is not require, as subscription status already asserted inside `registered_contenthost` fixture after registration of content host.
```suggestion
```

2024-01-25 17:52 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination or test_end_to_end'
airgun: 1152

2024-01-25 19:12 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k 'test_host_content_errata_tab_pagination or test_end_to_end'
airgun: 1152

2024-01-25 20:59 UTC, JacobCallahan approved these changes

2024-01-25 20:59 UTC, merged