ensure mqtt capsule is not bypassed
SatelliteQE/robottelo pull request #13817
Opened 2024-01-17 16:20 UTC by pondrejk

### Problem Statement
With global proxy setting on, it is possible that if the mqtt capsule is not reached, the default one is used instead. In such case we wouldn't find out there is a problem. 

### Solution
This PR forces the registered through capsule for the tests using external capsule

2024-01-17 16:21 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k  test_positive_run_job_on_host_registered_to_pull_provider[rhel8]

2024-01-19 14:34 UTC, synkd approved these changes
Looks good,, suggestions are non-blocking typo corrections.

2024-01-19 14:34 UTC, synkd commented on tests/foreman/cli/test_remoteexecution.py
> +        # Make sure the job is executed by the registered-trough capsule
```suggestion
        # Make sure the job is executed by the registered-through capsule
```
Non-blocking

2024-01-19 14:34 UTC, synkd commented on tests/foreman/cli/test_remoteexecution.py
> +        # Make sure the job is executed by the registered-trough capsule
```suggestion
        # Make sure the job is executed by the registered-through capsule
```
Non-blocking

2024-01-19 14:34 UTC, synkd commented on tests/foreman/api/test_remoteexecution.py
>      # Make sure the job is executed by the registered-trough capsule
```suggestion
    # Make sure the job is executed by the registered-through capsule
```

2024-01-19 14:54 UTC, pondrejk commented
applied suggestions, note: please do squash-merge

2024-01-22 13:19 UTC, ogajduse reviewed
Shouldn't both modified tests use the `setting_update` fixture to ensure that the setting returns to its original value? That way, the environment should stay unchanged for other tests that will run after these two.
https://github.com/SatelliteQE/robottelo/blob/2b1bf9b56d4ce61dd2d042ff16148958aa2c83ee/pytest_fixtures/component/settings.py#L6-L22

2024-01-23 09:51 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_pull_provider[rhel8]

2024-01-23 11:01 UTC, ogajduse approved these changes

2024-01-23 11:26 UTC, ogajduse commented
ACK
But a fix is still needed. Fixture name is missing in the test function definition or `@pytest.mark.usefixtures("setting_update")` is not used.

2024-01-23 11:57 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_pull_provider[rhel8]

2024-01-23 12:57 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_pull_provider[rhel8-remote_execution_global_proxy=False]

2024-01-26 13:31 UTC, rplevka approved these changes

2024-01-26 13:40 UTC, rplevka requested changes

2024-01-26 13:40 UTC, rplevka commented on tests/foreman/api/test_remoteexecution.py
> +@pytest.mark.parametrize('setting_update', ['remote_execution_global_proxy=False'], indirect=True)
with unchanged parameter name, pytest has issues with `=False` in the test name (see your recent PRT job).
I'd suggest calling the parameter `no-rex-global-proxy` or so.
you can do it by passing another parameter, called `ids`
[relevant docs](https://docs.pytest.org/en/7.1.x/example/parametrize.html#different-options-for-test-ids)

2024-01-30 09:26 UTC, pondrejk commented
trigger: test-robottelo
pytest: test_positive_run_job_on_host_registered_to_pull_provider[rhel8-no_global_proxy]

2024-01-30 09:47 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k test_positive_run_job_on_host_registered_to_pull_provider[rhel9-no_global_proxy]

2024-01-30 10:39 UTC, rplevka approved these changes

2024-01-30 10:39 UTC, merged