Add host teardown for smart classparameters test
SatelliteQE/robottelo pull request #13902
Opened 2024-01-25 08:19 UTC by shubhamsg199

### Problem Statement
test_positive_test_hidden_parameter_value is failing due to no teardown present for the host in test_positive_list

### Solution
Add teardown for the host deletion

2024-01-25 11:21 UTC, Gauravtalreja1 approved these changes
ACK for the teardown change, @shubhamsg199 could you update commit message/PR title to some meaningful message, and run PRT here please?

2024-01-26 10:45 UTC, lhellebr approved these changes
Have you considered making a host a fixture instead?

2024-01-26 18:02 UTC, ColeHiggins2 approved these changes

2024-01-27 12:41 UTC, rplevka requested changes
Thanks for fixing the test!
I agree with @lhellebr here.
Let's follow the practice of separating the environment setup from the test itself by moving the host creation to a fixture.
It seems pretty straightforward and should not take too much effort.

2024-01-29 07:12 UTC, shubhamsg199 commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_classparameters.py

2024-01-29 11:01 UTC, shubhamsg199 commented
> Thanks for fixing the test! I agree with @lhellebr here. Let's follow the practice of separating the environment setup from the test itself by moving the host creation to a fixture. It seems pretty straightforward and should not take too much effort.

@rplevka The host creation here is  just used by one test so I would rather keep it as is and can add the fixture if needed in future

2024-01-29 12:55 UTC, Gauravtalreja1 approved these changes
ACK, Moving host setup and teardown to separate fixture isn't required atm I feel

2024-01-29 12:56 UTC, merged