Fix useless asserts in installer tests
SatelliteQE/robottelo pull request #14099
Opened 2024-02-16 14:37 UTC by rmynar

Fixing assertions that were always True and therefore useless.

Note: `bool("any string with non-zero length")` is True, `True or False` is True

2024-02-16 14:39 UTC, rmynar commented
trigger: test-robottelo
pytest: tests/foreman/ -k 'test_installer_sat_pub_directory_accessibility or test_installer_cap_pub_directory_accessibility'

2024-02-16 15:58 UTC, ogajduse commented
Good catch @rmynar! I have prepared a patch that adds flake8-simplify and flake8-return rulesets to our ruff linter config some time ago and seeing your patch made me publish it today. #14100 

Let's merge yours first and I will rebase mine.

2024-02-16 15:58 UTC, ogajduse approved these changes

2024-02-16 15:58 UTC, ogajduse commented
@rmynar Can you please take a look at the PRT failures?

2024-02-16 17:18 UTC, rmynar commented
trigger: test-robottelo
pytest: tests/foreman/ -k "test_installer_sat_pub_directory_accessibility or test_installer_cap_pub_directory_accessibility"

2024-02-16 18:58 UTC, JacobCallahan requested changes
Some minor recommendations

2024-02-16 18:58 UTC, JacobCallahan commented on tests/foreman/destructive/test_installer.py
> +        assert 'HTTP/1.1 200 OK' in accessibility_check or 'HTTP/2 200 ' in accessibility_check
If you're just checking for specific substrings, you likely don't need to bother splitting the output into a list.
```suggestion
        accessibility_check = target_sat.execute(command).stdout
        assert 'HTTP/1.1 200 OK' in accessibility_check or 'HTTP/2 200 ' in accessibility_check
```

2024-02-16 18:58 UTC, JacobCallahan commented on tests/foreman/destructive/test_installer.py
> +        assert 'HTTP/2 200 ' not in accessibility_check
Same recommendation here
```suggestion
        accessibility_check = target_sat.execute(command).stdout
        assert 'HTTP/1.1 200 OK' not in accessibility_check
        assert 'HTTP/2 200 ' not in accessibility_check
```

2024-02-16 18:58 UTC, JacobCallahan commented on tests/foreman/installer/test_installer.py
> +        assert 'HTTP/1.1 200 OK' in accessibility_check or 'HTTP/2 200 ' in accessibility_check
You get the idea
```suggestion
        accessibility_check = capsule_configured.execute(command).stdout
        assert 'HTTP/1.1 200 OK' in accessibility_check or 'HTTP/2 200 ' in accessibility_check
```

2024-02-16 18:58 UTC, JacobCallahan commented on tests/foreman/installer/test_installer.py
> +        assert 'HTTP/2 200 ' not in accessibility_check
Same
```suggestion
        accessibility_check = capsule_configured.execute(command).stdout
        assert 'HTTP/1.1 200 OK' not in accessibility_check
        assert 'HTTP/2 200 ' not in accessibility_check
```

2024-02-16 22:41 UTC, ogajduse commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_installer.py::test_installer_sat_pub_directory_accessibility tests/foreman/installer/test_installer.py::test_installer_cap_pub_directory_accessibility

2024-02-16 23:30 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 5780
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_installer.py::test_installer_sat_pub_directory_accessibility tests/foreman/installer/test_installer.py::test_installer_cap_pub_directory_accessibility
Test Result : ================= 2 passed, 114 warnings in 2647.34s (0:44:07) =================
```

2024-02-19 14:00 UTC, lhellebr approved these changes
I agree with Jacob, otherwise LGTM

2024-02-19 14:21 UTC, rmynar commented
I just wanted to fix the logical error in assertion, but you're right that the split was useless. Hopefully it looks better now

2024-02-19 16:47 UTC, merged