validate that cv warning to force promote
SatelliteQE/robottelo pull request #14316
Opened 2024-03-08 11:58 UTC by vijaysawant

### Problem Statement
CU Case - Test cv promote shows warning of 'force promotion' for out of sequence LCE
BZ 2125728

### Solution
Added automation coverage

### Related Issues
NA

2024-03-08 14:47 UTC, vsedmik requested changes
One small change plus there would be some other proposal for change, which would be better discussed live at meet.

2024-03-08 14:47 UTC, vsedmik commented on tests/foreman/cli/test_contentview.py
> +        :BZ: 2125728
```suggestion
        :BZ: 2125728
        
        :customerscenario: true
```

2024-03-12 16:06 UTC, lhellebr commented on tests/foreman/cli/test_contentview.py
> +        # 1. Create an environment path ex- Library >> Test >> Preprod >> Prod
Should all this entity creation be turned into a fixture?

2024-03-12 16:07 UTC, lhellebr approved these changes

2024-03-12 16:10 UTC, lhellebr commented
What Vladimir is suggesting sounds like a very good test proposal but I'd leave it up to you if it is or is not out of scope of this PR.

But more importantly, I doubt this should be marked with the `:BZ:` in docstring. Because I think this tests something else than what the BZ is about. Its title is: `Content view Promote always warns for 'Force promotion' even if correct path is followed. `

2024-03-15 14:01 UTC, vsedmik approved these changes
Just a few nitpicks, non-blocking.

2024-03-15 14:06 UTC, sambible approved these changes
PRT and lgtm

2024-03-15 16:59 UTC, damoore044 approved these changes
nice work! pending @vsedmik 's comments on docstrings

2024-03-15 18:48 UTC, ColeHiggins2 approved these changes

2024-03-18 11:52 UTC, vijaysawant commented on tests/foreman/cli/test_contentview.py
> +        # Promote version 1.0 to Preprod, skip Library, this should fail with warning
Can you please update comment with 'suggest changes' so I can commit it directly, (I am away from keyb)

2024-03-18 11:56 UTC, vsedmik commented on tests/foreman/cli/test_contentview.py
> +        # Promote version 1.0 to Preprod, skip Library, this should fail with warning
```suggestion
        # Promote version 1.0 to Preprod, skip Test, this should fail with warning
```

2024-03-18 13:51 UTC, vsedmik commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_contentview.py -k validate_force_promote_warning

2024-03-18 14:32 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6105
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_contentview.py -k validate_force_promote_warning --external-logging
Test Result : ========== 1 passed, 131 deselected, 1 warning in 1149.81s (0:19:09) ===========
```

2024-03-18 14:35 UTC, merged