CC Automation/Comp Eval coverage
SatelliteQE/robottelo pull request #14451
Opened 2024-03-19 17:50 UTC by sambible

CC Automation/Comp Eval for CV work for BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2153523

2024-03-19 17:52 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py -k 'test_ccv_promote_registry_name_change'

2024-03-21 11:50 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6154
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_contentview.py -k test_ccv_promote_registry_name_change --external-logging
Test Result : ================= 87 deselected, 1 error in 786.88s (0:13:06) ==================
```

2024-04-03 13:58 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6287
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_contentview.py -k test_ccv_promote_registry_name_change --external-logging
Test Result : =========== 87 deselected, 3 warnings, 1 error in 705.16s (0:11:45) ============
```

2024-04-08 15:43 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py -k 'test_ccv_promote_registry_name_change'

2024-04-08 16:04 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6360
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_contentview.py -k test_ccv_promote_registry_name_change --external-logging
Test Result : =========== 87 deselected, 3 warnings, 1 error in 784.75s (0:13:04) ============
```

2024-04-08 16:06 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py -k 'test_ccv_promote_registry_name_change'

2024-04-08 16:25 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6363
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_contentview.py -k test_ccv_promote_registry_name_change --external-logging
Test Result : =========== 1 passed, 87 deselected, 4 warnings in 854.96s (0:14:14) ===========
```

2024-04-11 15:55 UTC, damoore044 approved these changes
ack nice work !

2024-04-16 08:35 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py -k 'test_ccv_promote_registry_name_change'

2024-04-16 08:54 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 76
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_contentview.py -k test_ccv_promote_registry_name_change --external-logging
Test Result : ========== 1 passed, 88 deselected, 97 warnings in 771.90s (0:12:51) ===========
```

2024-04-30 11:53 UTC, vsedmik approved these changes
Looks nice. @sambible could you rebase, resolve the conflict and push once again?

2024-04-30 11:53 UTC, vsedmik commented on tests/foreman/api/test_contentview.py
> +        assert version.promote(data={'environment_ids': lce2.id})
non-blocking
```suggestion
        assert 'success' in version.promote(data={'environment_ids': lce1.id})['result']
        assert 'success' in version.promote(data={'environment_ids': lce2.id})['result']
```

2024-04-30 12:01 UTC, vijaysawant requested changes
please look over steps.

2024-04-30 12:01 UTC, vijaysawant commented on tests/foreman/api/test_contentview.py
> +            3) Create a CCV and add the CV to it, then publish it
should be content view version
```suggestion
            3) Create a CCV and add the CV version to it, then publish it
```

2024-04-30 18:27 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py -k 'test_ccv_promote_registry_name_change'

2024-04-30 18:50 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6753
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_contentview.py -k test_ccv_promote_registry_name_change --external-logging
Test Result : ========== 1 passed, 88 deselected, 97 warnings in 804.24s (0:13:24) ===========
```

2024-04-30 19:57 UTC, vsedmik approved these changes
ACK

2024-04-30 19:58 UTC, merged