Assert commands results. Remove CA download, machines already have it. Do not install a library through pip.
SatelliteQE/robottelo pull request #14511
Opened 2024-03-25 13:34 UTC by lhellebr

2024-03-25 13:35 UTC, lhellebr commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout

2024-03-25 16:26 UTC, lhellebr commented
Test's setup passed and it failed later. Doesn't seem like this PR's fault. I tested on 6.15 without issues, I'll test on stream and comment the results.

2024-03-25 16:37 UTC, lhellebr commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout

2024-03-25 17:35 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6190
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout --external-logging
Test Result : ================== 1 failed, 1 warning in 2986.14s (0:49:46) ===================
```

2024-03-26 12:25 UTC, lhellebr commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout

2024-03-26 13:21 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6204
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout --external-logging
Test Result : ================== 1 failed, 1 warning in 2988.45s (0:49:48) ===================
```

2024-03-26 15:31 UTC, lhellebr commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout

2024-03-26 16:25 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6212
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout --external-logging
Test Result : ================== 1 passed, 1 warning in 2945.55s (0:49:05) ===================
```

2024-03-27 10:27 UTC, pondrejk approved these changes

2024-04-02 15:01 UTC, lhellebr commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout

2024-04-02 15:49 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6268
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout --external-logging
Test Result : ================== 1 passed, 4 warnings in 2602.95s (0:43:22) ==================
```

2024-04-03 12:57 UTC, lhellebr commented
@SatelliteQE/airgun-tier-1-reviewers

2024-04-05 14:57 UTC, lhellebr commented
@SatelliteQE/robottelo-tier-2-reviewers

2024-04-08 08:37 UTC, shweta83 requested changes

2024-04-08 08:37 UTC, shweta83 commented on pytest_fixtures/component/satellite_auth.py
>      if is_open('BZ:2113905'):
This condition can be removed as this BZ is verfied and closed now.

2024-04-23 08:59 UTC, lhellebr commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout

2024-04-23 09:33 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6646
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout --external-logging
Test Result : ================== 12 warnings, 1 error in 1561.60s (0:26:01) ==================
```

2024-04-26 13:22 UTC, lhellebr commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout

2024-04-26 13:28 UTC, lhellebr commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout

2024-04-26 13:29 UTC, lhellebr commented
BZ has been converted to docs, lxml package now should be installed manually according to docs. Updating accordingly.

2024-04-26 14:11 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6711
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/destructive/test_ldap_authentication.py::test_session_expire_rhsso_idle_timeout --external-logging
Test Result : ================= 1 passed, 17 warnings in 2393.81s (0:39:53) ==================
```

2024-04-26 15:47 UTC, ogajduse approved these changes

2024-04-26 15:47 UTC, ogajduse commented
PRT is passing, and Shweta's comment was addressed. Merging.

2024-04-26 15:48 UTC, merged