[RFE] Should not be able to publish the content-view, while repository sync in-progress
SatelliteQE/robottelo pull request #14677
Opened 2024-04-08 16:40 UTC by damoore044

### Reason
API Automation coverage for [RFE] SAT-2927 and BZ# 1957144
Target Milestone is 6.15.0, no CP to 6.14.z

### Steps
- Add repository to content-view
- Perform asynchronous repository sync
- Attempt to publish a version of the content-view, while repo sync ongoing.
- Raised HTTP exception, publish task failed, repo sync `task_id` found in humanized error message.

### PRT Trigger
```
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync
```

2024-04-08 16:40 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync

2024-04-08 17:00 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync

2024-04-08 17:04 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync

2024-04-08 17:32 UTC, devendra104 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync

2024-04-08 17:54 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6370
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync --external-logging
Test Result : ================== 1 passed, 4 warnings in 755.51s (0:12:35) ===================
```

2024-04-10 11:20 UTC, vijaysawant requested changes
Can we please add test `:steps:` along with these 3 testimony tokens ?
`:customerscenario:`
`:BZ:`
`:CaseAutomation:`

2024-04-10 11:20 UTC, vijaysawant commented on tests/foreman/api/test_contentview.py
> +
```suggestion

    :steps:
        1. Add repository to content-view
        2. Perform asynchronous repository sync
        3. Attempt to publish a version of the content-view, while repo sync ongoing.
        4. Assert: Raised HTTP exception, publish task failed, repo sync task_id found in humanized error, CV versions unchanged.

```

2024-04-10 18:58 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync

2024-04-10 19:18 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6433
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync --external-logging
Test Result : ================== 1 passed, 10 warnings in 663.91s (0:11:03) ==================
```

2024-04-11 07:15 UTC, vijaysawant approved these changes
Ack :+1: 

Optional - @damoore044 Do you thing rest of 3 testimony tokens are also require to add?
`:customerscenario:`
`:BZ:`
`:CaseAutomation:`

2024-04-11 13:38 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync

2024-04-11 13:58 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 6455
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync --external-logging
Test Result : ================== 1 passed, 10 warnings in 708.89s (0:11:48) ==================
```

2024-04-11 14:30 UTC, ColeHiggins2 approved these changes

2024-04-11 14:30 UTC, merged