test syncplan creation with custom timezone
SatelliteQE/robottelo pull request #15120
Opened 2024-05-21 12:23 UTC by pondrejk

### Problem Statement
Customer scenario coverage for bz#2015344

### Solution
Check if non UTC datetime is processed correctly by hammer

### Related Issues

2024-05-21 12:24 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py -k  timezone

2024-05-21 13:40 UTC, vsedmik requested changes
Small change request and a question.

2024-05-21 15:20 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_syncplan.py -k timezone

2024-05-21 16:57 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7040
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_syncplan.py -k timezone --external-logging
Test Result : ========== 1 passed, 85 deselected, 94 warnings in 643.59s (0:10:43) ===========
```

2024-05-22 09:33 UTC, vsedmik approved these changes

2024-05-22 14:00 UTC, synkd approved these changes

2024-05-23 07:08 UTC, merged

2024-06-18 08:40 UTC, dosas commented on tests/foreman/cli/test_syncplan.py
> +    expected_date = future_date + timedelta(hours=4)
@vsedmik @pondrejk This will work with(out) daylight savings time, here the difference will be 5 hours.

2024-06-18 08:54 UTC, vsedmik commented on tests/foreman/cli/test_syncplan.py
> +    expected_date = future_date + timedelta(hours=4)
There is DST used in both timezones, but you are right there are small differences _when_ the DST is applied in EU vs US.

2024-06-18 08:57 UTC, dosas commented on tests/foreman/cli/test_syncplan.py
> +    expected_date = future_date + timedelta(hours=4)
I do not understand your point. Yes, DST is used in the timezones but the expected diff is fixed to 4 hours. So at some point the diff will be 5 hours?

2024-06-18 09:10 UTC, vsedmik commented on tests/foreman/cli/test_syncplan.py
> +    expected_date = future_date + timedelta(hours=4)
Yes, and then it jumps back to 4 once the other timezone applies the DST too. I think there is one week diff when the DST is applied.

2024-06-20 13:18 UTC, dosas commented
@pondrejk Looking at this [comment](https://github.com/theforeman/hammer-cli/pull/369#issuecomment-2180564378) I am pretty sure that this test is working by coincidence (probably the default timezone on the CI servers?). Because `CEST` is not a valid timezone that can be parsed by hammer-cli. It should be something like `+04:00`