test timeout_to_kill
SatelliteQE/robottelo pull request #15162
Opened 2024-05-23 15:02 UTC by pondrejk

### Problem Statement
timeout to kill setting should cancel the rex job if it takes too long

### Solution
adding test 

### Related Issues

2024-05-23 15:06 UTC, pondrejk commented
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout
theforeman:
    smart_proxy_remote_execution_ssh: 115
```

2024-05-23 16:17 UTC, vsedmik approved these changes
Codewisely looks good, packit/PRT pending.

2024-05-23 18:43 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7096
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 2178.44s (0:36:18) ==========
```

2024-05-27 07:36 UTC, vsedmik requested changes

2024-05-27 07:36 UTC, vsedmik commented on tests/foreman/cli/test_remoteexecution.py
> +                'timeout_to_kill': '5',
Per PRT failure I guess this could help
```suggestion
                'timeout-to-kill': '5',
```

2024-05-27 07:45 UTC, pondrejk commented
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout
theforeman:
    smart_proxy_remote_execution_ssh: 115
```

2024-05-28 08:30 UTC, pondrejk commented
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout
theforeman:
    smart_proxy_remote_execution_ssh: 115
```

2024-05-28 12:36 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7131
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 59 deselected, 67 warnings, 1 error in 1719.57s (0:28:39) ===========
```

2024-05-29 08:00 UTC, pondrejk commented
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout
theforeman:
    smart_proxy_remote_execution_ssh: 115
```

2024-05-29 08:42 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7156
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 2155.09s (0:35:55) ==========
```

2024-05-30 08:58 UTC, pondrejk commented
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout
theforeman:
    smart_proxy_remote_execution_ssh: 115
```

2024-05-30 09:43 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7196
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 2225.42s (0:37:05) ==========
```

2024-06-03 07:35 UTC, pondrejk commented
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout
theforeman:
    smart_proxy_remote_execution_ssh: 115
```

2024-06-03 08:20 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7245
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 2239.36s (0:37:19) ==========
```

2024-06-04 15:09 UTC, lhellebr approved these changes

2024-06-11 08:32 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

2024-06-11 12:41 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

2024-06-11 13:00 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7356
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : =========== 59 deselected, 72 warnings, 1 error in 861.66s (0:14:21) ===========
```

2024-06-11 13:04 UTC, pondrejk commented
eh, prt won't pass due to the current registration issue, must await sn 62

2024-06-17 08:17 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

2024-06-17 08:44 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7401
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 1040.12s (0:17:20) ==========
```

2024-07-03 17:36 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

2024-07-03 18:03 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7636
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 1273.61s (0:21:13) ==========
```

2024-07-08 12:10 UTC, pondrejk commented
hm, awaiting rubygem-smart_proxy_remote_execution_ssh-0.10.6 to land at stream, having the proper fix to the original issue, stay tuned

2024-07-22 07:33 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

2024-07-22 08:01 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7804
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 1095.80s (0:18:15) ==========
```

2024-07-22 14:33 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7808
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 942.15s (0:15:42) ===========
```

2024-07-24 09:40 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

2024-07-24 10:05 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7832
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 failed, 59 deselected, 72 warnings in 928.00s (0:15:27) ===========
```

2024-07-24 11:54 UTC, pnovotny commented on tests/foreman/cli/test_remoteexecution.py
> +        command = r'for i in \`seq 160\`; do sleep \$i; done'
(non-blocking for the test functionality)
With `sleep $i`, the sleeps will be incremental, i.e. sleep 1; sleep 2; sleep 3, etc. 
For sleeping for 160 seconds in 1-second ticks, running `for run in {1..160}; do sleep 1; done` will do the trick.

2024-07-24 11:55 UTC, pnovotny approved these changes
LGTM. My comment above is non-blocking.

2024-08-01 11:23 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_remoteexecution.py -k timeout

2024-08-01 11:48 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7936
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_remoteexecution.py -k timeout --external-logging
Test Result : ========== 1 passed, 59 deselected, 72 warnings in 964.38s (0:16:04) ===========
```

2024-08-01 11:58 UTC, merged