[Reporting] Updating reporting tests to be sca compliant
SatelliteQE/robottelo pull request #15166
Opened 2024-05-23 21:12 UTC by ColeHiggins2

SCA is now the default in 6.16. This PR is for updating all tests under the Reporting Component
SAT-24355

2024-05-28 08:09 UTC, vsedmik requested changes
Looks good, just one suggestion for improvement.
Could you run PRT for some test using the `setup_content` fixture? The `test_positive_generate_job_report` could be a good candidate.

2024-05-28 08:09 UTC, vsedmik commented on tests/foreman/api/test_reporttemplates.py
> +    )
Let's use sets to check if all hosts were reported. 
```suggestion
    assert {i.Host for i in res} == {i.hostname for i in content_hosts}
```

2024-06-04 14:19 UTC, ColeHiggins2 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py::test_positive_generate_job_report

2024-06-04 15:23 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7278
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_reporttemplates.py::test_positive_generate_job_report --external-logging
Test Result : ================ 6 passed, 1060 warnings in 3358.02s (0:55:58) =================
```

2024-06-05 08:21 UTC, merged