[CC Automation] Add test covering interaction between File screen and published Content Views
SatelliteQE/robottelo pull request #15414
Opened 2024-06-14 15:28 UTC by sambible

### Problem Statement
Automation for this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2026701
Requires airgun PR https://github.com/SatelliteQE/airgun/pull/1426

### Related Issues
This area of Robottelo actually has no tests, so in a separate PR I'm going to raise at least 1 or 2 small tests for the other functionality in this area, just to get some coverage. 

trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k 'test_file_cv_display'
airgun: 1426

2024-06-17 07:25 UTC, LadislavVasina1 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k 'test_file_cv_display'
airgun: 1426

2024-06-17 07:34 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7400
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_contentview.py -k test_file_cv_display --external-logging
Test Result : ============ 3 deselected, 9 warnings, 1 error in 198.70s (0:03:18) ============
```

2024-06-17 16:22 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7412
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_contentview.py -k test_file_cv_display --external-logging
Test Result : =========== 1 passed, 3 deselected, 14 warnings in 662.09s (0:11:02) ===========
```

2024-06-18 07:27 UTC, vijaysawant requested changes
- Trying to correct sentances (I might be wrong) from test doc string > steps & expected results
- Suggestion to use `Verifies` field
- Suggestion to use single quotes for strings using inside test module to make it consistent.

2024-06-18 07:27 UTC, vijaysawant commented on tests/foreman/ui/test_contentview.py
> +        1. Create a File Repo, and publish content to it
```suggestion
        1. Create a file repo, and upload content into it
```

2024-06-18 07:27 UTC, vijaysawant commented on tests/foreman/ui/test_contentview.py
> +        2. Add it to a CV, and publish that CV
```suggestion
        2. Add file repo to a CV, and publish it
```

2024-06-18 07:27 UTC, vijaysawant commented on tests/foreman/ui/test_contentview.py
> +        3. Create a seperate CV, and publish it as well.
```suggestion
        3. Create another CV, and publish it
```

2024-06-18 07:27 UTC, vijaysawant commented on tests/foreman/ui/test_contentview.py
> +    :expectedresults: The CV containing the file repo is displayed, and no other CVs.
```suggestion
    :expectedresults: Only the Content View with the file repo is displayed.
```

2024-06-18 07:27 UTC, vijaysawant commented on tests/foreman/ui/test_contentview.py
> +    :customerscenario: true
Can we add Verifies field as well?
```suggestion
    :customerscenario: true
    
    :Verifies: SAT-17081
```

Make sure the Jira id `SAT-17081` is correct  :smile_cat:

2024-06-18 07:27 UTC, vijaysawant commented on tests/foreman/ui/test_contentview.py
> +    cv = target_sat.api.ContentView(id=cv.id, repository=[file_repo]).update(["repository"])
```suggestion
    cv = target_sat.api.ContentView(id=cv.id, repository=[file_repo]).update(['repository'])
```

2024-06-19 06:29 UTC, vijaysawant approved these changes
Thank you for work, looks good to me.
Pending PRT result.

2024-06-19 06:29 UTC, vijaysawant commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k 'test_file_cv_display'
airgun: 1426

2024-06-19 06:48 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7440
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_contentview.py -k test_file_cv_display --external-logging
Test Result : =========== 1 passed, 3 deselected, 14 warnings in 681.55s (0:11:21) ===========
```

2024-06-19 09:58 UTC, vsedmik approved these changes

2024-06-21 16:53 UTC, damoore044 approved these changes

2024-06-21 16:53 UTC, merged