Updates for upgrades component eval
SatelliteQE/robottelo pull request #15415
Opened 2024-06-14 15:37 UTC by vsedmik

### Problem Statement
During component eval some changes were proposed by PX/SD/QE for upgrade tests (scenario and all-tiers).

### Solution
This PR just implements a few of them, mostly related to @SatelliteQE/phoenix 
For reference check the _Component feedback sheet - Team Platform_ g-sheet

Split into a bunch of tiny commits, one per each g-sheet line 

### PRT test Cases example
trigger: test-robottelo
pytest: tests/foreman/cli/test_activationkey.py -k test_positive_update_aks_to_chost

2024-06-14 15:37 UTC, vsedmik commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_activationkey.py -k test_positive_update_aks_to_chost

2024-06-14 15:58 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7396
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_activationkey.py -k test_positive_update_aks_to_chost --external-logging
Test Result : ========= 3 failed, 145 deselected, 176 warnings in 711.54s (0:11:51) ==========
```

2024-06-14 18:24 UTC, vsedmik commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_activationkey.py -k test_positive_update_aks_to_chost

2024-06-14 18:44 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7398
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_activationkey.py -k test_positive_update_aks_to_chost --external-logging
Test Result : ========= 3 passed, 145 deselected, 178 warnings in 760.60s (0:12:40) ==========
```

2024-06-18 09:32 UTC, jameerpathan111 requested changes

2024-06-18 09:32 UTC, jameerpathan111 commented on tests/foreman/cli/test_activationkey.py
> +def test_positive_update_aks_to_chost(module_org, module_location, rhel_contenthost, target_sat):
```suggestion
def test_positive_update_aks_to_chost(module_org, module_location, rhel_contenthost, module_target_sat):
```
To be consistent, I'd suggest using `module_target_sat` in the test.

2024-06-18 09:32 UTC, jameerpathan111 commented on tests/foreman/cli/test_contentaccess.py
> +def test_positive_rct_shows_sca_enabled(module_sca_manifest, target_sat):
```suggestion
def test_positive_rct_shows_sca_enabled(module_sca_manifest, module_target_sat):
```

2024-06-19 07:49 UTC, vsedmik commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_activationkey.py -k test_positive_update_aks_to_chost

2024-06-19 08:11 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7441
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_activationkey.py -k test_positive_update_aks_to_chost --external-logging
Test Result : ========= 3 passed, 145 deselected, 177 warnings in 797.63s (0:13:17) ==========
```

2024-06-20 15:00 UTC, jameerpathan111 approved these changes

2024-06-24 13:39 UTC, pondrejk approved these changes

2024-06-26 14:53 UTC, sambible approved these changes

2024-06-26 14:53 UTC, merged