Add pytest option to randomly select and run number/percentage of tests from the collection.
SatelliteQE/robottelo pull request #15450
Opened 2024-06-18 14:32 UTC by jameerpathan111

### Problem Statement
- The Automation team requested to add support for pytest option to randomly select and run number/percentage of tests from the collection.

### Solution
- Add pytest option `--select-random-tests`: Number/Percentage of tests to randomly select and run from selected test collection.

### Examples
- pytest tests/foreman/ --select-random-tests '5%'
- pytest tests/foreman/ --select-random-tests 4

### Related Issues
- See SAT-20829

2024-06-18 14:41 UTC, jameerpathan111 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/ --select-random-tests 2
```

2024-06-18 14:59 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7429
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/ --select-random-tests 2 --external-logging
Test Result : ======== 2 passed, 2305 deselected, 2336 warnings in 661.87s (0:11:01) =========
```

2024-06-18 15:45 UTC, jameerpathan111 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_location.py --select-random-tests '10%' --component OrganizationsandLocations
```

2024-06-18 16:02 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7431
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_location.py --select-random-tests 10% --component OrganizationsandLocations --external-logging
Test Result : ========== 4 passed, 29 deselected, 65 warnings in 623.06s (0:10:23) ===========
```

2024-06-19 19:26 UTC, JacobCallahan requested changes
Can you generate a random seed that would be logged before use? Also, adding the option to pass a specific seed would allow us to repeat a random test selection.

2024-06-20 09:09 UTC, jameerpathan111 commented
> Can you generate a random seed that would be logged before use? Also, adding the option to pass a specific seed would allow us to repeat a random test selection.

I don't completely understand what you mean here. As per @jyejare's request he'd like user to specify the number/percentage of tests to collect. Or did you mean if no value is provided we should pick random number of tests?

2024-06-26 09:42 UTC, ogajduse reviewed
Agreed with Jake. It should be really simple to implement. With the current implementation, it should be only a matter of running `random.seed(seed)`.

```python
def random_pick(items, k, seed=None):
    if seed is not None:
        random.seed(seed)
    return random.sample(items, k) 

items = [1,2,3,4,5,6,7,8,9,10]
k = 2
seed = 42

picked_items = random_pick(items, k, seed)
print(f"Picked {k} random items (seed: {seed}):", picked_items)
# Picked 2 random items (seed: 42): [2, 1]
picked_items = random_pick(items, k, seed)
print(f"Picked {k} random items (seed: {seed}):", picked_items)
#Picked 2 random items (seed: 42): [2, 1]
picked_items = random_pick(items, k, seed)
print(f"Picked {k} random items (seed: {seed}):", picked_items)
#Picked 2 random items (seed: 42): [2, 1]
```

2024-06-26 09:59 UTC, rmynar requested changes
Agree with @JacobCallahan, there should be a way to rerun the same set of tests. There's a good tip how to implement "seed" from @ogajduse. But if you're not going to implement the seed, there should be at least a log entry that contains all the selected test, which should be easily copy&pasted.

2024-07-02 09:16 UTC, jameerpathan111 commented
> * pytest tests/foreman/ --select-random-tests 4

Ah, now I get what Jake meant. Thanks for explaining:) Implemented your suggestion.

2024-07-02 09:22 UTC, jameerpathan111 commented
```
(env-robottelo3) jpathan@jpathan-mac robottelo % pytest tests/foreman/api --select-random-tests 4 --random-tests-seed 32 --collect-only --disable-warnings
=============================================================================================================================================== test session starts ===============================================================================================================================================
collected 2316 items / 2312 deselected / 4 selected                                                                                                                                                                                                                                                               

<Dir robottelo>
  <Package tests>
    <Package foreman>
      <Package api>
        <Module test_subscription.py>
          <Function test_positive_async_endpoint_for_manifest_refresh>
        <Module test_multiple_paths.py>
          <Class TestDoubleCheck>
            <Function test_positive_post_and_get_requests[2]>
        <Module test_discoveryrule.py>
          <Function test_negative_create_with_invalid_host_limit_and_priority>
        <Module test_syncplan.py>
          <Function test_positive_update_enabled[False]>

=============================================================================================================================== 4/2316 tests collected (2312 deselected) in 15.60s ================================================================================================================================
```

```
(env-robottelo3) jpathan@jpathan-mac robottelo % pytest tests/foreman/api --select-random-tests 4 --random-tests-seed 32 --collect-only --disable-warnings
=============================================================================================================================================== test session starts ===============================================================================================================================================
collected 2316 items / 2312 deselected / 4 selected                                                                                                                                                                                                                                                               

<Dir robottelo>
  <Package tests>
    <Package foreman>
      <Package api>
        <Module test_subscription.py>
          <Function test_positive_async_endpoint_for_manifest_refresh>
        <Module test_multiple_paths.py>
          <Class TestDoubleCheck>
            <Function test_positive_post_and_get_requests[2]>
        <Module test_discoveryrule.py>
          <Function test_negative_create_with_invalid_host_limit_and_priority>
        <Module test_syncplan.py>
          <Function test_positive_update_enabled[False]>

=============================================================================================================================== 4/2316 tests collected (2312 deselected) in 15.31s ================================================================================================================================
```

2024-07-02 12:43 UTC, rmynar approved these changes
I'm not sure about Automation team needs, but current solution seems to be able to select testcases randomly and also replay the same set of tests. The replay using seed breaks as soon as test collection is modified, but I don't think this is a problem. ACK

2024-07-02 21:17 UTC, JacobCallahan approved these changes
Very nice!!

2024-07-02 21:17 UTC, merged