[CC Automation] Update API test to use refresh-all and add CLI test for bulk actions
SatelliteQE/robottelo pull request #15451
Opened 2024-06-18 18:43 UTC by sambible

### Problem Statement
Adds test coverage for: https://bugzilla.redhat.com/show_bug.cgi?id=2126420 / https://issues.redhat.com/browse/SAT-18199

### Related Issues
Also updates robottelo CLI to support `hammer alternate-content-source bulk` actions, and the API test to cover the endpoint added in https://github.com/SatelliteQE/nailgun/pull/1086

PRT test Cases example
trigger: test-robottelo
pytest: tests/foreman/api/test_acs.py -k 'test_positive_run_bulk_actions'

trigger: test-robottelo
pytest: tests/foreman/cli/test_acs.py -k 'test_bulk_actions'

2024-06-19 09:38 UTC, vsedmik requested changes
One minor thing, otherwise looks good to me :+1: 
Let's kick on PRT

2024-06-19 09:38 UTC, vsedmik commented on tests/foreman/api/test_acs.py
>          3. Bulk destroy some of them.
This should fix `make docs` in CI/CQ
```suggestion
        4. Bulk destroy some of them.
        5. Cleanup the rest.
```

2024-06-19 11:14 UTC, jyejare approved these changes
Framework changes look good

2024-06-26 12:54 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/api/test_acs.py -k 'test_positive_run_bulk_actions'

2024-06-26 13:13 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7535
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_acs.py -k test_positive_run_bulk_actions --external-logging
Test Result : =========== 1 passed, 6 deselected, 15 warnings in 707.43s (0:11:47) ===========
```

2024-06-26 14:48 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_acs.py -k 'test_bulk_actions'

2024-06-26 15:08 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7541
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_acs.py -k test_bulk_actions --external-logging
Test Result : ========== 1 passed, 13 deselected, 22 warnings in 658.79s (0:10:58) ===========
```

2024-06-27 13:57 UTC, vsedmik requested changes
Doc strings still need a fix to satisfy CI/CQ.

2024-06-28 09:10 UTC, vsedmik requested changes
Should be the last one missing

2024-06-28 09:10 UTC, vsedmik commented on robottelo/cli/acs.py
> +    bulk            Modify alternate content sources in bulk
```suggestion

    bulk            Modify alternate content sources in bulk
```

2024-06-28 09:22 UTC, vsedmik commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_acs.py -k 'test_bulk_actions'

2024-06-28 09:44 UTC, vsedmik approved these changes
All green

2024-06-28 09:46 UTC, merged