Fix container tags related failures
SatelliteQE/robottelo pull request #15598
Opened 2024-07-09 10:26 UTC by vsedmik

### Problem Statement
1. Name for container image tags was unified with API some time ago but we haven't update our tests.
2. The `container-image-tags-filter` is not printed by hammer so I'm commenting it out for now and until I figure out why.

### Solution
This PR fixes 1. and comments out checks for 2.

 ### PRT test Cases example
trigger: test-robottelo
pytest: tests/foreman/cli/test_docker.py::TestDockerRepository::test_positive_sync tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_additive tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_content_only tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_invalid_tags

2024-07-09 10:26 UTC, vsedmik commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_docker.py::TestDockerRepository::test_positive_sync tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_additive tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_content_only tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_invalid_tags

2024-07-09 10:47 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7675
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_docker.py::TestDockerRepository::test_positive_sync tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_additive tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_content_only tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_invalid_tags --external-logging
Test Result : ================== 5 passed, 47 warnings in 899.49s (0:14:59) ==================
```

2024-07-09 13:01 UTC, pondrejk requested changes

2024-07-09 13:18 UTC, vsedmik commented on tests/foreman/cli/test_repository.py
> +        #     assert tag in repo['container-image-tags-filter']
I need to figure it out first. It needs to be either deleted (if it's expected) or skipped (if it's a bug).

2024-07-09 17:43 UTC, vsedmik commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_docker.py::TestDockerRepository::test_positive_sync tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_additive tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_content_only tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_invalid_tags

2024-07-09 17:47 UTC, vsedmik commented on tests/foreman/cli/test_repository.py
> +        #     assert tag in repo['container-image-tags-filter']
Updated with the later.

2024-07-09 18:08 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7685
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_docker.py::TestDockerRepository::test_positive_sync tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_additive tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_content_only tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_invalid_tags --external-logging
Test Result : ================== 5 passed, 59 warnings in 979.01s (0:16:19) ==================
```

2024-07-10 06:07 UTC, LadislavVasina1 approved these changes
ack, looks good to me

2024-07-10 15:24 UTC, pondrejk approved these changes

2024-07-10 15:24 UTC, merged