CA- merge repo cli test scenarios, ansible collection repo sync and export
SatelliteQE/robottelo pull request #15621
Opened 2024-07-10 18:20 UTC by vijaysawant

### Problem Statement
Component audit - SAT-23366
Merge 2 related scenarios

### Solution
Merged into `test_positive_export_ansible_collection`
Removed testcase `test_positive_sync_ansible_collection`
Updated testcase name `test_positive_sync_and_export_ansible_collection`

### Related Issues
NA

## PRT test Cases example
```
trigger: test-robottelo
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_sync_and_export_ansible_collection'
```

2024-07-10 18:27 UTC, vijaysawant commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_sync_and_export_ansible_collection'

2024-07-10 18:28 UTC, vijaysawant commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_sync_and_export_ansible_collection'

2024-07-10 18:49 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7707
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_repository.py -k test_positive_sync_and_export_ansible_collection --external-logging
Test Result : ========= 2 passed, 133 deselected, 166 warnings in 754.20s (0:12:34) ==========
```

2024-07-11 07:34 UTC, vsedmik requested changes
I feel like we should keep the sync test for the sake of testing it in the _Repositories_ component and let the export (and import) be tested in the _ISS_ component where it actually belongs. We have coverage for export and import already: https://github.com/SatelliteQE/robottelo/blob/95a2ad019f08b7f3b0910f685d43d0f92b1946b0/tests/foreman/cli/test_satellitesync.py#L1670

2024-07-11 07:55 UTC, vijaysawant commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_repository.py::TestAnsibleCollectionRepository::test_positive_sync_ansible_collection

2024-07-11 08:12 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7709
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_repository.py::TestAnsibleCollectionRepository::test_positive_sync_ansible_collection --external-logging
Test Result : ================== 2 passed, 36 warnings in 657.68s (0:10:57) ==================
```

2024-07-11 08:50 UTC, omkarkhatavkar approved these changes

2024-07-11 08:50 UTC, merged