Add tests for host multi-CV
SatelliteQE/robottelo pull request #15688
Opened 2024-07-17 18:36 UTC by jeremylenz

### Problem Statement

There is no test coverage for existing features around multi-CV.

### Solution

Add tests covering existing functionality.

trigger: test-robottelo
pytest: tests/foreman/cli/test_host.py -k 'test_multi_cv_reg_not_allowed'

2024-07-17 18:37 UTC, omkarkhatavkar commented
Can one of the admins verify this patch?

2024-07-18 14:52 UTC, ColeHiggins2 commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_host.py -k 'test_multi_cv_reg_not_allowed'

2024-07-18 15:07 UTC, ColeHiggins2 commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_host.py -k test_multi_cv_reg_not_allowed

2024-07-18 15:14 UTC, ColeHiggins2 requested changes

2024-07-18 15:14 UTC, ColeHiggins2 commented on tests/foreman/cli/test_host.py
> +    So registration fails because multiple environments are not allowed.
indent this line to pass CI

2024-07-18 15:14 UTC, ColeHiggins2 commented on tests/foreman/cli/test_host.py
> +
We need to add an ID in the docstring

2024-07-18 15:14 UTC, ColeHiggins2 commented on tests/foreman/cli/test_host.py
> +
Lets add some extra assertions here to make sure the inital registration succeeds(helps for debugging tests if it ever fails) 
something like: 

```assert result.status == 0```
```assert rhel_contenthost.subscribed```

2024-07-18 15:14 UTC, ColeHiggins2 commented on tests/foreman/cli/test_host.py
> +
Lets assert a status here too

2024-07-18 17:04 UTC, jeremylenz commented
@ColeHiggins2 Rebased and comments should be addressed now. Also added an assertion that the setting is not exposed.

2024-07-18 17:05 UTC, jeremylenz commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_host.py -k 'test_multi_cv_reg_not_allowed'

2024-07-18 17:28 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7775
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_host.py -k test_multi_cv_reg_not_allowed --external-logging
Test Result : ========== 2 passed, 94 deselected, 128 warnings in 843.63s (0:14:03) ==========
```

2024-07-18 17:34 UTC, ColeHiggins2 requested changes

2024-07-18 17:34 UTC, ColeHiggins2 commented on tests/foreman/cli/test_host.py
> +def test_multi_cv_reg_not_allowed(
Lets also change this to a test_positive_multi_cv_reg_not_allowed or a test_negative_multi_cv_reg_not_allowed. In my mind... this is a test negative scenario

2024-07-18 17:40 UTC, jeremylenz commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_host.py -k 'test_negative_multi_cv_registration'

2024-07-18 17:59 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7776
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_host.py -k test_negative_multi_cv_registration --external-logging
Test Result : ========== 2 passed, 94 deselected, 129 warnings in 761.28s (0:12:41) ==========
```

2024-07-18 18:02 UTC, ColeHiggins2 approved these changes
Looks good to me!

2024-07-19 06:49 UTC, jyejare approved these changes

2024-07-19 06:50 UTC, merged