TFA fix for discovery plugin
SatelliteQE/robottelo pull request #15783
Opened 2024-07-26 17:04 UTC by amolpati30

The failure occurred because the code was deleting the discovery rule, and then attempting to read from the deleted table using the read_all method. To resolve this issue, I updated the method accordingly.

2024-07-26 17:20 UTC, amolpati30 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_discoveryrule.py -k test_positive_crud_with_non_admin_user
airgun: 1480

2024-07-26 17:40 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7882
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_discoveryrule.py -k test_positive_crud_with_non_admin_user --external-logging
Test Result : =========== 1 passed, 3 deselected, 16 warnings in 761.02s (0:12:41) ===========
```

2024-07-26 18:22 UTC, ColeHiggins2 approved these changes
Ack, pending airgun merge

2024-07-29 08:33 UTC, jameerpathan111 requested changes

2024-07-29 08:33 UTC, jameerpathan111 commented on tests/foreman/ui/test_discoveryrule.py
> +        assert new_rule_name not in dr_val
@amolpati30 you need to fix/update the rest of the tests too. There are 4 more places in the code where this change is needed. For example, https://github.com/SatelliteQE/robottelo/blob/276ddd0cae7923ac6921fd9fcdb9ab5c07533190/tests/foreman/ui/test_discoveryrule.py#L156

2024-07-31 14:14 UTC, amolpati30 commented
"trigger": "test-robottelo"
"pytest": "tests/foreman/ui/test_discoveryrule.py -k 'crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query or end_to_end'"
"airgun": "1480"

2024-07-31 14:57 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7928
Build Status: SUCCESS
PRT Comment: pytest /opt/app-root/src/robottelo/tests/foreman -v -m build_sanity --external-logging
Test Result : ======= 12 passed, 5526 deselected, 5633 warnings in 2122.04s (0:35:22) ========
```

2024-07-31 15:23 UTC, jameerpathan111 requested changes

2024-07-31 15:23 UTC, jameerpathan111 commented on tests/foreman/ui/test_discoveryrule.py
> +        assert dr.name not in dr_val
```suggestion
        assert dr.name in dr_val
```
@amolpati30 You have changed the assertion here. Is this expected?

2024-08-02 17:54 UTC, amolpati30 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_discoveryrule.py -k 'crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query or end_to_end'
airgun: 1480

2024-08-02 18:22 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7963
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_discoveryrule.py -k crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query or end_to_end --external-logging
Test Result : ============ 1 failed, 3 passed, 93 warnings in 1213.76s (0:20:13) =============
```

2024-08-02 19:25 UTC, amolpati30 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_discoveryrule.py -k 'crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query or test_positive_end_to_end'
airgun: 1480

2024-08-02 19:53 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7965
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_discoveryrule.py -k crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query or test_positive_end_to_end --external-logging
Test Result : ============ 1 failed, 3 passed, 97 warnings in 1214.82s (0:20:14) =============
```

2024-08-08 11:28 UTC, amolpati30 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_discoveryrule.py -k 'crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query'
airgun: 1480

2024-08-08 11:41 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8029
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_discoveryrule.py -k crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query --external-logging
Test Result : =========== 1 deselected, 9 warnings, 3 errors in 207.87s (0:03:27) ============
```

2024-08-08 20:46 UTC, amolpati30 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_discoveryrule.py -k 'crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query or end_to_end'
airgun: 1480

2024-08-08 20:57 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8054
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_discoveryrule.py -k crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query or end_to_end --external-logging
Test Result : ================== 9 warnings, 4 errors in 234.51s (0:03:54) ===================
```

2024-08-09 07:33 UTC, amolpati30 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_discoveryrule.py -k 'crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query or end_to_end'
airgun: 1480

2024-08-09 08:00 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8059
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_discoveryrule.py -k crud_with_non_admin_user or delete_rule_with_non_admin_user or list_host_based_on_rule_search_query or end_to_end --external-logging
Test Result : ============ 1 failed, 3 passed, 100 warnings in 1103.79s (0:18:23) ============
```

2024-08-09 10:50 UTC, amolpati30 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_discoveryrule.py -k 'crud_with_non_admin_user or end_to_end'
airgun: 1480

2024-08-09 11:14 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8062
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_discoveryrule.py -k crud_with_non_admin_user or end_to_end --external-logging
Test Result : =========== 2 passed, 2 deselected, 52 warnings in 992.86s (0:16:32) ===========
```

2024-08-23 17:20 UTC, amolpati30 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_discoveryrule.py -k 'crud_with_non_admin_user or end_to_end'
airgun: 1480

2024-08-23 17:42 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8264
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_discoveryrule.py -k crud_with_non_admin_user or end_to_end --external-logging
Test Result : =========== 2 passed, 2 deselected, 52 warnings in 935.46s (0:15:35) ===========
```

2024-08-28 12:50 UTC, shweta83 approved these changes
Ack

2024-08-28 13:47 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8334
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_discoveryrule.py -k crud_with_non_admin_user or end_to_end --external-logging
Test Result : =========== 2 passed, 2 deselected, 49 warnings in 845.80s (0:14:05) ===========
```

2024-08-29 06:01 UTC, merged