capsule upgrade playbook -- don't specify target version
SatelliteQE/robottelo pull request #15863
Opened 2024-08-06 09:08 UTC by pondrejk

### Problem Statement
Adjusting to the recent changes in satellite-maintain, for the test's scenario (upgrade from stream to stream) it no longer makes sense to specify the target version.

### Solution

### Related Issues
https://github.com/SatelliteQE/robottelo/pull/15862 is also needed to make this work, but that change is meant to be cherrypickes, while this should be master only

2024-08-06 09:16 UTC, lpramuk requested changes
Remove `--target-version` completely

2024-08-06 09:16 UTC, lpramuk commented on tests/foreman/api/test_remoteexecution.py
> +                'target_version': '',
Remove the line completely

2024-08-06 09:43 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule

2024-08-06 10:15 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7990
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k capsule --external-logging
Test Result : ========== 1 failed, 2 deselected, 16 warnings in 1382.00s (0:23:01) ===========
```

2024-08-06 10:41 UTC, lpramuk commented on tests/foreman/api/test_remoteexecution.py
> +                'target_version': '',
But there also need to be product changes - user option to specify `upgrade` or `update`

2024-08-06 10:42 UTC, lpramuk commented on tests/foreman/api/test_remoteexecution.py
> +                'target_version': '',
and `upgrade` is going to always fail for stream/6.16 since there is no 6.17 maintenance bits

2024-08-06 13:14 UTC, lpramuk commented on tests/foreman/api/test_remoteexecution.py
> -                'whitelist_options': 'repositories-validate,repositories-setup,non-rh-packages',
this change is merged already so please rebase

2024-08-06 14:37 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule

2024-08-06 15:11 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 7996
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k capsule --external-logging
Test Result : ========== 1 failed, 2 deselected, 16 warnings in 1458.04s (0:24:18) ===========
```

2024-08-07 09:31 UTC, lpramuk commented on tests/foreman/api/test_remoteexecution.py
> +                'target_version': '',
According to https://github.com/theforeman/foreman_ansible/pull/727 you should also change `job_template_id` from `upgrade` to `update`  unless you provide next version maintenance repo

2024-08-07 09:41 UTC, lpramuk requested changes
Please adjust job template name as well

2024-08-07 09:41 UTC, lpramuk commented on tests/foreman/api/test_remoteexecution.py
>              'job_template_id': template_id,
According to https://github.com/theforeman/foreman_ansible/pull/727 you should also change job_template_id from `Capsule Upgrade Playbook` to `Capsule Update Playbook` 
(unless you provide next version maintenance repo in order to upgrade to Y+1 successfully)

2024-08-07 13:05 UTC, pondrejk commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule
theforeman:
    foreman_ansible: 727
```

2024-08-07 13:56 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8004
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k capsule --external-logging
Test Result : ========== 1 failed, 2 deselected, 15 warnings in 2675.16s (0:44:35) ===========
```

2024-08-08 07:57 UTC, pondrejk commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule
theforeman:
    foreman_ansible: 727
```

2024-08-08 08:12 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8020
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k capsule --external-logging
Test Result : ============ 2 deselected, 8 warnings, 1 error in 291.51s (0:04:51) ============
```

2024-08-08 09:17 UTC, pondrejk commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule
theforeman:
    foreman_ansible: 727
```

2024-08-08 10:13 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8022
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k capsule --external-logging
Test Result : ========== 1 passed, 2 deselected, 15 warnings in 2774.65s (0:46:14) ===========
```

2024-09-04 09:42 UTC, pondrejk commented on tests/foreman/api/test_remoteexecution.py
> -    assert {'Ansible', 'Dynflow', 'Script', 'Pulpcore', 'Logs'}.issubset(feature_set)
Ansible is disabled by default on external capsules

2024-09-04 09:50 UTC, lpramuk approved these changes

2024-09-04 09:52 UTC, lpramuk commented
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule

2024-09-04 10:27 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8461
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k capsule --external-logging
Test Result : ========== 1 failed, 2 deselected, 15 warnings in 1457.51s (0:24:17) ===========
```

2024-09-04 10:58 UTC, lpramuk commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule
env:
    ROBOTTELO_server__version__release: '6.16.0'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16.0'
```

2024-09-04 11:08 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8463
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k capsule --external-logging
Test Result : ================= 2 deselected, 8 warnings, 1 error in 53.70s ==================
```

2024-09-04 12:18 UTC, lpramuk commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule
env:
    ROBOTTELO_server__version__release: '6.16.0'
    ROBOTTELO_server__version__snap: '2.0'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16.0'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '2.0'
```

2024-09-04 12:51 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8468
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k capsule --external-logging
Test Result : ========== 1 failed, 2 deselected, 15 warnings in 1438.00s (0:23:58) ===========
```

2024-09-05 12:54 UTC, pondrejk commented
@lpramuk looking at the prt result I suppose that changes from https://github.com/theforeman/foreman_ansible/pull/727 didn't get to 6.16 build... I'm sure they are not in stream either as the last foreman_ansible plugin release was before it got merged. So I guess we can re-run prt after plugin release and stream delivery happens

2024-09-06 07:05 UTC, lpramuk commented
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule

2024-09-06 07:58 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8500
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k capsule --external-logging
Test Result : ========== 1 failed, 2 deselected, 15 warnings in 2529.89s (0:42:09) ===========
```

2024-09-06 09:27 UTC, lpramuk commented
@pondrejk It is not even in today's stream/6.17 snap

2024-09-13 11:54 UTC, lhellebr commented
So what should happen without target version specified? Update to the latest stream snap? Do you really check somewhere that it has really been updated to the LATEST snap?

2024-09-13 11:55 UTC, lhellebr commented
Also, should it be in the recent snap?

2024-09-27 09:38 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k capsule

2024-09-30 16:59 UTC, pnovotny approved these changes
LGTM, PRT pending.

2024-10-04 09:29 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8868
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k test_positive_run_capsule_update_playbook --external-logging
Test Result : ========== 1 failed, 3 deselected, 16 warnings in 1609.68s (0:26:49) ===========
```

2024-10-24 07:47 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/api/test_remoteexecution.py -k test_positive_run_capsule_update_playbook

2024-10-24 08:21 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9131
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_remoteexecution.py -k test_positive_run_capsule_update_playbook --external-logging
Test Result : ========== 1 passed, 3 deselected, 16 warnings in 1526.59s (0:25:26) ===========
```

2024-10-24 12:05 UTC, merged