Add test coverage for Manage packages feature
SatelliteQE/robottelo pull request #15913
Opened 2024-08-12 14:06 UTC by LadislavVasina1

### Problem Statement
This Robottelo PR adds test coverage for the Manage Packages wizard. It is a new 6.16 feature with which users can manage packages.

`test_positive_manage_packages` is parametrized and the test cases are defined by the combination of the following parameters:

- number_of_hosts: 1 or 2

-  package_management_action: install_1_pckg, install_2_pckgs, upgrade_1_pckg, upgrade_all_pckgs, remove_1_pckg, remove_2_pckgs
- finish_via: rex or custom_rex
All this leads to 2 * 6 * 2 = 24 test cases in total.
For the visual representation of the test matrix see: https://miro.com/app/board/uXjVK0pTODA=/?share_link_id=776786926115

Depends on https://github.com/SatelliteQE/airgun/pull/1489

2024-08-12 14:15 UTC, LadislavVasina1 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
airgun: 1489
Katello:
    katello: 11101

2024-08-12 14:30 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8080
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_manage_packages --external-logging
Test Result : ========== 46 deselected, 75 warnings, 24 errors in 424.38s (0:07:04) ==========
```

2024-08-12 14:41 UTC, LadislavVasina1 commented
```trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
airgun: 1489
Katello:
    katello: 11101
```

2024-08-12 14:53 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8082
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_manage_packages --external-logging
Test Result : ========== 46 deselected, 75 warnings, 24 errors in 314.24s (0:05:14) ==========
```

2024-08-12 16:28 UTC, LadislavVasina1 commented
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '69.0'
airgun: 1489
Katello:
    katello: 11101

2024-08-12 16:29 UTC, LadislavVasina1 commented
```
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '69.0'
airgun: 1489
Katello:
    katello: 11101

2024-08-12 16:34 UTC, LadislavVasina1 commented
```
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
    ROBOTTELO_server__version__snap: '69.0'
airgun: 1489
Katello:
    katello: 11101

2024-08-12 16:40 UTC, ogajduse commented
```
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
    ROBOTTELO_server__version__snap: '69.0'
airgun: 1489
Katello:
    katello: 11101
```

2024-08-12 16:49 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
    ROBOTTELO_server__version__snap: '69.0'
airgun: 1489
Katello:
    katello: 11101

2024-08-12 17:04 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8086
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_manage_packages --external-logging
Test Result : ========== 46 deselected, 75 warnings, 24 errors in 355.76s (0:05:55) ==========
```

2024-08-12 17:11 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '69.0'
airgun: 1489
Katello:
    katello: 11101

2024-08-12 17:24 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8088
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_manage_packages --external-logging
Test Result : ========== 46 deselected, 75 warnings, 24 errors in 392.52s (0:06:32) ==========
```

2024-08-13 07:21 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
    ROBOTTELO_server__deploy_workflow: 'deploy-satellite-jenkins'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: 'stream'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '69.0'
airgun: 1489
Katello:
    katello: 11101

2024-08-13 07:32 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8093
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_manage_packages --external-logging
Test Result : ========== 46 deselected, 75 warnings, 24 errors in 261.83s (0:04:21) ==========
```

2024-08-13 08:49 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
    ROBOTTELO_server__version__snap: '69.0'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '69.0'
airgun: 1489
Katello:
    katello: 11101

2024-08-13 09:02 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8094
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_manage_packages --external-logging
Test Result : ========== 46 deselected, 75 warnings, 24 errors in 267.28s (0:04:27) ==========
```

2024-08-14 09:41 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
    ROBOTTELO_server__version__snap: '69.0'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '69.0'
airgun: 1489
Katello:
    katello: 11101

2024-08-14 09:54 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8102
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_manage_packages --external-logging
Test Result : ========== 46 deselected, 75 warnings, 24 errors in 415.00s (0:06:54) ==========
```

2024-08-14 19:26 UTC, sambible approved these changes
Would like to see passing PRT in CI, given that UI tests have a very remarkable ability to pass locally and fail in CI, but I wouldn't block it since it does seem there's some issues with packit PRT.

2024-08-14 19:26 UTC, sambible commented on tests/foreman/ui/test_host.py
> +    For the visual representation of the test matrix see: https://miro.com/app/board/uXjVK0pTODA=/?share_link_id=776786926115
I would leave this in the PR comments, but probably not in the actual test docstring.

2024-08-15 06:19 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
    ROBOTTELO_server__version__snap: '69.0'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '69.0'
airgun: 1489
Katello:
    katello: 11101

2024-08-15 08:10 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8120
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_host.py -k test_positive_manage_packages --external-logging
Test Result : ========= 24 passed, 46 deselected, 463 warnings in 6147.36s (1:42:27) =========
```

2024-08-15 09:07 UTC, vsedmik requested changes
Looks good! Just one change is actually needed, the rest are non-blocking proposals.

2024-08-15 09:10 UTC, LadislavVasina1 commented on tests/foreman/ui/test_host.py
> +                packages_to_upgrade = packages
it is intended, here we select more than 1 package even though the result will be the same as Upgrade All packages, the way it is reached is different

2024-08-15 09:12 UTC, LadislavVasina1 commented on tests/foreman/ui/test_host.py
> +        if used_action == 'install':
lets keep ifs :D

2024-08-15 09:12 UTC, vsedmik commented on tests/foreman/ui/test_host.py
> +                packages_to_upgrade = packages
Okay I got the answer from further assertions.

2024-08-15 10:09 UTC, vsedmik approved these changes

2024-08-15 12:08 UTC, ogajduse approved these changes
Given that PRT passed, I would not block it. Could you please consider transforming my comments into GH issues? You can pick them up later.

2024-08-15 12:08 UTC, ogajduse commented on tests/foreman/ui/test_host.py
> +                    ), f'Package "{package}" is not installed in the latest version!'
Optional:
if `packages_latest_version_dict` would be a list and would be created as follows:
```python
packages_latest_version_list = []
for item in packages_list:
    parts = item.split()
    # Remove architecture part from package name
    package_name = parts[0].split('.')[0]
    version = parts[1]  # parts look like ['package_name', 'version', 'repo']
    packages_latest_version_list.append({"name": package_name, "version": version})
```

then you could compare it using
```suggestion
                res = host.execute('rpm --query --all --queryformat="%{NAME},%{VERSION},%{RELEASE},%{ARCH}\n"')
                import csv
                installed_packages = [value for value in csv.DictReader(res.stdout.splitlines(), fieldnames={'name', 'version', 'release', 'arch'})]
                
                
```

The reason why I suggest it is that using 
Pick whatever you like from the whole suggestion, but I insist on using `--queryformat`. Doing regular expression magic on `rpm -q`/`rpm -qa` output is a hazard.

2024-08-15 12:14 UTC, merged