using custom org for timezone test
SatelliteQE/robottelo pull request #16261
Opened 2024-09-06 12:24 UTC by pondrejk

### Problem Statement
the test failed kind of mysteriously on module_org not found when associating the user. Local runs are ok, I suspect some interference with other tests from module. 

### Solution
Trying out a version with custom org

### Related Issues

2024-09-06 12:25 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_organization.py -k test_positive_create_user_with_timezone

2024-09-06 12:44 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8509
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_organization.py -k test_positive_create_user_with_timezone --external-logging
Test Result : ========== 1 passed, 36 deselected, 45 warnings in 715.97s (0:11:55) ===========
```

2024-09-06 14:44 UTC, synkd requested changes
Looks good overall. Since `module_org` is no longer used in the test, though, would you please remove it from the test definition?

2024-09-09 07:17 UTC, pondrejk commented
> Looks good overall. Since `module_org` is no longer used in the test, though, would you please remove it from the test definition?

done, thanks!

2024-09-09 13:07 UTC, synkd approved these changes

2024-09-09 14:08 UTC, merged