[6.15.z][Combined Jenkins Ask] Capsule testing for sanity (#15948)
SatelliteQE/robottelo pull request #16420
Opened 2024-09-19 09:40 UTC by jyejare

### Problem Statement
Caspule Test isnt a part of sanity testing due to several reasons:
1. Most test cases were dependent on Satellite and not on capsule
2. The running time for sanity for separate capsule checkout and installation, configuration exceeds our target sanity runtime

### Solution
Adding capsule installer test as part of sanity since Sanity is replacing bats tests in jenkins migration in delivery.

### Related Issues

2024-09-19 09:41 UTC, jyejare commented
trigger: test-robottelo
pytest: tests/foreman -m build_sanity

2024-09-19 14:02 UTC, jyejare commented
trigger: test-robottelo
pytest: tests/foreman -m build_sanity

2024-09-19 14:44 UTC, jameerpathan111 commented on pytest_fixtures/core/sat_cap_factory.py
> +    if 'build_sanity' not in request.config.option.markexpr:
@jyejare This is not a good approach. This change will cause unnecessary call to `module_target_sat` and extra checkout in normal automation run.

2024-09-19 14:50 UTC, jameerpathan111 requested changes

2024-09-19 14:50 UTC, jameerpathan111 commented on tests/foreman/installer/test_installer.py
> +            cmmd = 'satellite-maintain packages install -y fapolicyd'
This is wrong, there's won't be any satellite related packages installed on the rhel machine. It has to be done through dnf. It's done later in the setup
```suggestion
```

2024-09-19 14:55 UTC, jameerpathan111 requested changes

2024-09-19 14:55 UTC, jameerpathan111 commented on tests/foreman/installer/test_installer.py
> +    sat = module_sat_ready_rhels.pop()
Why are we using `pop` here. It'll remove Satellite from `module_sat_ready_rhels`, this could be used somewhere later in some other tests.

2024-09-19 15:15 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8733
Build Status: SUCCESS
PRT Comment: pytest tests/foreman -m build_sanity --external-logging
Test Result : ======= 12 passed, 5455 deselected, 5789 warnings in 3778.60s (1:02:58) ========
```

2024-09-19 20:52 UTC, JacobCallahan commented
@jameerpathan111 this is a cherry-pick, so should be merged as-is. @jyejare can then address your feedback in a new PR against master, which will then be cherry-picked back on top of this.

With that in mind, please collect your feedback and file a new issue with everything.

2024-09-19 20:52 UTC, JacobCallahan approved these changes

2024-09-20 11:25 UTC, jameerpathan111 commented
> With that in mind, please collect your feedback and file a new issue with everything.

Sure

2024-09-20 11:26 UTC, jameerpathan111 approved these changes

2024-09-20 17:37 UTC, Gauravtalreja1 commented
@jyejare @JacobCallahan As this is a manual cherrypick only, so how about we handle the feedback from @jameerpathan111 here only and open a separate PR to address in master/6.16.z only, that way we could avoid more cherrypick PRs :)

2024-09-20 17:54 UTC, jyejare commented
@Gauravtalreja1 I dont see any immediate blocker for merging this one from Jameers comment.

Max there would be an increase in total time for installer tests.

2024-09-23 11:04 UTC, rmynar approved these changes

2024-09-23 11:11 UTC, merged