changes to use the beaker urls for running upstream sanity
SatelliteQE/robottelo pull request #16549
Opened 2024-10-02 09:13 UTC by omkarkhatavkar

### Problem Statement
Currently, the sanity tests are tightly coupled with "Oh Snap" for retrieving required repository URLs. This creates a dependency that hinders the flexibility of running the same tests with alternative URL sources, such as Beaker URLs. The reliance on "Oh Snap" is particularly limiting when running upstream sanity tests right after building the necessary bits. This dependency affects the ability to run tests in different environments efficiently.

### Solution
This PR aims to decouple the sanity tests from "Oh Snap" by introducing a more flexible approach for handling repository URLs. Instead of relying exclusively on "Oh Snap" to fetch the URLs, we will modify the behaviour to allow passing the repository URLs directly through a repos file. This approach provides more control and adaptability, enabling tests to run seamlessly with either Beaker URLs or other sources without modifying the core logic.

By doing this, we improve the modularity of the tests, allowing upstream sanity runs to proceed immediately after building the necessary bits, enhancing efficiency and reducing dependencies on external services.

2024-10-02 13:42 UTC, rmynar reviewed
I recently faced similar situation - it was about using GA or internal repositories. I used server.version.source (https://github.com/SatelliteQE/robottelo/blob/master/conf/server.yaml.template#L11-L13) and I think it might be useful also in this case...
Maybe modifying sources from "ga, internal "to "ga. ohsnap, nightly" (ohsnap and nightly are both internal, just different url)

2024-10-02 15:56 UTC, ogajduse requested changes

2024-10-03 07:01 UTC, omkarkhatavkar commented
> I recently faced similar situation - it was about using GA or internal repositories. I used server.version.source (https://github.com/SatelliteQE/robottelo/blob/master/conf/server.yaml.template#L11-L13) and I think it might be useful also in this case... Maybe modifying sources from "ga, internal "to "ga. ohsnap, nightly" (ohsnap and nightly are both internal, just different url)

@ogajduse @jyejare what you guys think about this ?

2024-10-03 07:23 UTC, jyejare commented
@omkarkhatavkar Yeah I think we should be able to use the existing setting rather than defining new. BTW just assess the usage and the impact of modifying that setting for nightly should not bring in regressions.

2024-10-03 13:55 UTC, omkarkhatavkar commented on conf/dynaconf_hooks.py
> +        data = get_repos_config(settings)
It is not required if it is nightly as the settings are already loaded with the correct beaker URLs.

2024-10-03 13:55 UTC, omkarkhatavkar commented on conf/dynaconf_hooks.py
> +    if getattr(settings.robottelo.settings, 'fetch_from_ohsnap', True):
After new design I will be avoiding to add the `fetch_from_ohsnap ` as it will be not required

2024-10-03 13:56 UTC, omkarkhatavkar commented on conf/dynaconf_hooks.py
> +    if is_url(settings.ohsnap.host) and settings.robottelo.settings.fetch_from_ohsnap:
I will be removing the `fetch_from_ohsnap ` as it will be not needed

2024-10-07 06:00 UTC, omkarkhatavkar commented
@ogajduse @jyejare @rmynar can you please review second time ?

2024-10-07 06:01 UTC, omkarkhatavkar commented
@ogajduse PRT results are attached to CI PR, it has been ran on the MR-Jenkins. Please take a look at it.

2024-10-07 11:47 UTC, rmynar requested changes

2024-10-07 11:53 UTC, ogajduse approved these changes
ACK, pending Radek's comments. One small suggestion regarding code readability left.

2024-10-07 11:53 UTC, ogajduse commented on tests/foreman/installer/test_installer.py
> +                )
```suggestion
            if settings.server.version.source == 'nightly':
                repo_url = url=getattr(settings.repos, repo_default_url)
            else:
                repo_url = dogfood_repository(
                    ohsnap=settings.ohsnap,
                    repo=repo_variant,
                    product="capsule",
                    release=settings.capsule.version.release,
                    os_release=capsule_host.os_version.major,
                    snap=settings.capsule.version.snap,
                ).baseurl
```

and below the `url` kwarg in `Repository` class instantiation would be `url=repo_url`.

That makes the code a bit more readable.

2024-10-07 13:52 UTC, ogajduse approved these changes
Nice work. In the future, we might want to separate the `if nightly` logic from `if fetch_stuff_from_ohsnap`. But that is fine at the moment.

2024-10-07 14:04 UTC, jyejare approved these changes

2024-10-07 14:07 UTC, rmynar commented
```
trigger: test-robottelo
pytest: tests/foreman/installer/test_installer.py::test_satellite_installation tests/foreman/installer/test_installer.py::test_capsule_installation
env:
  ROBOTTELO_server__version__source: 'nightly'
  ROBOTTELO_capsule__version__source: 'nightly'
```

2024-10-07 14:11 UTC, omkarkhatavkar commented
@rmynar As I mentioned earlier, please take a look at the CI PR for PRT result which uses beaker repos. I have already tested that.

2024-10-07 15:58 UTC, jyejare commented
The required changes in CI are yet to merge but we can merge this PR independently. This should not bring any regression.

2024-10-08 05:11 UTC, omkarkhatavkar commented
trigger: test-robottelo

2024-10-08 06:01 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8891
Build Status: SUCCESS
PRT Comment: pytest /opt/app-root/src/robottelo/tests/foreman -v -m build_sanity --external-logging
Test Result : ======= 13 passed, 5445 deselected, 5709 warnings in 2762.33s (0:46:02) ========
```

2024-10-08 06:36 UTC, rmynar approved these changes
> @rmynar As I mentioned earlier, please take a look at the CI PR for PRT result which uses beaker repos. I have already tested that.

It looks better with the "PRT Passed" label ;-)

2024-10-08 09:21 UTC, merged