Fix Discovery Tests
SatelliteQE/robottelo pull request #16605
Opened 2024-10-08 04:22 UTC by shweta83

### Problem Statement

### Solution

### Related Issues

2024-10-08 04:23 UTC, shweta83 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host[rhel8-ipv4-bios-discovery]
"provisioning": true

2024-10-08 04:41 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8889
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host[rhel8-ipv4-bios-discovery] --external-logging
Test Result : =========== 1 deselected, 10 warnings, 1 error in 617.93s (0:10:17) ============
```

2024-10-08 04:55 UTC, shweta83 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host
"provisioning": true
env:
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16'
```

2024-10-08 06:17 UTC, shweta83 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host
provisioning: true
env:
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16'
```

2024-10-08 06:19 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8890
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host --external-logging
Test Result : ========== 4 deselected, 35 warnings, 4 errors in 4738.30s (1:18:58) ===========
```

2024-10-08 07:59 UTC, Gauravtalreja1 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host
provisioning: true
env:
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16'
    BROKER_SSH_BACKEND: hussh
```

2024-10-08 09:24 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8898
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host --external-logging --include-onprem-provisioning
Test Result : ================= 35 warnings, 4 errors in 4722.20s (1:18:42) ==================
```

2024-10-09 00:33 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 8908
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host --external-logging --include-onprem-provisioning
Test Result : ================= 35 warnings, 4 errors in 4706.57s (1:18:26) ==================
```

2024-10-24 10:43 UTC, shweta83 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host
provisioning: true
env:
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16'
    BROKER_SSH_BACKEND: hussh
```

2024-10-24 12:10 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9138
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host --external-logging --include-onprem-provisioning
Test Result : ================= 35 warnings, 4 errors in 4744.65s (1:19:04) ==================
```

2024-11-12 06:46 UTC, shweta83 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host
provisioning: true
env:
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16'
    BROKER_SSH_BACKEND: hussh
```

2024-11-12 08:11 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9329
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host --external-logging --include-onprem-provisioning
Test Result : ================= 35 warnings, 4 errors in 4775.78s (1:19:35) ==================
```

2024-11-12 10:45 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9331
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host --external-logging --include-onprem-provisioning
Test Result : ================= 35 warnings, 4 errors in 4760.52s (1:19:20) ==================
```

2024-11-12 14:18 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9336
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py::TestDiscoveredHost::test_positive_provision_pxe_host --external-logging --include-onprem-provisioning
Test Result : ================= 4 passed, 389 warnings in 3366.96s (0:56:06) =================
```

2024-11-12 16:44 UTC, shweta83 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py
provisioning: true
env:
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '9'
    BROKER_SSH_BACKEND: hussh
```

2024-11-12 18:45 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9340
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py --external-logging --include-onprem-provisioning
Test Result : ==== 3 failed, 11 passed, 1 deselected, 1404 warnings in 6781.18s (1:53:01) ====
```

2024-11-12 21:36 UTC, Gauravtalreja1 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py
provisioning: true
env:
    BROKER_SSH_BACKEND: hussh
```

2024-11-12 23:49 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9341
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py --external-logging --include-onprem-provisioning
Test Result : ==== 7 failed, 7 passed, 1 deselected, 1356 warnings in 7656.31s (2:07:36) =====
```

2024-11-13 07:50 UTC, shubhamsg199 requested changes
@shweta83 Can you also update https://github.com/SatelliteQE/robottelo/blob/37a277b2918e354c562c5c48c20d68c3b8fa4410/tests/foreman/api/test_provisioning.py#L394

2024-11-13 07:57 UTC, shweta83 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioning.py -k test_rhel_httpboot_provisioning
provisioning: true
env:
    BROKER_SSH_BACKEND: hussh
```

2024-11-13 08:01 UTC, shubhamsg199 approved these changes
Ack, PRT 9336 passed

2024-11-13 08:27 UTC, amolpati30 approved these changes

2024-11-13 09:27 UTC, shweta83 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py
provisioning: true
env:
    BROKER_SSH_BACKEND: hussh

2024-11-13 09:29 UTC, shweta83 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py --external-logging --include-onprem-provisioning
provisioning: true
env:
    BROKER_SSH_BACKEND: hussh
```

2024-11-13 11:31 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9345
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py --external-logging --include-onprem-provisioning --external-logging --include-onprem-provisioning
Test Result : = 5 failed, 9 passed, 1 deselected, 1428 warnings, 1 error in 6892.35s (1:54:52) =
```

2024-11-13 12:11 UTC, Gauravtalreja1 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py --external-logging --include-onprem-provisioning -m on_premises_provisioning
env:
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '9'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '9.0'
    BROKER_SSH_BACKEND: hussh
```

2024-11-13 12:13 UTC, Gauravtalreja1 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_discoveredhost.py --external-logging --include-onprem-provisioning -m on_premises_provisioning
provisioning: true
env:
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '9'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '9.0'
    BROKER_SSH_BACKEND: hussh
```

2024-11-13 14:12 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9347
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_discoveredhost.py --external-logging --include-onprem-provisioning -m on_premises_provisioning --external-logging --include-onprem-provisioning
Test Result : ==== 1 failed, 9 passed, 5 deselected, 1331 warnings in 6593.00s (1:49:52) =====
```

2024-11-13 14:52 UTC, Gauravtalreja1 approved these changes

2024-11-13 14:52 UTC, merged