New fixes and improvements to pytest req updates plugin
SatelliteQE/robottelo pull request #16692
Opened 2024-10-17 10:07 UTC by jyejare

### Problem Statement

### Solution

### Related Issues

2024-10-21 21:03 UTC, JacobCallahan requested changes
minor phrasing. ack on the concept though

2024-10-21 21:03 UTC, JacobCallahan commented on pytest_plugins/requirements/req_updater.py
> +                print('Required requirements are installed to be up-to-date.')
```suggestion
                print('Required requirements updated.')
```

2024-10-21 21:03 UTC, JacobCallahan commented on pytest_plugins/requirements/req_updater.py
> +                print('Optional requirements are installed to be up-to-date.')
```suggestion
                print('Optional requirements updated.')
```

2024-10-23 09:46 UTC, jyejare commented
@JacobCallahan Please revisit, all comments are fixed.

2024-10-23 09:46 UTC, jyejare commented
@JacobCallahan Please revisit, all comments are fixed.

2024-10-23 22:48 UTC, JacobCallahan approved these changes

2024-10-25 12:10 UTC, merged