[6.16.z] Migrate Old CV UI coverage (Upgrade)
SatelliteQE/robottelo pull request #16768
Opened 2024-10-24 17:15 UTC by Satellite-QE

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16283

#### Purpose
- Migrate upgrade case from `test_contentview_old.py` (not collected during test sessions)
- Promoted CVV in multiple environments, using UI to Delete the CVV and/or CV, removes it from the environments.
- Needs [Airgun 1592](https://github.com/SatelliteQE/airgun/pull/1592))

#### PRT Case (for Upgrade)
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py::test_positive_delete_cv_promoted_to_multi_env
airgun: 1592
env:
    ROBOTTELO_server__deploy_workflow: 'deploy-satellite-upgrade'
    ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '9'
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: 'ystream'
    BROKER_AnsibleTower__inventory: 'osp-rhos01-satellite-upgrade'
```

2024-10-24 17:15 UTC, Satellite-QE commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py::test_positive_delete_cv_promoted_to_multi_env
airgun: 1592

2024-10-24 18:19 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9150
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_contentview.py::test_positive_delete_cv_promoted_to_multi_env --external-logging
Test Result : ================= 1 failed, 10 warnings in 1148.35s (0:19:08) ==================
```

2024-10-25 15:12 UTC, vsedmik commented
@damoore044 , import of `VERSION` hasn't been cherry-picked to this branch, you'll need to add it
20:19:22  >           assert cv_info['Latest version'] == VERSION, (
20:19:22                  f'Latest version for CV {cv["name"]}: {cv_info["Latest version"]},'
20:19:22                  f' does not match expected: {VERSION}.'
20:19:22              )
20:19:22  E           NameError: name 'VERSION' is not defined
```

2024-10-25 15:14 UTC, vsedmik requested changes

2024-10-25 15:14 UTC, vsedmik commented on tests/foreman/ui/test_contentview.py
> +)
```suggestion
)

VERSION = 'Version 1.0'
```

2024-12-18 05:38 UTC, closed without merging