Convert Discovery upgrade scenario to new format
SatelliteQE/robottelo pull request #16898
Opened 2024-11-12 20:18 UTC by synkd

As part of the current upgrade scenarios refactor, this PR converts the Discovery pre-upgrade scenario to a Pytest fixture and modifies the pre- and post-upgrade scenarios to use the `SharedResource` framework.

2024-11-12 22:03 UTC, synkd commented
trigger: test-robottelo
pytest: tests/new_upgrades/test_discovery.py
env:
  BROKER_SSH_BACKEND: hussh

2024-11-12 22:55 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9343
Build Status: SUCCESS
PRT Comment: pytest tests/new_upgrades/test_discovery.py --external-logging
Test Result : ================= 1 passed, 19 warnings in 2645.89s (0:44:05) ==================
```

2024-11-13 11:11 UTC, vsedmik approved these changes
Looks good to me.

@synkd Would you mind to update the [CODEOWNERS](https://github.com/SatelliteQE/robottelo/blob/master/.github/CODEOWNERS) file with the new addition? We use it for the team-based review requests / heads up. Thank you!

2024-11-13 14:58 UTC, synkd commented
> @synkd Would you mind to update the [CODEOWNERS](https://github.com/SatelliteQE/robottelo/blob/master/.github/CODEOWNERS) file with the new addition? We use it for the team-based review requests / heads up. Thank you!

Added, thanks for pointing that out.

2025-01-02 09:38 UTC, vsedmik requested changes

2025-01-02 09:38 UTC, vsedmik commented on .github/CODEOWNERS
> +tests/new_upgrades/test_discovery.py @SatellitQE/team-rocket
```suggestion
tests/new_upgrades/test_discovery.py @SatelliteQE/team-rocket
```
A typo needs to be fixed.

2025-04-23 14:44 UTC, shubhamsg199 approved these changes

2025-04-23 15:06 UTC, shubhamsg199 commented on tests/new_upgrades/conftest.py
> +    """Mark tests using this fixture with pytest.mark.content_upgrades."""
Should be `pytest.mark.discovery_upgrades` right?

2025-04-24 20:40 UTC, synkd commented on tests/new_upgrades/conftest.py
> +    """Mark tests using this fixture with pytest.mark.content_upgrades."""
@shubhamsg199 Since the pre-upgrade scenarios in the new format are fixtures rather than tests, I don't think they should be marked with `*_upgrades` marks. The tests that will be collected and that should be marked in this way are now the post-upgrade scenarios, all of which will inherit their corresponding pre-upgrade scenario fixtures.

2025-04-25 09:53 UTC, shubhamsg199 commented on tests/new_upgrades/conftest.py
> +    """Mark tests using this fixture with pytest.mark.content_upgrades."""
Yes, I understood I meant the comment of the fixture `"""Mark tests using this fixture with pytest.mark.content_upgrades."""` to `"""Mark tests using this fixture with pytest.mark.discovery_upgrades."""`

2025-04-30 17:25 UTC, synkd commented on tests/new_upgrades/conftest.py
> +    """Mark tests using this fixture with pytest.mark.content_upgrades."""
@shubhamsg199 Whoops, sorry for my misunderstanding. You are right of course. Just made the change.

2025-05-02 07:06 UTC, vsedmik approved these changes
LGTM

2025-05-02 15:58 UTC, synkd commented
Since the only framework-level change here is to the `CODEOWNERS` file, I don't think tier 2 review is actually required for this. I'm open to debate on this point, but for now, I'm merging this PR.

2025-05-02 15:58 UTC, merged