Convert perf tuning upgrade scenario to new format
SatelliteQE/robottelo pull request #16929
Opened 2024-11-15 18:38 UTC by synkd

As part of the current upgrade scenarios refactor, this PR converts the performance tuning scenario to use the `SharedResource` framework, converts the pre-upgrade test to a Pytest fixture, and adds a Satellite upgrade fixture for this scenario.

2024-11-15 18:54 UTC, synkd commented
trigger: test-robottelo
pytest: tests/new_upgrades/test_performance_tuning.py
env:
  BROKER_SSH_BACKEND: hussh

2024-11-15 20:13 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9374
Build Status: SUCCESS
PRT Comment: pytest tests/new_upgrades/test_performance_tuning.py --external-logging
Test Result : ================= 1 passed, 19 warnings in 4301.67s (1:11:41) ==================
```

2024-11-18 21:37 UTC, JacobCallahan requested changes
Some minor comments for ids. Otherwise, this is looking nice

2024-11-18 21:37 UTC, JacobCallahan commented on tests/new_upgrades/test_performance_tuning.py
> +    :id: preupgrade-83404326-20b7-11ea-a370-48f17f1fc2e1
we should be able to drop ids for this since it's a fixture now

2024-11-18 21:37 UTC, JacobCallahan commented on tests/new_upgrades/test_performance_tuning.py
> +    :id: postupgrade-31e26b08-2157-11ea-9223-001a4a1601d8
May be best to remove post-upgrade from these as well
```suggestion
    :id: 31e26b08-2157-11ea-9223-001a4a1601d8
```

2025-04-29 11:25 UTC, lpramuk commented on tests/new_upgrades/test_performance_tuning.py
> +    with SharedResource(target_sat.hostname, upgrade_action, target_sat=target_sat) as sat_upgrade:
`target_sat.hostname`  and `target_sat=target_sat` ?
why such duplicity ?

2025-04-29 11:44 UTC, lpramuk approved these changes

2025-04-30 15:27 UTC, synkd commented on tests/new_upgrades/test_performance_tuning.py
> +    with SharedResource(target_sat.hostname, upgrade_action, target_sat=target_sat) as sat_upgrade:
@lpramuk looks like both are needed: 
```
2025-04-30 10:19:13 - robottelo - ERROR - Exception thrown:
    self = <robottelo.utils.shared_resource.SharedResource object at 0x7f0f0985bd90>
    
        def act(self):
            """Attempt to perform the action."""
            try:
    >           result = self.action(*self.action_args, **self.action_kwargs)
    E           TypeError: upgrade_action.<locals>._upgrade_action() missing 1 required positional argument: 'target_sat'
```
So we need `target_sat.hostname`, as that is being passed as the `resource_name` (the name of the file in `/tmp` tracking the Xdist workers) of the `SharedResource` object, and we need `target_sat=target_sat` as that is passed to  the `act` method of the `SharedResource` object, which in this case calls the `upgrade_action` fixture, which passes the `target_sat` to Broker, which calls the `upgrade-satellite` AAP job.

2025-05-13 19:47 UTC, JacobCallahan approved these changes
ACK, nice!

2025-05-13 19:48 UTC, merged