Donwload policy on_demand supported for file type repository
SatelliteQE/robottelo pull request #16960
Opened 2024-11-20 08:57 UTC by dosas

see https://github.com/Katello/katello/pull/11184

### Problem Statement

see title

### Solution

adapt tests

### Related Issues

2024-11-20 09:02 UTC, Satellite-QE commented
Can one of the admins verify this patch?

2024-11-22 16:31 UTC, vsedmik requested changes
Hello @dosas. Could you please rebase/resolve conflict since https://github.com/SatelliteQE/robottelo/pull/16961 got merged?
Please update the docstrings too. Thank you!

2024-11-26 13:24 UTC, dosas commented
> Hello @dosas. Could you please rebase/resolve conflict since #16961 got merged? Please update the docstrings too. Thank you!

@vsedmik done

2024-11-26 15:14 UTC, vsedmik approved these changes
Thank you!

2024-11-27 07:58 UTC, dosas commented
@vsedmik How many reviews do we need? Is one enough?

2024-11-27 14:32 UTC, damoore044 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_repository.py::TestRepository::test_negative_create_repos_with_download_policy tests/foreman/cli/test_repository.py::TestRepository::test_negative_create_repos_with_download_policy 
```

2024-11-27 14:46 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_repository.py::TestRepository::test_negative_create_repos_with_download_policy tests/foreman/cli/test_repository.py::TestRepository::test_negative_create_repos_with_download_policy

2024-11-27 16:04 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9472
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_repository.py::TestRepository::test_negative_create_repos_with_download_policy --external-logging
Test Result: ================== 3 passed, 32 warnings in 513.83s (0:08:33) ==================
```

2024-11-27 16:19 UTC, damoore044 approved these changes
nice PRT pass, thank you

2024-11-27 16:20 UTC, merged