RHEL10 Clients coverage in Content, some rhel8 content bumped to rhel9
SatelliteQE/robottelo pull request #17003
Opened 2024-11-26 22:14 UTC by damoore044

### PRT Case 
#### for cases parametrized using fixture `rhel_contenthost`
```
trigger: test-robottelo
pytest: tests/foreman/api cli ui/module.py -k 'rhel10' 
env:
     ROBOTTELO_content_host__rhel10__vm__workflow: 'deploy-template'
     ROBOTTELO_content_host__rhel10__vm__deploy_template_type: 'rhel'
     ROBOTTELO_content_host__rhel10__vm__deploy_custom_template_version: '10'
```

2024-11-26 22:28 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ -k 'rhel10' --ignore-glob='**/test_errata.py' --collect-only

2024-11-26 22:29 UTC, damoore044 commented
^ ignoring errata rhel10 cases for first collection, 
as they've already been tested and merged in #16807

2024-11-26 22:37 UTC, damoore044 commented
```
trigger: test-robottelo
pytest: tests/foreman/ -k 'rhel10' --collect-only $(find tests/foreman/ -type f -name 'test_errata.py' -exec echo --ignore={} \;)
```

2024-11-26 22:53 UTC, damoore044 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/ -k 'rhel10' $(find tests/foreman/ -type f -name 'test_errata.py' -exec echo --ignore={} \;)
env:
     ROBOTTELO_content_host__rhel10__vm__workflow: 'deploy-template'
     ROBOTTELO_content_host__rhel10__vm__deploy_template_type: 'rhel'
     ROBOTTELO_content_host__rhel10__vm__deploy_custom_template_version: '10'
```

2024-11-26 22:54 UTC, damoore044 commented
^ foreman/API tests with rhel10 params, ignoring test_errata.py

2024-11-26 22:58 UTC, damoore044 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/ -k 'rhel10' $(find tests/foreman/api -type f -name 'test_errata.py' -exec echo --ignore={} \;)
env:
     ROBOTTELO_content_host__rhel10__vm__workflow: 'deploy-template'
     ROBOTTELO_content_host__rhel10__vm__deploy_template_type: 'rhel'
     ROBOTTELO_content_host__rhel10__vm__deploy_custom_template_version: '10'
```

2024-11-26 22:59 UTC, damoore044 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/ -k 'rhel10' $(find tests/foreman/api/ -type f -name 'test_errata.py' -exec echo --ignore={} \;)
env:
     ROBOTTELO_content_host__rhel10__vm__workflow: 'deploy-template'
     ROBOTTELO_content_host__rhel10__vm__deploy_template_type: 'rhel'
     ROBOTTELO_content_host__rhel10__vm__deploy_custom_template_version: '10'
```

2024-11-27 13:00 UTC, damoore044 commented
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_contenthost.py -k 'rhel10' 
env:
     ROBOTTELO_content_host__rhel10__vm__workflow: 'deploy-template'
     ROBOTTELO_content_host__rhel10__vm__deploy_template_type: 'rhel'
     ROBOTTELO_content_host__rhel10__vm__deploy_custom_template_version: '10'
```

2024-11-27 14:53 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9471
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_contenthost.py -k rhel10 --external-logging
Test Result : == 10 failed, 10 passed, 129 deselected, 1457 warnings in 6396.11s (1:46:36) ===
```

2024-11-29 17:44 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

2024-11-29 20:49 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9490
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_errata.py --external-logging
Test Result : ========== 4 failed, 10 passed, 4437 warnings in 10620.88s (2:57:00) ===========
```

2024-12-07 13:29 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_errata.py

2024-12-07 15:30 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9554
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_errata.py --external-logging
Test Result : =========== 7 failed, 1279 warnings, 7 errors in 6489.17s (1:48:09) ============
```

2024-12-17 16:37 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api -k 'rhel10'

2024-12-17 21:17 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9659
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli -k rhel10 --external-logging
Test Result : = 9 failed, 12 passed, 1938 deselected, 5353 warnings, 14 errors in 16245.78s (4:30:45) =
```

2025-01-08 18:18 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api -k 'rhel10'

2025-01-08 20:35 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9790
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api -k rhel10 --external-logging
Test Result : = 3 failed, 11 passed, 2322 deselected, 3890 warnings, 9 errors in 7672.85s (2:07:52) =
```

2025-01-09 14:14 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api -k 'rhel10'

2025-01-09 17:39 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9801
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api -k rhel10 --external-logging
Test Result : == 3 failed, 20 passed, 2322 deselected, 5664 warnings in 11824.01s (3:17:04) ==
```

2025-01-09 17:48 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api -k 'rhel10'

2025-01-09 17:50 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_contenthost.py

2025-01-09 18:34 UTC, chris1984 reviewed
Left a few comments from just a quick glance.

2025-01-09 18:34 UTC, chris1984 commented on pytest_fixtures/component/provisioning_template.py
> +        repo_names.append(f'rhel{rhel_ver}_bos_beta')
Will these be switched to the GA repos once RHEL 10 goes GA?

2025-01-09 18:34 UTC, chris1984 commented on pytest_fixtures/core/contenthosts.py
> +@pytest.fixture(params=[{'rhel_version': 6}])
Since RHEL 6 is EOL even with extended maintenance, is it worth keeping a fixture for RHEL 6?

2025-01-10 01:11 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9805
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api -k rhel10 --external-logging
Test Result : = 4 failed, 21 passed, 2319 deselected, 7607 warnings, 1 error in 23726.29s (6:35:26) =
```

2025-01-10 16:02 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_contenthost.py

2025-01-10 17:02 UTC, damoore044 commented on pytest_fixtures/core/contenthosts.py
> +@pytest.fixture(params=[{'rhel_version': 6}])
@vsedmik @JacobCallahan thoughts on dropping fixture `rhel6_contenthost` in stream?

2025-01-10 21:57 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9819
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_contenthost.py --external-logging
Test Result : = 3 failed, 9 passed, 1 deselected, 1027 warnings, 10 errors in 20731.91s (5:45:31) =
```

2025-01-13 15:42 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/cli -k 'rhel10'

2025-01-14 02:14 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9847
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli -k rhel10 --external-logging
Test Result : = 2 failed, 10 passed, 1959 deselected, 4068 warnings, 30 errors in 11638.17s (3:13:58) =
```

2025-01-14 09:31 UTC, vsedmik commented on pytest_fixtures/core/contenthosts.py
> +@pytest.fixture(params=[{'rhel_version': 6}])
Yes, I agree to drop it. It is unused and abandoned anyway.

2025-01-15 13:24 UTC, lhellebr commented on pytest_fixtures/component/provisioning_template.py
> +    if rhel_ver == 10:  # TODO: Remove once rhel10 is GA
Can't this block be structured better?
```
if rhel_ver == 10:
  ...
elif rhel_ver == 7:
  ...
else:
   
```

2025-01-15 14:32 UTC, damoore044 commented on pytest_fixtures/component/provisioning_template.py
> +    if rhel_ver == 10:  # TODO: Remove once rhel10 is GA
Yes can definitely clean this up a bit lol

2025-01-15 19:04 UTC, damoore044 commented on pytest_fixtures/component/provisioning_template.py
> +    if rhel_ver == 10:  # TODO: Remove once rhel10 is GA
@lhellebr see newest commit thank you

2025-01-15 19:06 UTC, damoore044 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_provisioningtemplate.py::TestProvisioningTemplate::test_positive_template_check_rex_snippet[rhel10-ipv4]
```

2025-01-15 19:11 UTC, damoore044 commented
pre-commit.ci autofix

2025-01-15 19:23 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9892
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/api/test_provisioningtemplate.py::TestProvisioningTemplate::test_positive_template_check_rex_snippet[rhel10-ipv4] --external-logging
Test Result : ================== 1 passed, 9 warnings in 689.56s (0:11:29) ===================
```

2025-01-16 16:58 UTC, damoore044 commented
```
trigger: test-robottelo
pytest tests/foreman/api/test_ansible.py::TestAnsibleREX::test_positive_ansible_job_on_multiple_host
```

2025-01-16 17:05 UTC, damoore044 commented
trigger: test-robottelo
pytest tests/foreman/api/test_ansible.py::TestAnsibleREX::test_positive_ansible_job_on_multiple_host

2025-01-16 17:27 UTC, damoore044 commented
trigger: test-robottelo
pytest tests/foreman/api/test_ansible.py -k 'test_positive_ansible_job_on_multiple_host'

2025-01-16 17:28 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_ansible.py::TestAnsibleREX::test_positive_ansible_job_on_multiple_host

2025-01-16 18:18 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9907
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api/test_ansible.py::TestAnsibleREX::test_positive_ansible_job_on_multiple_host --external-logging
Test Result : ================= 1 failed, 25 warnings in 2429.79s (0:40:29) ==================
```

2025-01-17 16:52 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api/test_ansible.py::TestAnsibleREX::test_positive_ansible_job_on_multiple_host

2025-01-22 17:45 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_host.py -k 'rhel10'

2025-01-22 17:51 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_http_proxy.py -k 'rhel10'

2025-01-22 18:20 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9959
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_http_proxy.py -k rhel10 --external-logging
Test Result : ========== 2 passed, 9 deselected, 132 warnings in 1379.42s (0:22:59) ==========
```

2025-01-22 18:47 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9958
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli/test_host.py -k rhel10 --external-logging
Test Result : ==== 1 passed, 96 deselected, 697 warnings, 6 errors in 3287.36s (0:54:47) =====
```

2025-01-24 09:57 UTC, vsedmik requested changes
Overall looks good to me, I've only put a couple of nits below to address.

Somewhat bigger question is the usage of `rhelX_contenthost`. There was a discussion at the JPL call this week about moving away from them to `rhel_contenthost` + param (to resolve the IPv6 hosts deploy issue). @JacobCallahan said he would raise a PR for that, which would cause a merge conflict for one of you.

I'd propose both of you to negotiate on the next steps so you don't double the work. Anyway we might like to avoid the `rhelX_contenthost`s in this PR to minimize the conflict.

2025-01-24 09:57 UTC, vsedmik commented on tests/foreman/ui/test_contenthost.py
> +            'distro': 'rhel10',
```suggestion
            'distro': CHOST_RHEL_VER,
```

2025-01-24 09:57 UTC, vsedmik commented on tests/foreman/ui/test_contenthost.py
> +            'distro': 'rhel10',
```suggestion
            'distro': CHOST_RHEL_VER,
```

2025-01-24 09:57 UTC, vsedmik commented on tests/foreman/ui/test_contenthost.py
> +            'distro': 'rhel10',
```suggestion
            'distro': CHOST_RHEL_VER,
```

2025-01-24 09:57 UTC, vsedmik commented on tests/foreman/ui/test_contenthost.py
> +        result = vm.execute('subscription-manager repos')
Looks like a forgotten debug line. Do we need it?

2025-01-24 09:57 UTC, vsedmik commented on tests/foreman/api/test_errata.py
> +    assert REAL_RHEL8_1_ERRATA_ID in [errata['errata_id'] for errata in erratum]'''
Was this "stringed out" intentionally?
I'd rather use `#` if you aimed to remark it out, or remove completely.

2025-02-17 14:40 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api -k 'rhel10'

2025-02-17 15:23 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/cli -k 'rhel10'

2025-02-17 16:24 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 10202
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api -k rhel10 --external-logging
Test Result : = 4 failed, 16 passed, 2331 deselected, 3197 warnings, 4 errors in 5829.75s (1:37:09) =
```

2025-02-17 18:05 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 10207
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/cli -k rhel10 --external-logging
Test Result : = 9 failed, 13 passed, 1941 deselected, 3696 warnings, 14 errors in 9151.61s (2:32:31) =
```

2025-02-17 20:13 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_errata.py::test_downgrading_package_shows_errata_from_library[rhel10-ipv4]

2025-02-17 20:37 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 10211
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/cli/test_errata.py::test_downgrading_package_shows_errata_from_library[rhel10-ipv4] --external-logging
Test Result : ================== 1 passed, 16 warnings in 915.21s (0:15:15) ==================
```

2025-02-17 20:41 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/api -k 'rhel10'

2025-02-17 22:34 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 10212
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/api -k rhel10 --external-logging
Test Result : == 2 failed, 22 passed, 2332 deselected, 4270 warnings in 6403.66s (1:46:43) ===
```

2025-02-17 22:40 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/cli -k 'rhel10'

2025-02-18 13:42 UTC, damoore044 commented
trigger: test-robottelo
pytest: tests/foreman/ui -k 'rhel10'

2025-02-18 15:43 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 10231
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui -k rhel10 --external-logging
Test Result : === 4 failed, 17 passed, 766 deselected, 2259 warnings in 6718.27s (1:51:58) ===
```

2025-02-18 16:25 UTC, vsedmik approved these changes
Looks good to me, just one question.

2025-02-18 16:25 UTC, vsedmik commented on robottelo/constants/__init__.py
> +DISTROS_SUPPORTED = ['rhel6', 'rhel7', 'rhel8', 'rhel9', 'rhel10']
Is `rhel6` still supported?

2025-02-18 16:29 UTC, jeremylenz commented on robottelo/constants/__init__.py
> +DISTROS_SUPPORTED = ['rhel6', 'rhel7', 'rhel8', 'rhel9', 'rhel10']
Nope! https://github.com/Katello/katello/blob/a739b7104bde511b2a77eead93c6207cc94943a2/app/models/katello/rhel_lifecycle_status.rb#L49

2025-02-18 16:41 UTC, chris1984 approved these changes

2025-02-18 17:53 UTC, Gauravtalreja1 commented on pytest_fixtures/component/provisioning_template.py
> -    rhel_xy = Version(constants.REPOS['kickstart'][repo_name]['version'])
This was changed for EL10 in PR https://github.com/SatelliteQE/robottelo/pull/17385, so I wonder if this was changed intentionally OR if this PR isn't rebased on mentioned PR correctly?

2025-02-18 18:36 UTC, JacobCallahan requested changes
just a couple of small things

2025-02-18 18:36 UTC, JacobCallahan commented on pytest_fixtures/component/provisioning_template.py
> +    )
In cases like these, normal if/elif/else blocks are the same number of lines and flow better.
```suggestion
    if rhel_ver == 10  # TODO: Remove beta repos once RHEL10 is GA
        rhel_xy = Version(constants.REPOS['kickstart'][f'rhel{rhel_ver}_bos_beta']['version'])
    elif rhel_ver == 7:
        rhel_xy = Version(constants.REPOS['kickstart'][f'rhel{rhel_ver}']['version'])
    else:
        rhel_xy = Version(constants.REPOS['kickstart'][f'rhel{rhel_ver}_bos']['version'])
```

2025-02-18 18:36 UTC, JacobCallahan commented on tests/foreman/api/test_capsulecontent.py
>          )
now that you're injecting the two additional lines (and additional condition), i'd recommend the same as earlier.

2025-02-18 18:50 UTC, damoore044 commented on pytest_fixtures/component/provisioning_template.py
> -    rhel_xy = Version(constants.REPOS['kickstart'][repo_name]['version'])
I'll rebase again and check that change is in thanks!

2025-02-18 18:53 UTC, damoore044 commented on tests/foreman/api/test_capsulecontent.py
> +    @pytest.mark.rhel_ver_match('N-0')
Yes just EL10, I could specify '10' for `rhel_ver_match` , but with `N-0` it will always pick the newest RHEL supported, and only that one.

2025-02-18 19:14 UTC, Gauravtalreja1 approved these changes

2025-02-18 19:37 UTC, JacobCallahan approved these changes

2025-02-18 19:37 UTC, merged