Add test checking needs publish banner on cv index page
SatelliteQE/robottelo pull request #17154
Opened 2024-12-12 06:41 UTC by sambible

### Problem Statement
Test supporting this Customer Issue: https://issues.redhat.com/browse/SAT-28271

### Solution
Adds a test validating this issue+

### Related Issues
Requires Airgun PR: https://github.com/SatelliteQE/airgun/pull/1653

2024-12-12 07:46 UTC, LadislavVasina1 commented
@sambible To which branches do you want this PR to be merged?

2024-12-12 10:33 UTC, jameerpathan111 requested changes

2024-12-12 10:33 UTC, jameerpathan111 commented on tests/foreman/ui/test_contentview.py
> +@pytest.mark.tier2
```suggestion
```
We don't use tier markers anymore.

2024-12-12 10:33 UTC, jameerpathan111 commented on tests/foreman/ui/test_contentview.py
> +        assert not result2
```suggestion
        assert session.contentview_new.check_publish_banner(cv.name)
        cv.publish()
        assert not session.contentview_new.check_publish_banner(cv.name)
```

2024-12-12 10:33 UTC, jameerpathan111 commented on tests/foreman/ui/test_contentview.py
> +
```suggestion
    
    :Verifies: SAT-28271
    
    :customerscenario: true
```

2024-12-19 09:58 UTC, vsedmik reviewed
Codewisely looks good, one question and PRT pending.

2024-12-19 09:58 UTC, vsedmik commented on tests/foreman/ui/test_contentview.py
> +        assert not result2
Shouldn't the logic be the opposite? The "no changes" warning displayed _after_ publish, not before?

```suggestion
        result = session.contentview_new.check_publish_banner(cv.name)
        assert not result
        cv.publish()
        result2 = session.contentview_new.check_publish_banner(cv.name)
        assert result2
```

2024-12-19 10:01 UTC, vsedmik commented
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k test_cv_publish_warning
airgun: 1653
```

2024-12-19 11:58 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9674
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_contentview.py -k test_cv_publish_warning --external-logging
Test Result : =========== 1 failed, 7 deselected, 17 warnings in 649.18s (0:10:49) ===========
```

2025-01-15 16:36 UTC, sambible commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_contentview.py -k test_cv_publish_warning
airgun: 1653

2025-01-15 16:55 UTC, Satellite-QE commented
**PRT Result**
```
Build Number: 9887
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_contentview.py -k test_cv_publish_warning --external-logging
Test Result : =========== 1 passed, 7 deselected, 17 warnings in 754.04s (0:12:34) ===========
```

2025-01-16 17:10 UTC, vsedmik approved these changes

2025-01-16 18:11 UTC, chris1984 approved these changes

2025-01-16 18:32 UTC, synkd approved these changes

2025-01-17 08:58 UTC, jameerpathan111 approved these changes

2025-01-17 08:59 UTC, merged