Fix long failing reporting API tests
SatelliteQE/robottelo pull request #17189
Opened 2024-12-17 11:37 UTC by LadislavVasina1

### Problem Statement
Some API reporting tests did not work in stream due to multi CV changes.

### Solution
This PR fixes these issues by creating a fixture that promotes CV that is used with LCE which is needed now.

### Related Issues
It is expected for the PRT to fail with an error related to the usage of `--force` option. 
see: (SAT-30043)

### PRT test Cases example
```
trigger: test-robottelo
pytest: pytest tests/foreman/api/test_reporttemplates.py -k "test_positive_applied_errata or test_positive_applied_errata_report_with_invalid_errata or test_positive_applied_errata_by_search"
```

2024-12-17 11:38 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: pytest tests/foreman/api/test_reporttemplates.py -k "test_positive_applied_errata or test_positive_applied_errata_report_with_invalid_errata or test_positive_applied_errata_by_search"
```

2024-12-17 12:15 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k "test_positive_applied_errata or test_positive_applied_errata_report_with_invalid_errata or test_positive_applied_errata_by_search"
```

2024-12-17 13:50 UTC, LadislavVasina1 commented
All tests failed with `You must use --force to set a value other than 'enabled'` as expected

2024-12-17 14:29 UTC, vsedmik approved these changes
Codewisely looks good to me.
We may need to wait until a fix PR for the `--force` issue is up and kill two flies with one stone (merge two PRs with one PRT).

2024-12-17 15:15 UTC, jeremylenz commented
> a fix PR for the `--force` issue is up

https://github.com/Katello/hammer-cli-katello/pull/979

sorry about that ;)

2024-12-17 16:16 UTC, vsedmik commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k "test_positive_applied_errata or test_positive_applied_errata_report_with_invalid_errata or test_positive_applied_errata_by_search"
Katello:
  hammer-cli-katello: 979
```

2024-12-20 03:40 UTC, vijaysawant approved these changes

2024-12-26 11:14 UTC, vijaysawant requested changes

2024-12-26 11:14 UTC, vijaysawant commented on tests/foreman/api/test_reporttemplates.py
> +    :return: activation_key, cv, function_lce, function_org
```suggestion
    This function scope fixture creates CV and publish / promote it to LCE. It aslo creates AK which is associate with LCE & CV.

    :return: AK, CV, LCE and Org
```

2024-12-26 11:15 UTC, vijaysawant commented on tests/foreman/api/test_reporttemplates.py
> +    :return: activation_key, cv, function_lce, function_org
I am suggesting some non blocking changes related to doc string.

2025-01-06 08:55 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k "test_positive_applied_errata or test_positive_applied_errata_report_with_invalid_errata or test_positive_applied_errata_by_search"
Katello:
  hammer-cli-katello: 979
```

2025-01-14 14:07 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k "test_positive_applied_errata or test_positive_applied_errata_report_with_invalid_errata or test_positive_applied_errata_by_search"
```

2025-01-14 19:30 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k "test_positive_applied_errata or test_positive_applied_errata_report_with_invalid_errata or test_positive_applied_errata_by_search"
```

2025-01-15 07:27 UTC, vijaysawant approved these changes
Very good work @LadislavVasina1  :clap:

2025-01-15 08:39 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k "test_positive_applied_errata or test_positive_applied_errata_report_with_invalid_errata or test_positive_applied_errata_by_search"
```

2025-01-15 08:55 UTC, pondrejk approved these changes

2025-01-15 09:22 UTC, LadislavVasina1 commented
```
trigger: test-robottelo
pytest: tests/foreman/api/test_reporttemplates.py -k "test_positive_applied_errata or test_positive_applied_errata_report_with_invalid_errata or test_positive_applied_errata_by_search"
```

2025-01-15 11:04 UTC, merged

2025-01-15 11:05 UTC, vsedmik commented
PRT 9873 passed, merging
```
11:35:23  ========= 9 passed, 33 deselected, 845 warnings in 3781.42s (1:03:01) ==========
```