Adding skip. BZ:1850934
SatelliteQE/robottelo pull request #7952
Opened 2020-08-26 06:51 UTC by akhil-jha

2020-08-26 07:45 UTC, omkarkhatavkar approved these changes
ACK

2020-08-26 08:27 UTC, pondrejk requested changes
Hi @akhil-jha can you add the BZ number also to docstrings? It is useful to have that reference when  skips are eventually removed.

2020-08-26 08:53 UTC, akhil-jha commented
> Hi @akhil-jha can you add the BZ number also to docstrings? It is useful to have that reference when skips are eventually removed.

Done.

2020-08-26 13:49 UTC, JacobCallahan commented
@akhil-jha can you update your commit description to describe why these are being skipped?

2020-08-27 08:12 UTC, akhil-jha commented
> @akhil-jha can you update your commit description to describe why these are being skipped?

Ah. My bad. I have updated it now.

2020-09-02 07:04 UTC, pondrejk approved these changes

2020-09-02 07:04 UTC, merged