[jyejare] Close Loop 2 - VMWare Bug (1679225) and Discovery Bug (1367549)
SatelliteQE/robottelo pull request #7995
Opened 2020-09-15 12:43 UTC by jyejare

## Automated:

- VMWare Bug (1679225)
- Discovery Bug (1367549)

2020-09-17 19:07 UTC, rplevka requested changes
I'd reconsider the need of manipulating of the backend `dhcp` service.
All you have to do is to define a new `Subnet` entity with the subset of the range.
The algorithm to fetch an unused ip will be restricted to this.

2021-01-26 15:30 UTC, JacobCallahan commented
@jyejare  can you revisit this PR when you get a chance? Thanks!

2021-02-01 11:55 UTC, omkarkhatavkar commented
Can one of the admins verify this patch?

2021-02-18 08:03 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +        """Provision a pxe-based discovered hosts
OOPs the copy paste error :)

2021-02-18 13:35 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +                assert int(provisioned_host.ip.split('.')[-1]) <= int(old_sub_to_4o)
@rplevka
1. Changing the range from subnet entity doesnt changes the range in dhcpd.conf
2. Discovered hosts during discovery gets the IP from Satellite server DHCP that dhcpd.conf
3. But While provisioning that host,  the IP is assigned from subnet entity range.

And thats we have to check here for the bug - 1367549.

2021-02-18 13:37 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +            f'.{old_sub_from_4o}', f'.{str(int(old_sub_to_4o)-9)}'
No worries, at least the static hosts(qe-sat69-rhel-tier3) right now we are using to run these tests has a big pool of IPs to not to fail this test ! :)

2021-02-18 13:44 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +                assert int(provisioned_host.ip.split('.')[-1]) <= int(old_sub_to_4o)
@rplevka Also these are the official steps to verify that bug from DEVs :)

2021-02-18 16:02 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +            f'.{old_sub_from_4o}', f'.{str(int(old_sub_to_4o)-9)}'
@rplevka Do you have any alternate for that btw ? I know we can find the current range and find the middle of it, but feels unnecessary complicating things.

2021-02-19 06:32 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +            f'.{old_sub_from_4o}', f'.{str(int(old_sub_to_4o)-9)}'
Modified the code to not to fail that way !

2021-02-19 16:15 UTC, jyejare commented
@rplevka Answered and fixed your comments. So please revisit this long pending PR @rplevka @JacobCallahan and lets get this in.

Sorry for taking long time to revisit.

2021-02-22 11:40 UTC, rplevka commented on tests/foreman/api/test_discoveredhost.py
> +                assert int(provisioned_host.ip.split('.')[-1]) <= int(old_sub_to_4o)
@jyejare that's what i'm talking about -
All you have to do is to provision a host using a default `dhcpd.conf` config,
then simply update the Subnet entity attributes to narrow the old range down (not touching the dhcpd.conf) and turn that discovered host into a managed Host using a satellite.
It should reflect the ip settings from the subnet entity (the ip of the created host should be different from the one assigned to discovered host by dhcpd)

2021-02-22 12:06 UTC, rplevka commented on tests/foreman/api/test_discoveredhost.py
> +            f'.{old_sub_from_4o}', f'.{str(int(old_sub_to_4o)-9)}'
@jyejare defining an `ipaddress` module object and manipulating it is actually way simpler,
but what I'd do would be to take the very last usable host ip from the old range and make the new range to only allow this single IP.
```
import ipaddress

hosts = [ h for h in ipaddress.ip_network('192.168.1.0/24')][1:-1]
new_range_from = new_range_to = hosts[:-1]
```

..something among those lines.

2021-02-22 12:36 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +                assert int(provisioned_host.ip.split('.')[-1]) <= int(old_sub_to_4o)
@rplevka Yeah ! Thats good idea by the way ! The only thing I have to care is that - the discovered IP should not be in the modified subnet range :)

Like that ! Lets me implement that way !

2021-02-22 12:41 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +            f'.{old_sub_from_4o}', f'.{str(int(old_sub_to_4o)-9)}'
@rplevka Yeah ! Good idea ! Looks like the ipaddress module is inbuilt python lib.

2021-02-22 12:43 UTC, rplevka commented on tests/foreman/api/test_discoveredhost.py
> +                assert int(provisioned_host.ip.split('.')[-1]) <= int(old_sub_to_4o)
yeah, good point. you can minimalize the chances by making the new range only 1-host wide + take it from the end of the old range.

2021-02-22 12:47 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +                assert int(provisioned_host.ip.split('.')[-1]) <= int(old_sub_to_4o)
@rplevka Yeah ! Thats the plan !

2021-02-23 14:15 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +            f'.{old_sub_from_4o}', f'.{str(int(old_sub_to_4o)-9)}'
Not using this module, doesnt need to make it that complex. Just using `discovered_host + 2` way to make it quite easier.

2021-02-23 14:15 UTC, jyejare commented on tests/foreman/api/test_discoveredhost.py
> +                assert int(provisioned_host.ip.split('.')[-1]) <= int(old_sub_to_4o)
Done !

2021-02-23 14:16 UTC, jyejare commented
@rplevka Revisit , I have encountered all your comments :)

2021-03-01 16:39 UTC, rplevka approved these changes

2021-03-03 13:54 UTC, jyejare commented
@SatelliteQE/tier-2-reviewers Ping. Long pending PR, please review !

2021-03-05 16:58 UTC, merged