Robottelo Pytest Package Update to 5.4.3
SatelliteQE/robottelo pull request #8031
Opened 2020-10-02 18:10 UTC by ColeHiggins2

Updating pytest from 4.6.3 to 5.4.3.

After running several tests in the API, CLI, and UI, It does not look like any of the failures are related to the pytest changes. Please review the standalone Jenkins jobs for automation results. Jobs are 2010, 2013, and 2027 in Jenkins. 

If you think anything else should be updated, Please comment below

2020-10-05 12:07 UTC, lpramuk commented
https://docs.pytest.org/en/stable/changelog.html#pytest-5-1-0-2019-08-15

- []  pytest.raises and pytest.warns no longer support strings as the second argument.

2020-10-05 12:09 UTC, lpramuk requested changes
Add more changes to be able to update

2020-10-05 15:46 UTC, mshriver approved these changes

2020-10-06 23:54 UTC, lpramuk approved these changes

2020-10-12 16:17 UTC, merged

2020-10-12 16:22 UTC, jyejare commented
@JacobCallahan @mshriver @mirekdlugosz There are many such PRs opened by py-up bot. To merge those PRs I was looking for there use in tests and helpers in robottelo. Else we should make some mechanism to auto-test the related tests wrt to those python modules. Do you anything already exists like that e.g genealogist. 

Thoughts ?

2020-10-12 18:11 UTC, mshriver commented
I'm not aware of existing tools to do such a targeted search/test for python packages. A general pull request tester (planned) could be combined with identification of package changes in the PR, and tests using that package. With the layers of function calls its certainly not a trivial problem to solve.