Py38 update
SatelliteQE/robottelo pull request #8077
Opened 2020-10-21 21:21 UTC by mshriver

Should be merged after @JacobCallahan PR #7924 which introduces py3.8.

This enforces it, as well as uses pyupgrade tool to apply python 3.8 language standards automatically via pre-commit.

Initial f-string conversions were done by pyupgrade. It doesn't convert all uses of `.format()`

2020-10-22 17:57 UTC, JacobCallahan requested changes

2020-10-22 17:57 UTC, JacobCallahan commented on robottelo/api/utils.py
>                  }
This looks pretty ugly still, and could still look better as an f-string. Perhaps something like this
```python
os_ver = os.split(' ')[1].split('.')
query={'search': 'family="Redhat" AND major="{os_ver[0]}" AND minor="{os_ver[1]}")'}
```

2020-10-22 17:57 UTC, JacobCallahan commented on robottelo/api/utils.py
> +                    "found: '{}'".format(repo_backend_id, req.json().get('error'))
```suggestion
                    f"Pulp task with repo_id {repo_backend_id} errored or not "
                    f"found: '{req.json().get('error')}'"
```

2020-10-22 17:57 UTC, JacobCallahan commented on robottelo/cli/base.py
>                  )
```suggestion
                f'Command "{cls.command_base} {cls.command_sub}" finished with return_code '
                f'{response.return_code}\nstderr contains following message:\n{response.stderr}' 
```

2020-10-27 18:20 UTC, JacobCallahan requested changes
Just a few things. :)

2020-10-27 18:20 UTC, JacobCallahan commented on robottelo/libvirt_discovery.py
> +        self.guest_name = 'mac{}'.format(self.mac.replace(':', ""))
```suggestion
        self.guest_name = f"""mac{self.mac.replace(':', "")}"""
```

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_activationkey.py
> +        ak_name = '{}_{}'.format(ak_name_like, gen_string('alpha'))
you know the thing

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_capsule.py
> +                {'url': 'http://{}:{}'.format(gen_string('alpha', 6), gen_string('numeric', 4))}
```suggestion
                {'url': f'http://{gen_string("alpha", 6)}:{gen_string("numeric", 4)}'}
```

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_capsule_installer.py
>                  )
```suggestion
                f"wget -nv -P /usr/bin http://{settings.artifacts_server}/pub/katello-remove"
```

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_capsule_installer.py
> +                '--certs-tar {}'.format(capsule_vm.hostname, cert_file_path)
i think this reads better
```suggestion
                f'--foreman-proxy-fqdn {capsule_vm.hostname} '
                f'--certs-tar {cert_file_path}'
```

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_classparameters.py
> +        cls.env = Environment.list({'search': 'content_view="{}"'.format(cv['name'])})[0]
```suggestion
        cls.env = Environment.list({'search': f"""content_view="{cv['name']}""""})[0]
```

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_classparameters.py
> +                'search': 'puppetclass="{}"'.format(cls.puppet_class['name']),
could follow the same format as above

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_classparameters.py
> +        env = Environment.list({'search': 'content_view="{}"'.format(cv['name'])})[0]
and this

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_computeresource_libvirt.py
> +            'description': '<html>{}</html>'.format(gen_string('alpha')),
can bring these in

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_computeresource_libvirt.py
> +                'name': 'cr {}'.format(gen_string(str_type='alpha')),
```suggestion
                'name': f'cr {gen_string(str_type="alpha")}',
```

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_computeresource_rhev.py
> +                'name': 'cr {}'.format(gen_string(str_type='alpha')),
more of the same throughout this file

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_contentview.py
> +                lce='{}/{}'.format(env['name'], content_view['name']),
```suggestion
                lce=f'{env["name"]}/{content_view["name"]}',
```

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_contentview.py
> +                lce='{}/{}'.format(env['name'], content_view['name']),
ditto

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_docker.py
> +                    'docker pull {}'.format(repo['published-at']),
these are throughout this file
```suggestion
                    f'docker pull {repo["published-at"]}',
```

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_domain.py
> +            'name': 'white spaces {}'.format(gen_string(str_type='utf8')),
and this file

2020-10-27 18:20 UTC, JacobCallahan commented on tests/foreman/cli/test_environment.py
> +        cls.env = Environment.list({'search': 'content_view="{}"'.format(cls.cv['name'])})[0]
you guessed it!

2020-10-28 00:36 UTC, mshriver commented
@JacobCallahan there by my search (after having done more conversions manually) over 600 remaining uses of `.format()` in robottelo.

I don't really intend to completely remove the use of `.format()`, it still has its purpose and appropriate places to use it.

Thoughts on my limiting the amount of time I'm spending directly updating all of these, and leaving their conversion to future contributions? People will be refactoring their tests, and defining new fixtures, and along the way we can continue to remove uses of .format where f-strings make more sense.

Going to push what I've updated just searching directly for .format, not necessarily addressing the specific comments you've made here to places where pyupgrade did not automatically change to f-string.

2020-10-28 00:55 UTC, JacobCallahan commented
@mshriver it sounds like it is time to update and further expand SatQE's code standards. I can take some examples from this pull request for that as well. We can also raise this updated standard to the rest of the reviewers and then the larger team.

I'm fine with the limited scope of your changes in this pull request. Will look more at it tomorrow morning.

2020-10-28 12:36 UTC, mshriver commented
@JacobCallahan great - I did include an update to the docs where string formatting is mentioned, stating to use f-string instead of .format.

2020-10-28 14:06 UTC, mshriver commented on robottelo/cli/base.py
> +            f'--output={output_format}' if output_format else '',
I need to roll this back, this broke the unit tests. Functionality isn't the same, as argument keys are getting included when they should not.

2020-10-30 20:48 UTC, JacobCallahan approved these changes

2020-11-02 15:08 UTC, pondrejk approved these changes
It's too huge to make any guarantees, though I don't know how else to do it and now is probably the best time

2020-11-02 15:18 UTC, merged