[6.8.z] pytest conversion - api.test_discoveredhost
SatelliteQE/robottelo pull request #8305
Opened 2021-01-25 13:10 UTC by rplevka

backport of
https://github.com/SatelliteQE/robottelo/pull/8112

2021-01-26 17:19 UTC, mshriver commented on tests/foreman/api/test_discoveredhost.py
> +            f'\\[I\\|app\\|[a-z0-9]+\\] Started POST '
This `f` prefix isn't necessary but is completely inconsequential.

2021-01-26 17:20 UTC, mshriver approved these changes

2021-01-26 18:53 UTC, JacobCallahan requested changes

2021-01-26 18:53 UTC, JacobCallahan commented on tests/foreman/api/test_discoveredhost.py
> +                logger.warning(f'Failed to decode char using utf-8 charset, replacing by "?"')
no f-string needed here, unless you were wanting to add in the offending line.

2021-01-26 18:53 UTC, JacobCallahan commented on tests/foreman/api/test_discoveredhost.py
> +        (f"DHCPACK on [0-9.]+ to {host.mac}", "DHCPACK"),
single quotes, please

2021-01-26 18:53 UTC, JacobCallahan commented on tests/foreman/api/test_discoveredhost.py
> +        "sed -ie 's/TIMEOUT [[:digit:]]\\+/TIMEOUT 1/g' " "/var/lib/tftpboot/pxelinux.cfg/default"
```suggestion
        "sed -ie 's/TIMEOUT [[:digit:]]\\+/TIMEOUT 1/g' /var/lib/tftpboot/pxelinux.cfg/default"
```

2021-01-26 18:53 UTC, JacobCallahan commented on tests/foreman/api/test_discoveredhost.py
> +        query={'search': 'name == {}'.format(result['name'])}
can do an f-string here

2021-01-26 18:53 UTC, JacobCallahan commented on tests/foreman/api/test_discoveredhost.py
> +                (f"DHCPACK on [0-9.]+ to {pxe_host.mac}", "DHCPACK"),
single quotes here

2021-01-26 18:53 UTC, JacobCallahan commented on tests/foreman/api/test_discoveredhost.py
> +                    (f"DHCPACK on [0-9.]+ to {pxe_host[0].mac}", "DHCPACK"),
single quotes here

2021-01-28 00:54 UTC, rplevka commented
I believe the travis failure is unrelated

2021-02-01 11:55 UTC, omkarkhatavkar commented
Can one of the admins verify this patch?

2021-02-09 15:22 UTC, mshriver commented on robottelo/libvirt_discovery.py
> +            command_args.append('--network={vm_nw_type}:{vm_network}')
Missing an f-string here.

2021-02-09 15:22 UTC, mshriver commented on robottelo/libvirt_discovery.py
> +            '--type={vm_nw_type}',
missing f-strings for these variables.

2021-02-09 15:23 UTC, mshriver commented on tests/foreman/api/test_discoveredhost.py
> +    groups = re.search('DHCPACK on (\\d.+) to', dhcp_fdi.out)
I'd recommend using `r''` string prefix here to avoid warnings on escape characters.

2021-02-09 15:24 UTC, mshriver commented on tests/foreman/api/test_discoveredhost.py
> +    groups = re.search('DHCPACK on (\\d.+) to', dhcp_fdi.out)
Applies to all regex expressions in this PR.

2021-02-09 15:26 UTC, mshriver commented on tests/foreman/api/test_discoveredhost.py
> +        discoman_role = entities.Role().search(query={'search': 'name="Discovery Manager"'})[0]
`discoman`, my favorite super-hero.

2021-02-09 15:29 UTC, mshriver commented on tests/foreman/api/test_discoveredhost.py
> +@pytest.mark.stubbed
Duplicate markers

2021-02-09 15:31 UTC, mshriver requested changes
Couple f-strings to resolve, backport looks good otherwise. I think most/all of @JacobCallahan comments have been addressed.

2021-02-09 16:46 UTC, JacobCallahan commented on tests/foreman/api/test_discoveredhost.py
> +    host_name = 'mac{}'.format(discovered_host['mac'].replace(':', ''))
```suggestion
    host_name = f'mac{discovered_host["mac"].replace(":", "")}'
```

2021-04-01 06:05 UTC, closed without merging