remove or merge redundant or non needed tests
SatelliteQE/robottelo pull request #8306
Opened 2021-01-25 17:12 UTC by rplevka

first step in the refactoring of CLI discovered tests.

2021-01-25 19:14 UTC, rplevka commented on tests/foreman/cli/test_discoveredhost.py
> -    def test_positive_pxe_less_with_dhcp_unattended(self):
this is already contained as a step in
`test_positive_provision_pxeless_bios_syslinux`

2021-01-25 19:15 UTC, rplevka commented on tests/foreman/cli/test_discoveredhost.py
> -    def test_positive_provision_pxeless_uefi_grub(self):
UEFI-GRUB is an unsupported combo

2021-01-25 19:16 UTC, rplevka commented on tests/foreman/cli/test_discoveredhost.py
> -    def test_positive_provision_pxeless_uefi_grub2(self):
Bootloader doesn't matter in the pxeless scenario, as a `kexec` is used

2021-01-25 19:17 UTC, rplevka commented on tests/foreman/cli/test_discoveredhost.py
> -    def test_positive_provision_pxeless_uefi_grub2_secureboot(self):
Secureboot is not supported, also the firwmare doesn't matter in pxeless scenario

2021-01-25 19:17 UTC, rplevka commented on tests/foreman/cli/test_discoveredhost.py
> -    def test_positive_provision_pxe_host_with_uefi_grub(self):
not supported scenario

2021-01-25 19:18 UTC, rplevka commented on tests/foreman/cli/test_discoveredhost.py
> -    def test_positive_provision_pxe_host_with_uefi_grub2_sb(self):
secure boot not supported

2021-01-25 19:18 UTC, rplevka commented on tests/foreman/cli/test_discoveredhost.py
> -    def test_positive_delete_pxeless_host(self):
There's no difference between removing a pxeless host or a pxe-based host - it's a discovered host entity in foreman.

2021-01-25 19:19 UTC, rplevka commented on tests/foreman/cli/test_discoveredhost.py
> -    def test_positive_list_discovered_host(self):
we already do this as a part of
`test_positive_provision_pxeless_bios_syslinux`

2021-01-25 19:21 UTC, rplevka commented on tests/foreman/cli/test_discoveredhost.py
>      def test_positive_assign_discovery_manager_role(self):
i'll most probably use non-admin user with discovery roles on all tests after refactoring. I might parameterize the tests to use each role.

2021-01-25 19:42 UTC, rplevka commented on tests/foreman/cli/test_discoveredhost.py
> -    def test_positive_custom_facts_pxeless_discovery(self):
there's no difference in listing facts of pxe-based or pxeless discovered host, merging both to a single test:
`test_positive_list_facts`
where both builtin and custom facts are to be checked.

2021-01-25 21:29 UTC, lvrtelov approved these changes
LGTM. Thanks for adding those comments, Roman!

2021-01-26 13:17 UTC, tstrych approved these changes
ACK, please look at code review failiure

```
tests/foreman/cli/test_discoveredhost.py
========================================

DiscoveredTestCase::test_positive_list_facts:511
------------------------------------------------

* Docstring should have at least caseautomation, casecomponent, caseimportance, caselevel, id, requirement, testtype, upstream token(s)
* Docstring has RST parsing issues. RST parser messages:

  * Unexpected indentation.

      :id: 2c65925c-05d9-4f6d-b1b7-1fa1492c95a8
      :Setup:
    >     1. Provisioning should be configured
          2. Host is already discovered
    ```

2021-01-26 16:55 UTC, JacobCallahan requested changes
Awesome! Just need to resolve the failures @tstrych noted above.

2021-01-26 19:52 UTC, swadeley approved these changes
ACK

2021-01-26 19:52 UTC, swadeley commented on tests/foreman/cli/test_discoveredhost.py
> +        destroy one or more discovered host as well view, create_new, edit,
```suggestion
        destroy one or more discovered hosts as well as view, create_new, edit,
```

2021-01-26 19:52 UTC, swadeley commented on tests/foreman/cli/test_discoveredhost.py
> +        one or more discovered host
```suggestion
        one or more discovered hosts
```

2021-01-27 06:06 UTC, JacobCallahan approved these changes

2021-01-27 06:06 UTC, merged