filter tests moved to pytest
SatelliteQE/robottelo pull request #8378
Opened 2021-02-24 09:35 UTC by pondrejk

```
pytest tests/foreman/api/test_filter.py 
================================================= test session starts =================================================

tests/foreman/api/test_filter.py ...                                                                            [100%]

=========================================== 3 passed, 12 warnings in 13.71s ===========================================
```
```

pytest tests/foreman/cli/test_filter.py 
================================================= test session starts =================================================                                                                                                 

tests/foreman/cli/test_filter.py ........                                                                       [100%]

============================================ 8 passed in 290.12s (0:04:50) ============================================

```

2021-02-24 12:06 UTC, swadeley approved these changes
ACK

2021-02-24 12:06 UTC, swadeley commented on tests/foreman/cli/test_filter.py
> +    """Search for provisioning template permissions. Set ``cls.ct_perms``."""
```suggestion
    """Search for provisioning template permissions. Set ``ct_perms``."""
```

2021-02-25 10:44 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/api/test_filter.py

2021-02-25 17:58 UTC, mshriver commented on tests/foreman/cli/test_filter.py
> +    return role
Bit of code golf, but a good practice to follow - there's no need to assign `role` here, just ` return make_role()`

2021-02-25 17:59 UTC, mshriver requested changes
One small change concerning an assertion pattern of two lists, otherwise looks great.

2021-03-05 20:56 UTC, mshriver approved these changes

2021-03-05 20:56 UTC, merged