cli test subnet u2p
SatelliteQE/robottelo pull request #8410
Opened 2021-03-09 17:29 UTC by tstrych

`================== 21 passed, 18 skipped in 327.16s (0:05:27) ==================`

please @rdrazny look at the tests, 
Important thing is that I added at the begining `:CaseImportance: Medium` 
Because we require this information for the tests.  
If you want to change it please let me know.

2021-03-09 17:30 UTC, tstrych commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_subnet.py

2021-03-12 03:41 UTC, JacobCallahan requested changes

2021-03-12 03:41 UTC, JacobCallahan commented on tests/foreman/cli/test_subnet.py
> +@pytest.mark.parametrize('options', **parametrized(invalid_missing_attributes()))
Make sure parameterized tests have their docstrings updated to indicate they are.

2021-03-12 10:48 UTC, jyejare requested changes
ACK pending parameterized tokens.

2021-03-12 10:48 UTC, jyejare commented on tests/foreman/cli/test_subnet.py
> +    :expectedresults: Subnet is not created
Add parametrized token in docstring.

2021-03-12 10:48 UTC, jyejare commented on tests/foreman/cli/test_subnet.py
> +    :expectedresults: Subnet is not created
Add parametrized token in docstring.

2021-03-12 10:48 UTC, jyejare commented on tests/foreman/cli/test_subnet.py
> +    :id: ab60372e-cef7-4495-bd66-68e7dbece475
Add parametrized token in docstring.

2021-03-12 10:48 UTC, jyejare commented on tests/foreman/cli/test_subnet.py
> +    :id: d0a857b4-be10-4b5d-86d4-43cf99c11619
Add parametrized token in docstring.

2021-03-12 10:48 UTC, jyejare commented on tests/foreman/cli/test_subnet.py
> +    :steps:
```suggestion
    :steps: Check if 'set-parameter' option is present in subnet command.
```

2021-03-12 10:48 UTC, jyejare commented on tests/foreman/cli/test_subnet.py
> +        1. Check if 'set-parameter' option is present in
Need not to enumerate if we have only one step.

2021-03-12 17:13 UTC, tstrych commented
thanks for reviews ;)

2021-03-12 17:15 UTC, tstrych commented on tests/foreman/cli/test_subnet.py
> +    domains_amount = random.randint(3, 5)
sure :+1: 
these tests are not mine, so don't want to changes in the logic of the tests, but this is really small change which brings some speedup, will implement.

2021-03-17 02:44 UTC, JacobCallahan commented
trigger: test-robottelo
pytest: -n 3 --collect-only tests/foreman/cli/test_subnet.py

2021-03-17 14:17 UTC, jyejare approved these changes
ACK!

2021-03-17 14:17 UTC, jyejare commented on tests/foreman/cli/test_subnet.py
> +    :steps: 1. Check if 'set-parameter' option is present in subnet command.
Even remove 1 there, keep it plain.

Non blocking comment.

2021-03-18 10:41 UTC, tstrych commented
trigger: test-robottelo
pytest: --collect-only tests/foreman/cli/test_subnet.py

2021-03-18 11:06 UTC, tstrych commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_subnet.py

2021-03-18 11:16 UTC, tstrych commented
Okay, now I can see the pr-tester is disabled. and run 68 failed at the beginning at command parsing. 
Precisely ` mapping values are not allowed here` 

So problem not connected.

Result locally:
```
pytest --collect-only tests/foreman/cli/test_subnet.py
============================================================================ test session starts ============================================================================
collected 39 items                                                                                                                                                          

<Package cli>
  <Module test_subnet.py>
    <Function test_positive_CRUD>
    <Function test_negative_create_with_attributes[0]>
    <Function test_negative_create_with_attributes[1]>
    <Function test_negative_create_with_attributes[2]>
    <Function test_negative_create_with_attributes[3]>
    <Function test_negative_create_with_attributes[4]>
    <Function test_negative_create_with_attributes[5]>
    <Function test_negative_create_with_address_pool[0]>
    <Function test_negative_create_with_address_pool[1]>
    <Function test_negative_create_with_address_pool[2]>
    <Function test_negative_create_with_address_pool[3]>
    <Function test_negative_update_attributes[0]>
    <Function test_negative_update_attributes[1]>
    <Function test_negative_update_attributes[2]>
    <Function test_negative_update_attributes[3]>
    <Function test_negative_update_attributes[4]>
    <Function test_negative_update_attributes[5]>
    <Function test_negative_update_address_pool[0]>
    <Function test_negative_update_address_pool[1]>
    <Function test_negative_update_address_pool[2]>
    <Function test_negative_update_address_pool[3]>
    <Function test_positive_set_parameter_option_presence>
    <Function test_positive_create_with_parameter>
    <Function test_positive_create_with_parameter_and_multiple_values>
    <Function test_positive_create_with_parameter_and_multiple_names>
    <Function test_negative_create_with_parameter_and_invalid_separator>
    <Function test_positive_create_with_multiple_parameters>
    <Function test_negative_create_with_duplicated_parameters>
    <Function test_positive_inherit_subnet_parmeters_in_host>
    <Function test_negative_inherit_subnet_parmeters_in_host>
    <Function test_positive_subnet_parameters_override_from_host>
    <Function test_positive_subnet_parameters_override_impact_on_subnet>
    <Function test_positive_update_parameter>
    <Function test_negative_update_parameter>
    <Function test_positive_update_subnet_parameter_host_impact>
    <Function test_positive_delete_subnet_parameter>
    <Function test_positive_delete_multiple_parameters>
    <Function test_positive_delete_subnet_parameter_host_impact>
    <Function test_positive_delete_subnet_parameter_overrided_host_impact>

======================================================================== 39 tests collected in 0.05s ========================================================================
```

2021-03-18 13:15 UTC, tstrych commented
trigger: test-robottelo
pytest: tests/foreman/cli/test_subnet.py

2021-03-18 20:26 UTC, mshriver approved these changes

2021-03-18 20:26 UTC, merged