Refactor test_api_endtoend and endtoend/utils for pytest
SatelliteQE/robottelo pull request #8430
Opened 2021-03-17 18:50 UTC by mshriver

Running these locally still, not quite ready yet.

2021-03-18 04:51 UTC, JacobCallahan requested changes

2021-03-18 04:51 UTC, JacobCallahan commented on tests/foreman/endtoend/test_api_endtoend.py
> +        assert content_host.content_facet_attributes['lifecycle_environment_id'], le1.id
This assertion should be ==

2021-03-18 04:51 UTC, JacobCallahan commented on tests/foreman/endtoend/test_api_endtoend.py
> +        assert content_host.content_facet_attributes['content_view_id'], content_view.id
This assertion should be ==

2021-03-18 12:15 UTC, mshriver commented on tests/foreman/endtoend/test_api_endtoend.py
> +        assert content_host.content_facet_attributes['content_view_id'], content_view.id
Good catches, thanks!

2021-03-18 14:12 UTC, mshriver commented
trigger: test-robottelo
pytest: tests/foreman/endtoend/test_api_endtoend.py

2021-03-19 17:06 UTC, JacobCallahan commented
Looks like you had a failure in the prt

2021-03-19 17:59 UTC, mshriver commented
@JacobCallahan yep, check out the description - its a failure on the master branch, some API endpoints have changed in recent snaps.

2021-03-19 18:11 UTC, JacobCallahan approved these changes

2021-04-01 10:49 UTC, rplevka approved these changes

2021-04-01 12:40 UTC, merged