Refactor upgrades/test_remoteexecution for pytest
SatelliteQE/robottelo pull request #8436
Opened 2021-03-18 22:28 UTC by mshriver

Wasn't able to run the tests locally, going to ask the component owner for some help.

2021-03-20 04:33 UTC, JacobCallahan requested changes

2021-03-20 04:33 UTC, JacobCallahan commented on tests/upgrades/test_remoteexecution.py
> +                'search_query': f"name = {client.hostname}",
I am now the 'single quotes' guy 🙃

2021-03-20 04:34 UTC, JacobCallahan commented
@lhellebr can you run these changes locally and add the results in here please?

2021-03-22 12:29 UTC, mshriver commented
trigger: test-robottelo
pytest: -m pre_upgrade tests/upgrades/test_remoteexecution.py

2021-03-22 14:42 UTC, JacobCallahan approved these changes

2021-03-29 05:23 UTC, devendra104 approved these changes
ACK

2021-03-29 13:23 UTC, merged