[Dynaconf] Compute Resource Libvirt
SatelliteQE/robottelo pull request #8437
Opened 2021-03-19 07:33 UTC by akhil-jha

GitLab MR: 
```
$ pytest -k test_positive_create_with_name tests/foreman/api/test_computeresource_libvirt.py
==================================================================== test session starts =====================================================================
platform linux -- Python 3.8.7, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: robottelo, configfile: pyproject.toml
plugins: reportportal-5.0.8, forked-1.3.0, xdist-2.2.1, mock-3.5.1, ibutsu-1.14.1, services-2.2.1
collected 67 items / 60 deselected / 7 selected                                                                                                              

tests/foreman/api/test_computeresource_libvirt.py .......                                                                                              [100%]

============================================================= 7 passed, 60 deselected in 34.48s ==============================================================

```

2021-03-24 12:38 UTC, omkarkhatavkar requested changes

2021-03-24 12:38 UTC, omkarkhatavkar commented on conf/libvirt.yaml.template
> +  LIBVIRT_HOSTNAME: libvirt.example.com
if these values are going to get updated based on git lab PR, we should comment those attributes

2021-03-24 12:38 UTC, omkarkhatavkar commented on conf/libvirt.yaml.template
> +  LIBVIRT_IMAGE_DIR: /path/to/libvirt/images
we can pass actual libvirt directory path here nothing I sense as sensitive

2021-03-26 13:27 UTC, omkarkhatavkar approved these changes
ACK

2021-03-26 13:34 UTC, JacobCallahan requested changes

2021-03-26 13:34 UTC, JacobCallahan commented on conf/libvirt.yaml.template
> +  # foreman-discovery-image-3.0.5-3_unattended_down_el6.iso
looks like you're missing an empty line at the end of this file

2021-03-26 14:21 UTC, JacobCallahan approved these changes

2021-03-26 14:21 UTC, merged