Rewrite RHEV CLI test to Pytest
SatelliteQE/robottelo pull request #8457
Opened 2021-03-23 15:32 UTC by lhellebr

```
$ pytest tests/foreman/cli/test_computeresource_rhev.py --verbose -n2
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.7, pytest-6.2.2, py-1.9.0, pluggy-0.13.1 -- /home/lhellebr/git/robottelo/venv3/bin/python3
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/lhellebr/git/robottelo, configfile: pyproject.toml
plugins: xdist-2.2.1, ibutsu-1.14.1, services-2.2.1, mock-3.5.1, cov-2.10.0, reportportal-5.0.8, forked-1.2.0
[gw0] linux Python 3.8.7 cwd: /home/lhellebr/git/robottelo
[gw1] linux Python 3.8.7 cwd: /home/lhellebr/git/robottelo
[gw1] Python 3.8.7 (default, Jan 20 2021, 00:00:00)  -- [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
[gw0] Python 3.8.7 (default, Jan 20 2021, 00:00:00)  -- [GCC 10.2.1 20201125 (Red Hat 10.2.1-9)]
gw0 [10] / gw1 [10]
scheduling tests via LoadScheduling

tests/foreman/cli/test_computeresource_rhev.py::test_positive_rhev_info 
tests/foreman/cli/test_computeresource_rhev.py::test_positive_create_rhev_with_valid_name 
[gw1] [ 10%] PASSED tests/foreman/cli/test_computeresource_rhev.py::test_positive_create_rhev_with_valid_name 
[gw0] [ 20%] PASSED tests/foreman/cli/test_computeresource_rhev.py::test_positive_rhev_info 
tests/foreman/cli/test_computeresource_rhev.py::test_positive_delete_by_name 
tests/foreman/cli/test_computeresource_rhev.py::test_positive_delete_by_id 
[gw0] [ 30%] PASSED tests/foreman/cli/test_computeresource_rhev.py::test_positive_delete_by_id 
[gw1] [ 40%] PASSED tests/foreman/cli/test_computeresource_rhev.py::test_positive_delete_by_name 
tests/foreman/cli/test_computeresource_rhev.py::test_negative_create_rhev_with_url 
tests/foreman/cli/test_computeresource_rhev.py::test_negative_create_with_same_name 
[gw1] [ 50%] PASSED tests/foreman/cli/test_computeresource_rhev.py::test_negative_create_rhev_with_url 
tests/foreman/cli/test_computeresource_rhev.py::test_positive_update_name 
[gw0] [ 60%] PASSED tests/foreman/cli/test_computeresource_rhev.py::test_negative_create_with_same_name 
tests/foreman/cli/test_computeresource_rhev.py::test_positive_add_image_rhev_with_name 
[gw1] [ 70%] PASSED tests/foreman/cli/test_computeresource_rhev.py::test_positive_update_name 
tests/foreman/cli/test_computeresource_rhev.py::test_negative_add_image_rhev_with_invalid_uuid 
[gw1] [ 80%] SKIPPED tests/foreman/cli/test_computeresource_rhev.py::test_negative_add_image_rhev_with_invalid_uuid 
[gw0] [ 90%] PASSED tests/foreman/cli/test_computeresource_rhev.py::test_positive_add_image_rhev_with_name 
tests/foreman/cli/test_computeresource_rhev.py::test_negative_add_image_rhev_with_invalid_name 
[gw0] [100%] PASSED tests/foreman/cli/test_computeresource_rhev.py::test_negative_add_image_rhev_with_invalid_name 

====================================================================================== warnings summary ======================================================================================
tests/foreman/cli/test_computeresource_rhev.py:92
tests/foreman/cli/test_computeresource_rhev.py:92
  /home/lhellebr/git/robottelo/tests/foreman/cli/test_computeresource_rhev.py:92: PytestUnknownMarkWarning: Unknown pytest.mark.tier - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.tier

-- Docs: https://docs.pytest.org/en/stable/warnings.html
==================================================================== 9 passed, 1 skipped, 2 warnings in 110.32s (0:01:50) ====================================================================
2021-03-23 16:14:47 - py.warnings - WARNING - /home/lhellebr/git/robottelo/venv3/lib/python3.8/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Mapping, MutableMapping

2021-03-23 16:14:47 - py.warnings - WARNING - /home/lhellebr/git/robottelo/venv3/lib/python3.8/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Mapping, MutableMapping

2021-03-23 16:14:47 - py.warnings - WARNING - /home/lhellebr/git/robottelo/venv3/lib/python3.8/site-packages/cinderclient/client.py:23: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp

WARNING:robottelo.config:Legacy Robottelo settings configure() failed, most likely required configuration option is not provided. Continuing for the sake of unit tests
WARNING:robottelo.config:Dynaconf validation failed, continuing for the sake of unit tests
```

2021-03-23 18:45 UTC, JacobCallahan requested changes

2021-03-23 18:45 UTC, JacobCallahan commented on tests/foreman/cli/test_computeresource_rhev.py
> +            'name': 'cr {}'.format(gen_string(str_type='alpha')),
```suggestion
            f'name': 'cr {gen_string(str_type="alpha")}',
```

2021-03-23 18:45 UTC, JacobCallahan commented on tests/foreman/cli/test_computeresource_rhev.py
> +            'name': 'img {}'.format(gen_string(str_type='alpha')),
```suggestion
            f'name': 'img {gen_string(str_type="alpha")}',
```

2021-03-23 18:45 UTC, JacobCallahan commented on tests/foreman/cli/test_computeresource_rhev.py
> +                'uuid': 'invalidimguuid {}'.format(gen_string(str_type='alpha')),
```suggestion
                f'name': 'img {gen_string(str_type="alpha")}',
                f'uuid': 'invalidimguuid {gen_string(str_type="alpha")}',
```

2021-03-23 18:45 UTC, JacobCallahan commented on tests/foreman/cli/test_computeresource_rhev.py
> +                'name': 'img {}'.format(gen_string(str_type='alphanumeric', length=256)),
```suggestion
                f'name': 'img {gen_string(str_type="alphanumeric", length=256)}',
```

2021-03-24 11:42 UTC, lhellebr commented
```
$ pytest tests/foreman/cli/test_computeresource_rhev.py 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.7, pytest-6.2.2, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/lhellebr/git/robottelo, configfile: pyproject.toml
plugins: xdist-2.2.1, ibutsu-1.14.1, services-2.2.1, mock-3.5.1, cov-2.10.0, reportportal-5.0.8, forked-1.2.0
collected 11 items / 1 deselected / 10 selected                                                                                                                                              

tests/foreman/cli/test_computeresource_rhev.py ........s.                                                                                                                              [100%]

====================================================================================== warnings summary ======================================================================================
tests/foreman/cli/test_computeresource_rhev.py:92
  /home/lhellebr/git/robottelo/tests/foreman/cli/test_computeresource_rhev.py:92: PytestUnknownMarkWarning: Unknown pytest.mark.tier - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.tier

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================================= 9 passed, 1 skipped, 1 deselected, 1 warning in 165.27s (0:02:45) ==============================================================

```

2021-03-24 12:41 UTC, JacobCallahan approved these changes

2021-03-24 13:15 UTC, omkarkhatavkar approved these changes
ACK

2021-03-24 13:15 UTC, merged