Convert VMWare CLI test to pytest
SatelliteQE/robottelo pull request #8460
Opened 2021-03-23 17:40 UTC by lhellebr

2021-03-23 18:53 UTC, JacobCallahan requested changes

2021-03-23 18:53 UTC, JacobCallahan commented on tests/foreman/cli/test_computeresource_vmware.py
> +    vmware.loc = make_location()
you could inherit the module-level org and location fixtures

2021-03-24 10:03 UTC, omkarkhatavkar commented
@lhellebr Can you please upload the test result?

2021-03-24 13:53 UTC, lhellebr commented
```
$ pytest tests/foreman/cli/test_computeresource_vmware.py 
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.7, pytest-6.2.2, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/lhellebr/git/robottelo, configfile: pyproject.toml
plugins: xdist-2.2.1, ibutsu-1.14.1, services-2.2.1, mock-3.5.1, cov-2.10.0, reportportal-5.0.8, forked-1.2.0
collected 4 items                                                                                                                                                                            

tests/foreman/cli/test_computeresource_vmware.py ....                                                                                                                                  [100%]

====================================================================================== warnings summary ======================================================================================
tests/foreman/cli/test_computeresource_vmware.py::test_positive_create_with_server
tests/foreman/cli/test_computeresource_vmware.py::test_positive_create_with_server
tests/foreman/cli/test_computeresource_vmware.py::test_positive_create_with_server
tests/foreman/cli/test_computeresource_vmware.py::test_positive_create_with_server
  /home/lhellebr/git/robottelo/venv3/lib/python3.8/site-packages/urllib3/connectionpool.py:846: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    warnings.warn((

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================== 4 passed, 4 warnings in 60.39s (0:01:00) ==========================================================================
```

2021-03-24 14:27 UTC, pondrejk approved these changes

2021-03-24 16:57 UTC, JacobCallahan approved these changes

2021-03-24 16:58 UTC, merged