Use DOCKER_UPSTREAM_NAME
SatelliteQE/robottelo pull request #8473
Opened 2021-03-29 15:35 UTC by swadeley

rather than hardcoded repo name
    Change to mirror.gcr.io

Not cherry pick, but same as https://github.com/SatelliteQE/robottelo/pull/8318

2021-03-29 15:48 UTC, JacobCallahan requested changes
Since this no longer is the docker registry, it would be more appropriate to change the names of the constants to be something like "CONTAINER_REGISTRY_HUB" etc...

2021-03-29 15:52 UTC, swadeley commented
robottelo]$ pytest --show-capture=no tests/foreman/cli/test_repository.py
============================ test session starts ===============================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_1/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, cov-2.11.1, mock-3.5.1, ibutsu-1.14.1, reportportal-5.0.8, xdist-2.2.1
collecting ... 2021-03-29 15:37:38 - conftest - DEBUG - Collected 95 test cases
collected 95 items                                                                                                                                                                                

tests/foreman/cli/test_repository.py ................

2021-03-29 16:17 UTC, swadeley commented
> Since this no longer is the docker registry

I have changed it for master first:
https://github.com/SatelliteQE/robottelo/pull/8474

2021-03-31 21:22 UTC, mshriver approved these changes

2021-03-31 21:22 UTC, mshriver commented
I don't think the update to the names is necessary to backport into 6.8.z, given its very limited future scope.

2021-03-31 21:22 UTC, merged

2021-04-01 06:57 UTC, swadeley commented
> I don't think the update to the names is necessary to backport into 6.8.z, given its very limited future scope.

OK, ACK