tests/robottelo/test_func_shared.py fix and pytest conversion
SatelliteQE/robottelo pull request #8493
Opened 2021-04-08 11:20 UTC by ppochop

There was an issue with generating different values where ensuring the values were different was done by `self.assertNotEqual`. This could randomly cause the tests to fail. While the chances of that are generally minimal (e.g. 1/10,000). However, in `test_simple_shared_counter` the odds of that happening are 1/100 which is not that low and it actually failed in one of my PRs. This was fixed by simply removing the assertion statements. To ensure the values are different, `while` statements were added. This may not be necessary because again, the odds of that happening are low but I made a judgement call and put it in.

Because the file was not in pytest, I also converted it. Since this is my first attempt at pytest conversion, please don't spare any comments/suggestions :) 

```
pytest tests/robottelo/test_func_shared.py
collected 15 items                                                             

tests/robottelo/test_func_shared.py ...............                      [100%]

============================= 15 passed in 15.13s ==============================
```

2021-04-08 11:22 UTC, omkarkhatavkar commented
Can one of the admins verify this patch?

2021-04-13 16:10 UTC, mshriver approved these changes

2021-04-14 15:23 UTC, JacobCallahan requested changes

2021-04-14 15:23 UTC, JacobCallahan commented on tests/robottelo/test_func_shared.py
> +    @pytest.fixture(scope="class")
Please switch these to single-quote strings.
It looks like there are multiple instances of this throughout the file as well.

2021-04-15 10:48 UTC, lhellebr approved these changes
LGTM

2021-04-15 11:22 UTC, merged