[VM->Broker] Conversion of ui/test_remoteexecution
SatelliteQE/robottelo pull request #8527
Opened 2021-04-19 11:35 UTC by akhil-jha

Convert the test in ui/test_remoteexecution that previously used the VirtualMachine class.
```
$ pytest -k test_positive_run_job_template_multiple_hosts_by_ip tests/foreman/ui/test_remoteexecution.py 
==================================================================== test session starts =====================================================================
platform linux -- Python 3.8.7, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/satelliteqe/robottelo, configfile: pyproject.toml
plugins: reportportal-5.0.8, forked-1.3.0, xdist-2.2.1, cov-2.11.1, mock-3.5.1, ibutsu-1.14.1, services-2.2.1
collected 4 items / 7 deselected                                                                                                                             

tests/foreman/ui/test_remoteexecution.py .                                                                                                             [100%]

======================================================== 1 passed, 7 deselected in 577.11s (0:08:37) =========================================================
```

2021-04-19 11:36 UTC, akhil-jha commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_remoteexecution.py -k test_positive_run_job_template_multiple_hosts_by_ip

2021-04-19 19:23 UTC, JacobCallahan requested changes

2021-04-20 11:26 UTC, pondrejk approved these changes
ack pending Jake's comment

2021-05-05 09:27 UTC, akhil-jha commented
```
$ pytest -k test_positive_run_job_template_multiple_hosts_by_ip tests/foreman/ui/test_remoteexecution.py 
========================================================================================================== test session starts ===========================================================================================================
platform linux -- Python 3.8.7, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/akjha/satelliteqe/robottelo, configfile: pyproject.toml
plugins: reportportal-5.0.8, forked-1.3.0, xdist-2.2.1, cov-2.11.1, mock-3.6.0, ibutsu-1.14.1, services-2.2.1
collected 4 items / 7 deselected                                                                                                                                                                                                         

tests/foreman/ui/test_remoteexecution.py .                                                                                                                                                                                         [100%]

============================================================================================== 1 passed, 7 deselected in 592.52s (0:09:52) ===============================================================================================
```

2021-05-05 09:28 UTC, akhil-jha commented on tests/foreman/ui/test_remoteexecution.py
>          for client in vm_clients:
Changes made. 
Sorry for the late action.

2021-05-05 14:21 UTC, JacobCallahan approved these changes

2021-05-05 14:22 UTC, merged