closed loop, check org api
SatelliteQE/robottelo pull request #8531
Opened 2021-04-20 11:10 UTC by pondrejk

automation for https://bugzilla.redhat.com/show_bug.cgi?id=1828549
Checks for manifest cert exposed in organization api endpoint

```
pytest tests/foreman/api/test_organization.py -k test_negative_check_org_endpoint
                                                     
tests/foreman/api/test_organization.py .                                                                      [100%]

=================================== 1 passed, 42 deselected, 2 warnings in 7.12s ====================================

```

2021-04-21 08:49 UTC, swadeley commented
Hello @pondrejk 

Does this test require a manifest to be installed?

I did not see one installed under `class TestOrganization:`

Thank you

2021-04-21 10:00 UTC, pondrejk commented
@swadeley good point, checking

2021-04-22 04:09 UTC, JacobCallahan requested changes

2021-04-22 13:23 UTC, pondrejk commented
Added an organization with manifest

2021-04-22 13:26 UTC, pondrejk commented on tests/foreman/api/test_organization.py
> +        assert 'BEGIN RSA PRIVATE KEY' not in orgstring
Yes, there was a particular key, but checking just a subsection wouldn't catch cert re-appearing elsewhere, that's why I check the whole output

2021-04-22 14:27 UTC, swadeley approved these changes
ACK

2021-04-22 17:46 UTC, JacobCallahan approved these changes

2021-04-22 17:46 UTC, merged