Add manual BZ test coverage
SatelliteQE/robottelo pull request #8557
Opened 2021-04-29 20:24 UTC by tpapaioa

This PR adds some manual/stubbed tests for BZ coverage.
```
<Package cli>
  <Module test_hostgroup.py>
    <Function test_positive_nested_hostgroup_info>
<Package ui>
  <Module test_hostgroup.py>
    <Function test_positive_create_new_host>
  <Module test_repository.py>
    <Function test_positive_discover_module_stream_repo_via_existing_product>
    <Function test_positive_upload_resigned_rpm>
    <Function test_positive_remove_srpm_change_checksum>
```

2021-04-29 20:34 UTC, JacobCallahan requested changes
Since these are stubs, can you put some test steps in the metadata?

2021-05-05 13:49 UTC, mshriver approved these changes

2021-05-05 13:49 UTC, mshriver commented
@tpapaioa changes look good, need to fix the formatting though for testimony tokens.

2021-05-05 15:11 UTC, JacobCallahan approved these changes

2021-05-06 15:18 UTC, merged