cert expiration test-case with katello-cert-check
SatelliteQE/robottelo pull request #8597
Opened 2021-05-10 15:10 UTC by omkarkhatavkar

### Test Result

```
Testing started at 8:30 PM ...
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --path /home/okhatavk/okhatavk/Satellite/robottelo/tests/foreman/sys/test_katello_certs_check.py -- -k test_negative_check_expiration_of_certificate
Launching py.test with arguments -k test_negative_check_expiration_of_certificate /home/okhatavk/okhatavk/Satellite/robottelo/tests/foreman/sys/test_katello_certs_check.py in /home/okhatavk/Satellite/robottelo

============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/okhatavk/okhatavk/Satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, cov-2.10.1, xdist-2.2.1, reportportal-5.0.8, mock-3.5.1, forked-1.3.0, ibutsu-1.14.1, picked-0.4.6collected 14 items / 13 deselected / 1 selected

../../okhatavk/Satellite/robottelo/tests/foreman/sys/test_katello_certs_check.py  [100%] 
```

2021-05-10 15:37 UTC, JacobCallahan requested changes

2021-05-10 15:37 UTC, JacobCallahan commented on tests/foreman/sys/test_katello_certs_check.py
> +        assert result.return_code == 0, 'Failed revert the time setting'
```suggestion
        assert result.return_code == 0, 'Failed to revert the time setting'
```

2021-05-10 15:37 UTC, JacobCallahan commented on tests/foreman/sys/test_katello_certs_check.py
> +    def update_system_time(self):
can you provide a docstring explaining what/why this fixture is used for?

2021-05-10 15:37 UTC, JacobCallahan commented on tests/foreman/sys/test_katello_certs_check.py
> +        checks = result.stdout.split("\n\n")
```suggestion
        checks = result.stdout.split('\n\n')
```

2021-05-10 16:45 UTC, JacobCallahan approved these changes

2021-05-12 05:52 UTC, jameerpathan111 approved these changes
Ack

2021-05-12 07:00 UTC, swadeley approved these changes
ACK

2021-05-12 07:01 UTC, merged