Content Credential changes for 6.10
SatelliteQE/robottelo pull request #8650
Opened 2021-05-27 09:10 UTC by swadeley

:CaseComponent: ContentCredentials

Hello

In 6.9
```
hammer repository update --help
--gpg-key[-id]           Set the current gpg key context for the request. Name/Id can be used
```

In 6.10, hammer repository command can no longer use a gpg-key name, only ID:
```
hammer repository update --help
<snip>
--gpg-key-id GPG_KEY_ID        Id of the gpg key that will be assigned to the new repository
```

2021-06-03 16:56 UTC, ColeHiggins2 commented
Will this affect other tests in the test_repository.py file or is this simply a backend change? @swadeley

2021-06-03 17:50 UTC, swadeley commented
> Will this affect other tests in the test_repository.py file or is this simply a backend change? @swadeley

Any test that uses --gpg-key <name> will be affected.

I think these files also needs an update:
 `tests/robottelo/test_hammer.py`
`tests/foreman/data/hammer_commands.json`

2021-06-18 13:07 UTC, JacobCallahan commented
@swadeley any update on this?

2021-06-21 10:55 UTC, swadeley commented
> @swadeley any update on this?

HI, I have just rebased. I will make another PR for the other files mentioned above mainly because I would the git commits to be separate.

Thank you

2021-06-21 14:59 UTC, JacobCallahan approved these changes

2021-06-22 14:00 UTC, latran requested changes
Looks good! It is possible to add test result?

2021-06-22 14:32 UTC, swadeley commented
> > @swadeley any update on this?
> 
> HI, I have just rebased. I will make another PR for the other files mentioned above mainly because I would the git commits to be separate. There is a script to fix update those files[1], so that is another reason why it should not be in this PR
> 
> Thank you
> 
> [1] https://github.com/SatelliteQE/robottelo/blob/master/scripts/hammer_command_tree.py

https://github.com/SatelliteQE/robottelo/pull/8712

2021-06-22 14:41 UTC, swadeley commented
> Looks good! It is possible to add test result?

test running

2021-06-22 15:39 UTC, swadeley commented
robottelo]$ git checkout content_credential_changes_for_6_10
Switched to branch 'content_credential_changes_for_6_10'
robottelo]$ pytest --show-capture=no tests/foreman/cli/test_content_credentials.py 
============================ test session starts ===================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/sjw/sat6/robottelo, configfile: pyproject.toml
plugins: xdist-2.3.0, mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-2.12.1, reportportal-5.0.8
collected 88 items                                                                                                                                                                                

tests/foreman/cli/test_content_credentials.py ........................................................................................                                                      [100%]

============================ 88 passed, 4 warnings in 2886.37s (0:48:06) ==============================

2021-06-22 19:27 UTC, latran approved these changes
ACK

2021-06-22 19:53 UTC, merged