VMBroker conversion rex in upgrades
SatelliteQE/robottelo pull request #8657
Opened 2021-05-31 09:56 UTC by pondrejk

Needs review from upgrade specialists :) Also I wasn't sure how to do the vm cleanup postupgrade

2021-05-31 10:45 UTC, jyejare requested changes
ACK pending comments.

2021-05-31 10:45 UTC, jyejare commented on tests/upgrades/test_remoteexecution.py
> +        client = VMBroker(nick='rhel7', host_classes={'host': ContentHost})
Instead, you should use the existing function level fixture :
https://github.com/SatelliteQE/robottelo/blob/master/pytest_fixtures/broker.py#L47

2021-05-31 10:45 UTC, jyejare commented on tests/upgrades/test_remoteexecution.py
> +        client = VMBroker(nick='rhel7', host_classes={'host': ContentHost})
Instead, you should use the existing function level fixture :
https://github.com/SatelliteQE/robottelo/blob/master/pytest_fixtures/broker.py#L47

2021-05-31 11:54 UTC, jyejare commented on tests/upgrades/test_remoteexecution.py
> +        client = rhel7_contenthost
You can directly use it, you need not initialise the `client` variable for it.

Below line will change to:
```
rhel7_contenthost.install_capsule_katello_ca(capsule=self.proxy_name)
```
Same others.

2021-06-01 08:18 UTC, jyejare commented
trigger: test-robottelo
pytest: -m pre_upgrade tests/upgrades/test_remoteexecution.py

2021-06-01 20:40 UTC, mshriver approved these changes
The test failures in PRT are well outside the scope of what you're doing here.

Your conversion to using VMBroker content hosts is clean.

2021-06-01 20:41 UTC, merged