adding tmp directory
SatelliteQE/robottelo pull request #8660
Opened 2021-05-31 15:46 UTC by akhil-jha

I encountered this when my capsule installation in the PR #8659  failed in PRT 127 with error `failed on setup with "FileNotFoundError: [Errno 2] No such file or directory:` The missing directory is `robottelo/tmp`. When the capsule installation failed, according to [this](https://github.com/SatelliteQE/robottelo/blob/3dd2a277701ac46467b9e97279c43db1081d5489/robottelo/hosts.py#L504) , the capsule.log should be copied over to the base testing machine.

2021-05-31 18:14 UTC, JacobCallahan requested changes
Let's hold on this and see if there is a better way.

2021-06-01 15:27 UTC, mshriver commented
@JacobCallahan Shouldn't this be resolved by `broker.session.sftp_read` calling `Path.mkdir` before trying to write?

2021-06-01 15:27 UTC, mshriver requested changes
The framework should handle writing this file whether or not the file or the target directory exists.

2021-06-01 15:57 UTC, JacobCallahan commented
@mshriver that is indeed where this should be handled. I can update the existing broker PR to account for this.
If that solution is agreeable to everyone else, then this PR can be closed.

2021-06-03 04:23 UTC, akhil-jha commented
> @mshriver that is indeed where this should be handled. I can update the existing broker PR to account for this.
> If that solution is agreeable to everyone else, then this PR can be closed.

I think that should be okay. 
Closing this PR.

2021-06-03 04:23 UTC, closed without merging

2021-06-03 12:39 UTC, JacobCallahan commented
This is solved by the addition of these lines in Broker's session class.
https://github.com/SatelliteQE/broker/pull/109/files#diff-6e88e617cde4e6aa876445eaaa4845b26cee35f289eb83c21cbbde2b103b44b0R74