adding the stub tests for global registration feature 6.10
SatelliteQE/robottelo pull request #8729
Opened 2021-06-25 13:09 UTC by omkarkhatavkar

2021-06-28 14:52 UTC, synkd requested changes

2021-06-28 14:52 UTC, synkd commented on tests/foreman/ui/test_host.py
> +    :expectedresults: Some of the fields in the form should be populated based on host-group
Which values in the form will be populated based on the host group? Can you list them in `:expectedresults:`?

2021-06-28 14:52 UTC, synkd commented on tests/foreman/ui/test_host.py
> +    """Host registration form should be get populate automatically based on the host-group
```suggestion
    """Host registration form should be populated automatically based on the host group
```

2021-06-28 14:52 UTC, synkd commented on tests/foreman/ui/test_host.py
> +    should be restricted for the any other api calls.
```suggestion
    should be restricted for any other api calls.
```

2021-06-28 14:52 UTC, synkd commented on tests/foreman/ui/test_host.py
> +    :expectedresults: global registration token should be restricted any api calls
```suggestion
    :expectedresults: global registration token should be restricted for any api calls
```

2021-06-29 14:31 UTC, latran requested changes

2021-06-29 14:31 UTC, latran commented on tests/foreman/ui/test_host.py
> +    get re-registered with out any error.
```suggestion
    get re-registered without any error.
```

2021-06-29 14:32 UTC, latran reviewed
If this stays as manual in the future, I think adding test steps would help, but I'll leave that choice up to you.

2021-07-02 07:35 UTC, devendra104 approved these changes
ACK

2021-07-02 18:20 UTC, JacobCallahan approved these changes

2021-07-02 18:21 UTC, merged