[WIP] Update test ui test_contenthost to use REX
SatelliteQE/robottelo pull request #8817
Opened 2021-08-02 18:57 UTC by swadeley

Hello

Updating more tests in  /ui/test_contenthost.py  to use REX

I need to wait for this bugzilla to be resolved before I can test this file:
[Bug 1983043 - undefined method `prune_known_hosts!` when executing a remote job](https://bugzilla.redhat.com/show_bug.cgi?id=1983043)

2021-08-08 03:14 UTC, JacobCallahan commented
@swadeley I see that the first bug has been verified and the second is modified. Could you still have this in and skip on the status of the second bug?

2021-08-09 08:51 UTC, swadeley commented
> @swadeley I see that the first bug has been verified and the second is modified. Could you still have this in and skip on the status of the second bug?

In theory, but if the fix will be in the next snap, I will think about that.

2021-08-20 09:58 UTC, swadeley commented
Hello

this PR depends on:
[ Add REX support to chost and errata tests #607 ](https://github.com/SatelliteQE/airgun/pull/607)

2021-08-20 13:15 UTC, swadeley commented
Hello

some test that now use REX

robottelo]$ date && pytest tests/foreman/ui/test_contenthost.py -k test_positive_end_to_end_bulk_update -k package
Fri 20 Aug 12:27:57 BST 2021
============================== test session starts ====================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_1/robottelo, configfile: pyproject.toml
plugins: xdist-2.3.0, mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-2.12.1, reportportal-5.0.8
collected 28 items / 22 deselected / 6 selected                                                                                                                                                   

tests/foreman/ui/test_contenthost.py ......                                                                                                                                                 [100%]


========================== 6 passed, 22 deselected, 5 warnings in 4108.49s (1:08:28) ========================

2021-08-25 14:06 UTC, swadeley commented
Hello

with [ Add REX support to chost and errata tests #607 ](https://github.com/SatelliteQE/airgun/pull/607),

all tests except two non REX tests in `tests/foreman/ui/test_contenthost.py` pass.

This one because of [Bug 1995228 - Applying errata from an Erratum's Content Host tab fails ](https://bugzilla.redhat.com/show_bug.cgi?id=1995228):
`tests/foreman/ui/test_contenthost.py::test_positive_end_to_end`

and this one because of unrelated change:
`tests/foreman/ui/test_contenthost.py::test_content_access_after_stopped_foreman`

2021-08-25 14:55 UTC, mshriver commented on tests/foreman/cli/test_satellitesync.py-test_new_positive_export_custom_product
> +"""Test class for InterSatellite Sync
It looks like you may have duplicated a test module here?

2021-08-25 14:58 UTC, mshriver requested changes
Changes to test_contenthost look good, but it looks like there is some extraneous content in the PR.

2021-09-01 14:50 UTC, mshriver commented on tests/foreman/ui/test_contenthost.py
> +        if not is_open('BZ:1995228'):
@swadeley I think you mean robottelo-runner (PRT), not PIT here (Product integration testing).

PRT can indeed run UI tests, it has the same selenium config as our core CI pipelines.

2021-09-01 15:07 UTC, mshriver approved these changes

2021-09-01 15:39 UTC, swadeley commented on tests/foreman/ui/test_contenthost.py
> +        if not is_open('BZ:1995228'):
PRT = Pull Request Tester , thanks for the info

2021-09-02 20:20 UTC, swadeley commented
Needs another rebase

2021-09-02 20:35 UTC, swadeley commented
trigger: test-robottelo
pytest:  tests/foreman/ui/test_contenthost.py

2021-09-08 14:14 UTC, latran approved these changes
ack

2021-09-08 15:03 UTC, merged

2021-09-09 07:42 UTC, swadeley commented
Thank you