updated the certs tests to use host class
SatelliteQE/robottelo pull request #8884
Opened 2021-08-25 13:47 UTC by omkarkhatavkar

2021-08-25 13:49 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/sys/test_katello_certs_check.py

2021-08-25 14:55 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/sys/test_katello_certs_check.py

2021-08-25 16:19 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/sys/test_katello_certs_check.py

2021-08-30 18:23 UTC, JacobCallahan commented on tests/foreman/sys/test_katello_certs_check.py
> +        capsule = AttrDict({'hostname': 'capsule.example.com'})
haha no, this works

2021-08-30 19:46 UTC, JacobCallahan requested changes
small changes

2021-08-30 19:46 UTC, JacobCallahan commented on robottelo/hosts.py
> +        self.execute('bash certs.sh')
Can you either check the exit code or some state on the system to validate whether this method did in fact do everything it was support to before returning?

2021-08-30 19:46 UTC, JacobCallahan commented on tests/foreman/sys/test_katello_certs_check.py
> +            assert result.status == 0, 'Hammer Ping fail'
```suggestion
            assert result.status == 0, f'Hammer Ping failed:\n{result.stderr}'
```

2021-08-31 13:22 UTC, JacobCallahan approved these changes
ACK, thanks!

2021-09-01 13:41 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/sys/test_katello_certs_check.py

2021-09-01 14:11 UTC, swadeley approved these changes
ACK

2021-09-01 15:33 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/sys/test_katello_certs_check.py

2021-09-01 17:46 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/sys/test_katello_certs_check.py

2021-09-02 03:31 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/sys/test_katello_certs_check.py

2021-09-02 07:09 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/sys/test_katello_certs_check.py

2021-09-02 10:52 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/sys/test_katello_certs_check.py

2021-09-02 12:22 UTC, mshriver approved these changes

2021-09-02 12:23 UTC, merged