Scenarios class docstrings
SatelliteQE/robottelo pull request #8991
Opened 2021-09-23 11:00 UTC by jyejare

Moved all Upgrade Scenario docstrings to a class level so that we can push one scenario as a one test case to polarion using https://github.com/jyejare/betelgeuse/pull/1 .

2021-09-27 20:53 UTC, mshriver requested changes
Per our discussions, I thought we were not going down this path of collecting and applying test metadata of the class separately for some paths.

2021-09-28 08:35 UTC, jyejare commented
@mshriver I raised this PR after discussion with @vijay8451 , he understands and agrees with the strategy to push the upgrade scenarios from class docstrings. 

This decision is purely made on POC basis since Polarion is used purely as a test management tool and hence we are good with this strategy. @vijay8451 was one of the contributors in upgrade scenarios so he understands the architecture of upgrade scenarios. If management later sees any issues with class strategy, we will go back to the per def basis strategy. But I dont see that will ever happen.

2021-12-20 20:11 UTC, latran commented
@JacobCallahan can you provide feedback for this based on Mike's comment?

2021-12-20 20:22 UTC, JacobCallahan commented
@latran @mshriver this is something @jyejare and I talked about a while ago and will be revisited at a later time.

2021-12-21 08:51 UTC, jyejare commented
@latran yeah, for time being we would like to keep this in draft until we decide that #9226 isn't doing the job well :)

2022-06-14 13:57 UTC, JacobCallahan commented
Closing this for now, but this can be revisited if needed in the future.

2022-06-14 13:57 UTC, closed without merging