6.9.z
SatelliteQE/robottelo pull request #8992
Opened 2021-09-23 18:05 UTC by jyejare

CherryPicked `Content Host` recent additions and updates to 6.9.z from master.

2021-09-27 21:30 UTC, mshriver commented on pytest_fixtures/content_hosts.py
> +@pytest.fixture
I believe this decorator needs removed, as it was the cause of a scope mismatch exception.

2021-09-27 21:31 UTC, mshriver requested changes
Missing a small change that went into master as a follow-up fix to scope mismatch.

2021-09-29 07:29 UTC, jyejare commented
@mshriver Cherry-picked that as well! Thanks for notifying it !

2021-09-29 12:46 UTC, mshriver approved these changes

2021-10-04 19:40 UTC, merged