Add test for negative api ping
SatelliteQE/robottelo pull request #9106
Opened 2021-10-29 20:04 UTC by Gauravtalreja1

**Description:**
- Add negative API ping to test to cover BZ-1835122.
- Move API ping tests from endtoend to api/test_ping.py to keep alike CLI tests.
- Update pytest marks for cli/test_ping.py.

**Test Results:**
```
$ pytest -qv --disable-warnings tests/foreman/api/test_ping.py 
=============================================================== test session starts ===============================================================
platform linux -- Python 3.8.2, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/gtalreja/sat_workspace/robottelo, configfile: pyproject.toml
plugins: xdist-2.4.0, services-2.2.1, forked-1.3.0, reportportal-5.0.8, mock-3.6.1, ibutsu-1.16, cov-3.0.0
collected 2 items                                                                                                                                 

tests/foreman/api/test_ping.py ..                                                                                                           [100%]

========================================================= 2 passed, 4 warnings in 53.10s ==========================================================
```
```
$ pytest -qv --disable-warnings tests/foreman/cli/test_ping.py 
=============================================================== test session starts ===============================================================
platform linux -- Python 3.8.2, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/gtalreja/sat_workspace/robottelo, configfile: pyproject.toml
plugins: xdist-2.4.0, services-2.2.1, forked-1.3.0, reportportal-5.0.8, mock-3.6.1, ibutsu-1.16, cov-3.0.0
collected 2 items                                                                                                                                 

tests/foreman/cli/test_ping.py ..                                                                                                           [100%]

========================================================= 2 passed, 3 warnings in 52.60s ==========================================================
```
Signed-off-by: Gaurav Talreja <gtalreja@redhat.com>

2021-11-01 11:32 UTC, pondrejk requested changes

2021-11-01 11:32 UTC, pondrejk commented on tests/foreman/api/test_ping.py
> +def test_negative_ping_fail_status(default_sat):
we should mark this test as destructive as it stops a service

2021-11-01 11:32 UTC, pondrejk commented on tests/foreman/api/test_ping.py
> +    assert response['status'] == 'FAIL'
should we assert more specifically on which services failed in addition to the overall status

2021-11-01 11:32 UTC, pondrejk commented on tests/foreman/api/test_ping.py
> +    """
Id say we should check all services are up when we start testing

2021-12-09 07:00 UTC, devendra104 commented
@Gauravtalreja1 Converted the PR to draft state, Change the state once it gets ready for review.

2022-03-01 20:55 UTC, latran commented
@Gauravtalreja1 any updates on this?

2022-03-08 20:25 UTC, JacobCallahan commented
bump

2022-03-09 07:31 UTC, Gauravtalreja1 commented
Mistakenly deleted this branch locally, will restore and have plenty of things in todo, will continue this soon

2022-07-15 21:30 UTC, Gauravtalreja1 commented
trigger: test-robottelo
pytest: tests/foreman/destructive/test_ping.py

2022-07-18 08:47 UTC, swadeley approved these changes
ACK

2022-07-18 09:26 UTC, omkarkhatavkar commented on tests/foreman/destructive/test_ping.py
> +    yield module_target_sat
no need to yield satellite here, you can just yield and use `module_target_sat` in the test function.

2022-07-20 16:46 UTC, Gauravtalreja1 commented on tests/foreman/destructive/test_ping.py
> +    result = tomcat_service_teardown.execute("hammer ping")
I kept this name by referring to the existing sys fixture `foreman_service_teardown`, closing this thread as non-blocking

2022-07-21 10:24 UTC, omkarkhatavkar approved these changes

2022-07-21 10:24 UTC, merged