DRAFT RHcloud insights rake commands
SatelliteQE/robottelo pull request #9127
Opened 2021-11-08 15:19 UTC by spusateri

Passing locally, however I think the assertions can be added upon and improved. Would checking whether a remediation is present be outside the scope of this test?

2021-11-15 10:42 UTC, jameerpathan111 commented
@spusateri can you resolve the conflicts? My pr is merged now.

2021-11-29 06:52 UTC, jameerpathan111 commented on tests/foreman/cli/test_rhcloud_inventory.py
```suggestion
:CaseAutomation: Automated
```

2021-11-29 07:59 UTC, jameerpathan111 commented on tests/foreman/cli/test_rhcloud_inventory.py
> +    assert result.status == 0
Can you add assertion for `Synchronized Insights hosts hits data` in `result.stdout`

2021-11-29 08:00 UTC, jameerpathan111 commented on tests/foreman/cli/test_rhcloud_inventory.py
> +def test_positive_inventory_recommendation_sync(organization_ak_setup, rhcloud_sat_host):
```suggestion

@pytest.mark.tier3
def test_positive_inventory_recommendation_sync(
    set_rh_cloud_token,
    organization_ak_setup,
    rhcloud_registered_hosts,
    rhcloud_sat_host,
):
```

2021-12-08 16:45 UTC, Gauravtalreja1 commented on tests/foreman/cli/test_rhcloud_inventory.py
> +# @pytest.mark.stubbed
This should be removed, instead of a comment.

2021-12-20 20:22 UTC, latran requested changes
Pending changes from other's suggestion and a test result.

2022-02-21 21:06 UTC, latran commented
@jameerpathan111 can you take over this PR?

2022-03-02 20:23 UTC, Griffin-Sullivan commented
Looks like this was already done in https://github.com/SatelliteQE/robottelo/pull/9330. We should go ahead and close this out.

2022-03-02 20:29 UTC, closed without merging