6.9.z fix user end to end
SatelliteQE/robottelo pull request #9138
Opened 2021-11-10 14:20 UTC by synkd

This PR backports https://github.com/SatelliteQE/robottelo/pull/9134 to the 6.9.z branch.

2021-11-10 15:44 UTC, rplevka requested changes
You might want to switch the target branch to `6.9.z` instead of `master`

2021-11-10 15:47 UTC, synkd commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_user.py::test_positive_end_to_end

2021-11-10 15:48 UTC, rplevka approved these changes

2021-11-11 17:30 UTC, ogajduse approved these changes

2021-11-11 17:30 UTC, merged