added tests to search products on any org
SatelliteQE/robottelo pull request #9211
Opened 2021-12-01 20:01 UTC by ColeHiggins2

When trying to access the products page and "Any Organization" is selected, Users should see a landing page that asks them to select an Org. 

Currently, there are no views in airgun that allow us to see this. This is the current workaround.

2021-12-01 21:10 UTC, JacobCallahan requested changes

2021-12-01 21:10 UTC, JacobCallahan commented on tests/foreman/ui/test_repository.py
> +    when Any Organization is selected
```suggestion
    :expectedresults: UI asks to select an Organization on products page
        when Any Organization is selected
```

2022-01-04 10:06 UTC, swadeley commented on tests/foreman/ui/test_repository.py
> +        4. Assert that user must select and Organization
```suggestion
        4. Assert that user must select an Organization
```

2022-02-21 21:17 UTC, latran commented
@ColeHiggins2 any updates on this?  You still need help?

2022-03-08 20:24 UTC, JacobCallahan commented
Bump

2022-08-16 09:22 UTC, Gauravtalreja1 commented
@ColeHiggins2 Can you update this PR?

2023-06-11 05:34 UTC, closed without merging