[Cherry-Pick] Remove Selenium dependency from 6.10.z
SatelliteQE/robottelo pull request #9262
Opened 2021-12-27 08:44 UTC by jyejare

Cherry-Picked #9256 !

2021-12-27 13:56 UTC, JacobCallahan approved these changes

2021-12-27 19:40 UTC, Gauravtalreja1 requested changes
From your branch name `jyejare:6.10.z`, assuming this PR for 6.10.z branch, but you're targetting it for master, is that intentional?

2021-12-28 08:31 UTC, jyejare commented
@Gauravtalreja1 Oops ! Great catch :)

Let me close this and open a new one !

2021-12-28 08:49 UTC, Gauravtalreja1 approved these changes

2021-12-28 13:01 UTC, jyejare commented
Merging with 2 ACKs !

2021-12-28 13:01 UTC, merged