Fixing UI test_errata
SatelliteQE/robottelo pull request #9479
Opened 2022-04-06 08:57 UTC by akhil-jha

1. Adding coverage for BZ2029192
2. Minor Assertion updates.
3. Removing 1 test as BZ is on WONTFIX

2022-04-06 08:57 UTC, akhil-jha commented
trigger: robottelo
pytest: tests/foreman/ui/test_errata.py

2022-04-06 11:01 UTC, jyejare requested changes
ACK pending changes requested !

2022-04-07 09:31 UTC, akhil-jha commented on tests/foreman/ui/test_errata.py
> +    :BZ: 2029192
yes

2022-04-07 09:31 UTC, akhil-jha commented on tests/foreman/ui/test_errata.py
> +        session.settings.update('name = remote_execution_by_default', 'Yes')  # BZ 2029192
Changes made. Could you please re-review it?

2022-04-07 09:31 UTC, akhil-jha commented on tests/foreman/ui/test_errata.py
> -def test_positive_content_host_errata_details(session, erratatype_vm, module_org, test_name):
The test is actually failing.

2022-04-07 09:31 UTC, akhil-jha commented on tests/foreman/ui/test_errata.py
> -@pytest.mark.skip_if_open('BZ:2013093')
Done

2022-04-07 09:32 UTC, akhil-jha commented on tests/foreman/ui/test_errata.py
> +            _set_setting_value(errata_status_installable, True)
Same as above

2022-04-07 14:31 UTC, jyejare approved these changes

2022-04-07 20:52 UTC, latran approved these changes
ACK

2022-04-11 08:33 UTC, pondrejk approved these changes
ack pending docstring fix

2022-04-11 08:33 UTC, pondrejk commented on tests/foreman/ui/test_errata.py
> -@pytest.mark.skip_if_open('BZ:2013093')
sorry but I don't see it added, did you push?

2022-04-11 08:39 UTC, akhil-jha commented on tests/foreman/ui/test_errata.py
> -@pytest.mark.skip_if_open('BZ:2013093')
Oops, I added in the wrong place!! :open_mouth: 
Done now.

2022-04-12 07:29 UTC, merged