Add test for deleting rhrepo
SatelliteQE/robottelo pull request #9580
Opened 2022-05-12 19:02 UTC by sambible

Test for BZ 1152672

2022-05-12 20:03 UTC, latran requested changes

2022-05-12 20:03 UTC, latran commented on tests/foreman/ui/test_repository.py
> +def test_positive_delete_rhrepo(session, module_org):
```suggestion
def test_positive_delete_rhel_repo(session, module_org):
```

2022-05-12 20:03 UTC, latran commented on tests/foreman/ui/test_repository.py
> +
missing customer case docstring:

`:customerscenario: true`

2022-05-12 20:05 UTC, latran commented
trigger: robottelo
pytest: tests/foreman/ui/test_repository.py -k test_positive_delete_rhrepo

2022-05-12 21:09 UTC, sambible commented
trigger: robottelo
pytest: tests/foreman/ui/test_repository.py -k test_positive_delete_rhel_repo

2022-05-13 21:08 UTC, latran requested changes

2022-05-13 21:08 UTC, latran commented on tests/foreman/ui/test_repository.py
> +def test_positive_delete_rhel_repo(session, module_org):
You passed in `module_org`, but I don't see it being used.  Instead, I see you also called `entities.Organization().create()`.

Use one or the other.  In this instance, use `module_org`

2022-05-13 21:08 UTC, latran commented on tests/foreman/ui/test_repository.py
> +
Delete whitespace

2022-05-13 21:08 UTC, latran commented on tests/foreman/ui/test_repository.py
> +
Delete whitespace

2022-05-23 11:18 UTC, pondrejk approved these changes
ack, minor comment

2022-05-23 11:18 UTC, pondrejk commented on tests/foreman/ui/test_repository.py
> +        )
reading the bz, if the product contained just a single repo, it should be cleaned up after repo removal, maybe worth asserting for that too

2022-05-24 21:11 UTC, ColeHiggins2 approved these changes
ACK, Pending @latran comment

2022-05-27 01:45 UTC, latran approved these changes
ACK

2022-05-27 12:30 UTC, merged