automation for closed loop bz 2044631 for 6.11
SatelliteQE/robottelo pull request #9590
Opened 2022-05-16 21:55 UTC by latran

Close loop bug for https://bugzilla.redhat.com/show_bug.cgi?id=2044631.   The CLI does not have a way to check the presence of the packages in a cv so I cannot automate.

Finally, I discovered a bug when I wrote this.  Waiting for it to be fixed before taking this out of draft.

2022-06-01 01:03 UTC, latran commented
added skip marker for https://bugzilla.redhat.com/show_bug.cgi?id=2086957

2022-06-16 14:57 UTC, vsedmik requested changes
Just one change requested, otherwise looks good to me.

2022-06-17 07:16 UTC, vsedmik approved these changes

2022-06-17 15:37 UTC, mshriver commented on tests/foreman/ui/test_contentview.py
> +    with manifests.clone() as manifest:
Why not use any of the existing fixtures for module cloning?

2022-06-17 15:38 UTC, mshriver approved these changes
Approved, but I think the manifest cloning could be done in setup via existing fixtures.

2022-06-27 18:42 UTC, merged