location selection for UI job invocation test
SatelliteQE/robottelo pull request #9789
Opened 2022-07-18 13:40 UTC by pondrejk

Previously, the test selected organization but not location, causing assertion error as the host couldn't be found

2022-07-18 13:42 UTC, omkarkhatavkar approved these changes

2022-07-18 21:35 UTC, latran requested changes
Can you include some test results? Other than that, everything looks good!

2022-07-19 12:25 UTC, pondrejk commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_jobinvocation.py -k  test_positive_run_default_job_template_by_ip

2022-07-19 13:50 UTC, pondrejk commented
@latran robottelo-runner passed :)

2022-07-19 14:10 UTC, latran approved these changes

2022-07-22 21:52 UTC, Gauravtalreja1 approved these changes

2022-07-22 21:52 UTC, merged