Adding subcomponent docstring for Candlepin in test cases where appropriate
SatelliteQE/robottelo pull request #9819
Opened 2022-07-21 21:23 UTC by latran

This is a continuation of last month from an email I sent out about adding `subcomponent` for components that are shared with a katello component, but not necessary covered in automation.  I'm now implementing this for a few test cases that I think `Candlepin` shares with another component.  I'm putting this in draft for now because I still want to go through it more thoroughly, but still wanted some feedback from the original component owner in the files and others.

1. What do you guys think of this simple change?
2. @mshriver How long would it take to inject this new field into ibutsu/ReportPortal?
3. Other feedback?

2022-07-22 06:21 UTC, shweta83 commented on tests/foreman/cli/test_host.py
> +    :subcomponent: Candlepine
Candlepin*

2022-07-22 06:21 UTC, shweta83 commented on tests/foreman/ui/test_contenthost.py
> +    :subcomponent: Candlepine
Candlepin*

2022-07-22 06:21 UTC, shweta83 commented on tests/foreman/ui/test_contenthost.py
> +    :subcomponent: Candlepine
Candlepin*

2022-07-22 06:21 UTC, shweta83 commented on tests/foreman/ui/test_subscription.py
> +    :subcomponent: Candlepine
Candlepin*

2022-07-22 06:21 UTC, shweta83 commented on tests/foreman/ui/test_subscription.py
> +    :subcomponent: Candlepine
Candlepin*

2022-07-22 06:21 UTC, shweta83 commented on tests/foreman/ui/test_subscription.py
> +    :subcomponent: Candlepine
Candlepin*

2022-07-22 06:21 UTC, shweta83 commented on tests/foreman/ui/test_subscription.py
> +    :subcomponent: Candlepine
Candlepin*

2022-07-22 11:18 UTC, mshriver commented
@latran concerning RP/ibutsu, they accept all metadata key/value pairs defined by markers/user_properties.

See this module for how those markers/metadata are processed and injected into user_properties for junit:
https://github.com/SatelliteQE/robottelo/blob/master/pytest_plugins/metadata_markers.py

Concerning polarion/testimony, we'll need updated in polarion admin for our project to allow specifying subcomponent, and we'll want to validate subcomponent just like component.

2022-07-26 20:43 UTC, JacobCallahan approved these changes

2022-07-27 07:42 UTC, peterdragun approved these changes

2022-07-29 19:14 UTC, JacobCallahan requested changes
Looks like you need to add `SubComponent` and at least `Candlepin` below it in `testimony.yaml`

2022-11-30 05:36 UTC, closed without merging