Automation for bz-2038388
SatelliteQE/robottelo pull request #9839
Opened 2022-07-26 22:49 UTC by latran

Adding coverage for this candlepin bz.  Will post test results later.

2022-07-27 17:41 UTC, JacobCallahan requested changes

2022-07-27 17:41 UTC, JacobCallahan commented on tests/foreman/ui/test_activationkey.py
> +def test_positive_ak_with_custom_product_on_rhel6(session, rhel6_contenthost, target_sat):
If you're inheriting `target_sat`, it would be best to use it for entity and UI interactions in this test.

2022-07-27 17:41 UTC, JacobCallahan commented on tests/foreman/ui/test_activationkey.py
> +    org = entities.Organization().create()
for example
```suggestion
    org = target_sat.api.Organization().create()
```

2022-07-27 17:41 UTC, JacobCallahan commented on tests/foreman/ui/test_activationkey.py
> +    with session:
ui example
```suggestion
    with target_sat.ui_session():
```

2022-07-29 18:37 UTC, latran commented
Test results
```
pytest tests/foreman/cli/test_activationkey.py -k test_positive_ak_with_custom_product_on_rhel6

========= 1 passed, 144 deselected, 2 warnings in 517.70s (0:08:37) ==========

pytest tests/foreman/ui/test_activationkey.py -k test_positive_ak_with_custom_product_on_rhel6
======== 1 passed, 40 deselected, 3 warnings in 663.25s (0:11:03) ===============
```

2022-07-29 19:21 UTC, JacobCallahan requested changes
one last quick change

2022-07-29 19:21 UTC, JacobCallahan commented on tests/foreman/ui/test_activationkey.py
> +    entities_ids = setup_org_for_a_custom_repo(
```suggestion
    entities_ids = target_sat.cli_factory.setup_org_for_a_custom_repo(
```

2022-07-29 19:38 UTC, JacobCallahan approved these changes

2022-07-29 20:07 UTC, merged