Update the Sat version fallback to 6.12
SatelliteQE/robottelo pull request #9851
Opened 2022-07-29 20:46 UTC by JacobCallahan

After branching, we need to make sure we're falling back to the correct version.

2022-07-29 20:54 UTC, latran approved these changes

2022-07-29 20:55 UTC, latran requested changes

2022-07-29 20:55 UTC, latran commented on robottelo/constants/__init__.py
>  SATELLITE_OS_VERSION = "7"
This is supposed to be 8 in 6.12 right?

2022-07-29 21:07 UTC, JacobCallahan commented on robottelo/constants/__init__.py
>  SATELLITE_OS_VERSION = "7"
oohhhh good catch!

2022-07-29 21:25 UTC, latran approved these changes

2022-08-01 09:27 UTC, ogajduse reviewed
@JacobCallahan Do you want to change `constants.REPOS` in this PR? I see Satellite version strings there that are good candidates to be updated too.

2022-08-01 14:25 UTC, merged