Test for checking contents_changed after repo sync
SatelliteQE/robottelo pull request #9892
Opened 2022-08-02 18:36 UTC by ColeHiggins2

New customer scenario for testing contents_changed after repo sync

2022-08-02 18:37 UTC, ColeHiggins2 commented
Confirm functionality with dev

2022-08-03 16:26 UTC, ColeHiggins2 commented
When running the contents_changed command in the CLI, I get 0 rows returned( This is what we want)
```
could not change directory to "/root": Permission denied
 class | execution_plan_uuid | input 
-------+---------------------+-------
(0 rows)
```
However, when running the command via target_sat.execute() I get an empty string. Am I correct in assuming this is the same as (0 rows)?

2022-08-03 17:42 UTC, mshriver commented on tests/foreman/api/test_repository.py
> +        entities.Repository(id=repo_id).sync()
Please use `target_sat.api.Repository()`

2022-08-03 17:44 UTC, mshriver commented on tests/foreman/api/test_repository.py
> +            upload_manifest(module_org.id, manifest.content)
https://github.com/SatelliteQE/robottelo/blob/0018520356b29fe680bb931791bc55f17f0a76f0/pytest_fixtures/component/taxonomy.py#L62

Looks like this fixture would be appropriate for the test so you don't have to handle the manifest within the call phase.

2022-08-03 17:46 UTC, mshriver commented
@ColeHiggins2 concerning your comment about the return from the `psql` command execution, sounds fine to me. Its a matter of the defaults for the table (or lack of) output when running the command directly, versus the formatting that hammer CLI is doing.

You can add an additional check against the return code of the command - to make sure that it was successful and returned nothing to stdout.

2022-08-03 23:05 UTC, latran requested changes
Pending test run result after changes.

2022-08-04 12:52 UTC, Griffin-Sullivan commented on tests/foreman/api/test_repository.py
> +        assert 1 == 1
What's the purpose of this assertion?

2022-08-05 18:03 UTC, ColeHiggins2 commented on tests/foreman/api/test_repository.py
> +        assert 1 == 1
accidentally left in there. oops

2022-08-05 18:30 UTC, latran commented
trigger: test-robottelo
pytest: tests/foreman/api/test_repository.py -k test_positive_sync_repo_null_contents_changed

2022-08-05 18:49 UTC, latran requested changes

2022-08-05 18:49 UTC, latran commented on tests/foreman/api/test_repository.py
> +        assert prod_log_out.stdout == ''
Can you also add a `prod_log_out.status`?  It might be a better output than `stdout`.

2022-08-10 19:07 UTC, mshriver commented on tests/foreman/api/test_repository.py
> +
```suggestion

```

2022-08-10 19:08 UTC, mshriver approved these changes

2022-08-10 19:08 UTC, mshriver commented on tests/foreman/api/test_repository.py
> +
This will fix pre-commit failures.

2022-08-10 19:27 UTC, latran approved these changes

2022-08-10 19:29 UTC, Griffin-Sullivan approved these changes

2022-08-10 19:36 UTC, merged