Add check subscription startdate displayed
SatelliteQE/robottelo pull request #9896
Opened 2022-08-02 20:20 UTC by swadeley

Hello

A simple check but a lot of setup so I have added it to the end_to_end test.

This is closed loop for:
[Bug 1920860 – The Start Date field is blank for Subscriptions within Content Hosts page in Satellite WebUI](https://bugzilla.redhat.com/show_bug.cgi?id=1920860)

but with workaround for bug:
[Bug 2112320](https://bugzilla.redhat.com/show_bug.cgi?id=2112320) - Hidden column between Quantity and Attached in the table of subscriptions

2022-08-02 20:24 UTC, swadeley commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_contenthost.py::test_positive_end_to_end

2022-08-03 20:41 UTC, ColeHiggins2 approved these changes
Looks good to me

2022-08-03 23:00 UTC, latran approved these changes

2022-08-04 12:36 UTC, jameerpathan111 requested changes

2022-08-04 12:36 UTC, jameerpathan111 commented on tests/foreman/ui/test_contenthost.py
> +            assert startdate in custom_sub['Starts']
```suggestion
        # Check start date for BZ#1920860 (but handle BZ#2112320 offset-by-one bug)
        custom_product_name = module_repos_collection_with_manifest.custom_product['name']
        custom_sub = next(
                item
                for item in chost['subscriptions']['resources']['assigned']
                if item["Repository Name"] == custom_product_name
            )
        if is_open('BZ:2112320'):
            assert startdate in custom_sub['Expires']
        else:
            assert startdate in custom_sub['Starts']
```

2022-08-04 13:49 UTC, mshriver approved these changes

2022-08-04 13:50 UTC, mshriver commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_contenthost.py::test_positive_end_to_end

2022-08-04 14:05 UTC, mshriver commented on tests/foreman/ui/test_contenthost.py
> +            )
```suggestion
            item
            for item in chost['subscriptions']['resources']['assigned']
            if item["Repository Name"] == custom_product_name
            )
```

2022-08-04 14:28 UTC, jameerpathan111 commented
trigger: test-robottelo
pytest: tests/foreman/ui/test_contenthost.py::test_positive_end_to_end

2022-08-04 14:29 UTC, jameerpathan111 approved these changes

2022-08-04 14:59 UTC, merged

2022-08-07 15:50 UTC, swadeley commented
Thank you.